### ISSUE TITLE
Server3.py error

### ISSUE THREAD

**Issue by AChagan** [insidesherpa/JPMC-tech-task-2-PY3#1]
Hello,

When starting the server I'm running into the following error:

![server3py](https://user-images.githubusercontent.com/43882314/67723675-a188f080-f9d4-11e9-8700-7e94a6685ba5.png)

**Environment**
OS: Windows 10 64bits
Python: 3.7.5
npm: 6.12.0
node: v12.13.0

Thank you

**Comment by brianrodriguez** [comment]
try running "python datafeed/server3.py" from the parent directory. I was getting the same error when trying to run the server directly in the datafeed directory, but it works if you cd .. to the parent.

**Comment by AChagan** [comment]
Thank you brian, it worked!

**Comment by jbf-insidesherpa** [comment]
Thanks for helping clear the issues @brianrodriguez ! we've also updated the readme.  Should be using the same updates on the module pages themselves.
