### ISSUE TITLE
not able to start the server

### ISSUE THREAD

**Issue by harshul21** [insidesherpa/JPMC-tech-task-2-PY3#105]
when I am writing the command
python3 datafeed/server3.py
I am getting the issue that python 3 is not recognized as an internal or external command.
pls help me for the above issue

**Comment by rs043866** [comment]
You have to set the Environment variable if you are using Windows 10, or try installing the python again.

**Comment by SiddhlodaAyyar** [comment]
Watch this video and if you still get the error comment down in the youtube section and we'll try to solve it.
https://youtu.be/wRAG9i8O_44

**Comment by archi-007** [comment]
See if you are on linux you need to install python by sudo apt install python3.
And if you are on Windows you need to install python3 from their website and add it to your path(environment variables).
Cheers!
