### ISSUE TITLE
npm install&start failure

### ISSUE THREAD

**Issue by SiddhantDugar** [insidesherpa/JPMC-tech-task-2-PY3#106]
tried all the steps mentioned in the guide but still unable to install.

npm start
npm ERR! missing script: start

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/siddhantdugar/.npm/_logs/2020-05-02T14_16_34_231Z-debug.log
Siddhants-MacBook-Pro:~ siddhantdugar$ npm config set python3 /usr/bin/python3
Siddhants-MacBook-Pro:~ siddhantdugar$ npm install
npm WARN siddhantdugar@1.0.0 No description
npm WARN siddhantdugar@1.0.0 No repository field.

audited 2 packages in 0.693s
found 0 vulnerabilities

Siddhants-MacBook-Pro:~ siddhantdugar$ npm start
npm ERR! missing script: start

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/siddhantdugar/.npm/_logs/2020-05-02T14_17_27_817Z-debug.log

**Comment by vatsalajha** [comment]
npm ERR! missing script: start

It means you have to update start part in your package.json file.
Even I am facing same issue, as I don't know, what should be the start file

**Comment by Pranathi-star** [comment]
C:\Users\prana>npm install
npm WARN saveError ENOENT: no such file or directory, open 'C:\Users\prana\package.json'
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\prana\package.json'
npm WARN prana No description
npm WARN prana No repository field.
npm WARN prana No README data
npm WARN prana No license field.

up to date in 1.258s
found 0 vulnerabilities

I made sure that npm is mapping python 2.7 and the python on my computer is also 2.7. I don't understand whats the issue

**Comment by vatsalajha** [comment]
1)You close the terminal you are currently working on
2) download the node_module dependencies, given in the link from slides( I think it's in the last)
3) Delete the node _module dependency currently residing in your JPMC... Task 2 folder.
4) Unzip the node_module dependency folder that you downloaded and move the extracted folder to your JPMC... Task 2 folder 
5)Now, you need to open the terminal again , go inside your JPMC task2 folder by cd-ing into it 
6)now type npm install and ignore any warnings, and it will load for a bit
7) then type npm start, and if all is correct ,your web page will start
Try this step by step, and if you face any issue, comment here.

**Comment by Pranathi-star** [comment]
Thank you for the help. It worked. I reached the final display page on my
browser.

**Comment by vatsalajha** [comment]
That's great 😊

**Comment by guptasubham** [comment]
it worked finally....thanks a ton:)

> 1)You close the terminal you are currently working on
> 2) download the node_module dependencies, given in the link from slides( I think it's in the last)
> 3) Delete the node _module dependency currently residing in your JPMC... Task 2 folder.
> 4) Unzip the node_module dependency folder that you downloaded and move the extracted folder to your JPMC... Task 2 folder
> 5)Now, you need to open the terminal again , go inside your JPMC task2 folder by cd-ing into it
> 6)now type npm install and ignore any warnings, and it will load for a bit
> 7) then type npm start, and if all is correct ,your web page will start
> Try this step by step, and if you face any issue, comment here.

**Comment by vatsalajha** [comment]
Good for you.

**Comment by SiddhantDugar** [comment]
> 1)You close the terminal you are currently working on
> 2) download the node_module dependencies, given in the link from slides( I think it's in the last)
> 3) Delete the node _module dependency currently residing in your JPMC... Task 2 folder.
> 4) Unzip the node_module dependency folder that you downloaded and move the extracted folder to your JPMC... Task 2 folder
> 5)Now, you need to open the terminal again , go inside your JPMC task2 folder by cd-ing into it
> 6)now type npm install and ignore any warnings, and it will load for a bit
> 7) then type npm start, and if all is correct ,your web page will start
> Try this step by step, and if you face any issue, comment here.

Finally worked ! Thank you for your help :)

**Comment by vatsalajha** [comment]
Your welcome 😊
