### ISSUE TITLE
line 338 run(App()) ,line 261 self,sim_start,_,_ = next(self._data_1)

### ISSUE THREAD

**Issue by 77Siddharth** [insidesherpa/JPMC-tech-task-2-PY3#107]
stop iteration error. 
I did try to troubleshoot 8085 port method but still gives me the same error.
![ss](https://user-images.githubusercontent.com/30522963/80867126-0be65a80-8cb0-11ea-99c7-7ffb4194f36a.png)

**Comment by Ziva1811** [comment]
I am also getting the same error. Don't know how to resolve

**Comment by VishalKhurana** [comment]
I am too getting the same error.Any help would be appreciated.
Thanks.

**Comment by niksm7** [comment]
I am facing the same error please help.

**Comment by rs043866** [comment]
I am also facing the same error, please help

**Comment by rs043866** [comment]
Try changing port 8085 and run the server.py outside of datafeed directory, like.. 
python datafeed/server3.py

**Comment by niksm7** [comment]
Thanks @rs043866 it worked for me!

**Comment by sg28march** [comment]
> Try changing port 8085 and run the server.py outside of datafeed directory, like..
> python datafeed/server3.py

Thanks @rs043866 
It worked !!

**Comment by rhythm10** [comment]
> Try changing port 8085 and run the server.py outside of datafeed directory, like..
> python datafeed/server3.py

works, thanx, but too confused why it works like this only
