### ISSUE TITLE
Failed to Compile (Task 2 Setup)

### ISSUE THREAD

**Issue by cathy-yue** [insidesherpa/JPMC-tech-task-2-PY3#108]
I am getting this issue when I run the npm start command. I wasn't able to sucessfully run npm install and even tried all the trouble shooting solutions. I ended up downloading the node_modules and replacing it and finally npm start worked. However, now I have this error and I am not sure where to start. 

![npmInstall](https://user-images.githubusercontent.com/64174326/80872370-7c28b800-8c7f-11ea-92dd-f78aa4a23e95.png)

**Comment by Inderjeet0003** [comment]
as already in another issues.Delete ur node_module folder and download it from drive link given and then place it place of deleted node_module.Hope it will work cozz it worked for me.
drive link:
https://drive.google.com/uc?export=download&confirm=8PQ0&id=1ML6nECK18J0jM3hhfJdSCRtCNLssruYQ

**Comment by cathy-yue** [comment]
> as already in another issues.Delete ur node_module folder and download it from drive link given and then place it place of deleted node_module.Hope it will work cozz it worked for me.
> drive link:
> https://drive.google.com/uc?export=download&confirm=8PQ0&id=1ML6nECK18J0jM3hhfJdSCRtCNLssruYQ

Thank you for your help! I actually tried that before I opened this issue but it turns out I unzipped the file but didn't replace the node_module correctly. But since it worked for you I tried it again and it helped a lot.
