### ISSUE TITLE
Failed to open Webpage

### ISSUE THREAD

**Issue by krish-gangwar** [insidesherpa/JPMC-tech-task-2-PY3#11]
![Screenshot from 2019-11-11 00-21-48](https://user-images.githubusercontent.com/46054056/68549010-790fe600-0419-11ea-8b8b-d63105c46ec9.png)
![Screenshot from 2019-11-11 00-25-04](https://user-images.githubusercontent.com/46054056/68549038-cab87080-0419-11ea-89b1-ef39601b8a6c.png)
![Screenshot from 2019-11-11 00-25-10](https://user-images.githubusercontent.com/46054056/68549039-cab87080-0419-11ea-92a0-55304a1f15b2.png)
![Screenshot from 2019-11-11 00-25-23](https://user-images.githubusercontent.com/46054056/68549040-cb510700-0419-11ea-90d6-9cb5cd0d2e53.png)
![Screenshot from 2019-11-11 00-25-30](https://user-images.githubusercontent.com/46054056/68549041-cb510700-0419-11ea-88e5-0d3573d917e5.png)

**Comment by jbf-insidesherpa** [comment]
@krish-gangwar what's your node version and npm version.
The recommended version for this project is node v11.0.0 and npm v6.4.1

**Comment by AntMan242** [comment]
I got the same issue, and i did an npm i (install) table, and it accepted the jpmorgan perspective import..

**Comment by krish-gangwar** [comment]
Thank you @jbf-insidesherpa and @AntMan242 . It worked finally.
