### ISSUE TITLE
npm install failed, missing dependencies

### ISSUE THREAD

**Issue by GryphonTorch** [insidesherpa/JPMC-tech-task-2-PY3#116]
Hi I got the following error message when I started the npm install step:
![npm_error](https://user-images.githubusercontent.com/45518553/81039052-898dae80-8eda-11ea-939b-c488836cc021.png)

I downloaded the google drive folder for node modules and replaced it, am running visual studio 2017 and python 2.7, 3 installed. 
![folder](https://user-images.githubusercontent.com/45518553/81039147-c3f74b80-8eda-11ea-9714-3bcbe07b49ca.png)
Thanks!

**Comment by GryphonTorch** [comment]
Downloaded the modules zip for WIN, which fixed the install program (246 MB sized zip)

**Comment by nikhilgy** [comment]
from where did you download modules zip please tell

**Comment by GryphonTorch** [comment]
@nikhilgy try this link: https://drive.google.com/file/d/1ML6nECK18J0jM3hhfJdSCRtCNLssruYQ/view 
the 246 MB zip folder worked for my windows laptop. Hope this helps!

**Comment by nikhilgy** [comment]
> @nikhilgy try this link: https://drive.google.com/file/d/1ML6nECK18J0jM3hhfJdSCRtCNLssruYQ/view
> the 246 MB zip folder worked for my windows laptop. Hope this helps!

it worked.Thanks
But now npm start is giving issue

![Screenshot (35)](https://user-images.githubusercontent.com/63981603/81400094-fe1a5480-9149-11ea-8dc9-f2b305ca9069.png)
