### ISSUE TITLE
Unable to generate patch file

### ISSUE THREAD

**Issue by venkataadithyavarmachendeti** [insidesherpa/JPMC-tech-task-2-PY3#120]
C:\Users\Admin\JPMC-tech-task-2-PY3>git commit -m 'Create Patch File'
error: pathspec 'Patch' did not match any file(s) known to git
error: pathspec 'File'' did not match any file(s) known to git

**Comment by Syeda-Sufia** [comment]
> C:\Users\Admin\JPMC-tech-task-2-PY3>git commit -m 'Create Patch File'
> error: pathspec 'Patch' did not match any file(s) known to git
> error: pathspec 'File'' did not match any file(s) known to git

Use Double quotes instead. 
=> git commit -m "Create Patch File"
Worked for me :)

**Comment by SiddhlodaAyyar** [comment]
Watch this video and if you still get the error comment down in the youtube section and we'll try to solve it.
https://youtu.be/wRAG9i8O_44
