### ISSUE TITLE
Clicking Start Streaming Data doesn't do anything 

### ISSUE THREAD

**Issue by cathy-yue** [insidesherpa/JPMC-tech-task-2-PY3#121]
I am using a windows operating system and when I ran "npm start" it automatically uses Microsoft edge. However, when I click "start streaming data" nothing happens. Then I clicked the tool icon and I see a chart but no data. Does anyone know what I can do to fix this?

![bank merge](https://user-images.githubusercontent.com/64174326/81085081-bf279d00-8ec4-11ea-82ee-8542cd76bbdc.png)
![bank merge1](https://user-images.githubusercontent.com/64174326/81085087-bfc03380-8ec4-11ea-8e34-5832015c00f5.png)

**Comment by mk1107** [comment]
open new command prompt  (as an administrator)
go to the project file
then run this command python datafeed/server3.py


this is because you need to run server file along with client file

**Comment by cathy-yue** [comment]
> open new command prompt (as an administrator)
> go to the project file
> then run this command python datafeed/server3.py
> 
> this is because you need to run server file along with client file

Hello sorry for the late reply and I appreciate your help! However, when I did this the last time I am pretty sure I ran that command. I tried it again today and it is now giving me an ImportError:

Traceback (most recent call last):
  File "datafeed/server3.py", line 26, in <module>
    import dateutil.parser
ImportError: No module named dateutil.parser

The last time I did this I did not get this error and the only thing I've changed with that I downloaded node_modules using the file provided to us in the instructions: https://drive.google.com/file/d/1ML6nECK18J0jM3hhfJdSCRtCNLssruYQ/view

I then replaced node_modules from that file with the one I currently have. Last time I did this it worked for me and now it is giving me this error when I run the command you suggested, even though I did not change anything.

Do you know what I can do to fix this?

**Comment by cathy-yue** [comment]
Also I want to add that I did first try following the troubleshooting page with this issue. I have pip installed. However, I do not think I correctly put it in the system's environment variable. 

I also ran pip install python-dateutil afterwards  and it says that the requirement is already satisified so I figured I followed the trouble shooting instructions correctly.

**Comment by mk1107** [comment]
> > open new command prompt (as an administrator)
> > go to the project file
> > then run this command python datafeed/server3.py
> > this is because you need to run server file along with client file
> 
> Hello sorry for the late reply and I appreciate your help! However, when I did this the last time I am pretty sure I ran that command. I tried it again today and it is now giving me an ImportError:
> 
> Traceback (most recent call last):
> File "datafeed/server3.py", line 26, in
> import dateutil.parser
> ImportError: No module named dateutil.parser
> 
> The last time I did this I did not get this error and the only thing I've changed with that I downloaded node_modules using the file provided to us in the instructions: https://drive.google.com/file/d/1ML6nECK18J0jM3hhfJdSCRtCNLssruYQ/view
> 
> I then replaced node_modules from that file with the one I currently have. Last time I did this it worked for me and now it is giving me this error when I run the command you suggested, even though I did not change anything.
> 
> Do you know what I can do to fix this?

The error which u r getting is due to pip. Same problem when I was facing it did pip install 2-3 times and make sure that u r in proper directory.

**Comment by mk1107** [comment]
U need to trial and error for all such problems
Hope your problem gets resolved soon

**Comment by SiddhlodaAyyar** [comment]
Watch this video and if you still get the error comment down in the youtube section and we'll try to solve it.
https://youtu.be/wRAG9i8O_44

**Comment by cathy-yue** [comment]
> Watch this video and if you still get the error comment down in the youtube section and we'll try to solve it.
> https://youtu.be/wRAG9i8O_44

Thank you, I will let you know if I am still having issues. I am only available during the weekends so expect to hear from me in the youtube comments this weekend if I have an issue!

**Comment by cathy-yue** [comment]
> Watch this video and if you still get the error comment down in the youtube section and we'll try to solve it.
> https://youtu.be/wRAG9i8O_44

Your video helped me fix both of the problems I had. Thank you for the help!
