### ISSUE TITLE
react-scripts start

### ISSUE THREAD

**Issue by jay1499** [insidesherpa/JPMC-tech-task-2-PY3#122]
is there any fix for this issue?
my node and npm versions are correct and I am using python3 # @

![Screenshot (133)](https://user-images.githubusercontent.com/36840105/81091254-9632f680-8f1c-11ea-8b37-b8ddf718022b.png)

**Comment by tripathiritwik** [comment]
Same error is occuring on my system also.

**Comment by abhi17uec009bansal** [comment]
I am also getting same error_

**Comment by vskarthikprasad** [comment]
same in mine too...?

**Comment by AssanaliAbu** [comment]
anyone solved this?

**Comment by vskarthikprasad** [comment]
Uninstall all the components (npm,node,..etc)
Again Clone the git repo.
Go to datafeed folder (as admin) run the server
Now open another terminal(as admin) and go to datafeed folder and type "npm install"
ignore the log file errors
type "npm start"

This worked for me

**Comment by SiddhlodaAyyar** [comment]
Watch this video and if you still get the error comment down in the youtube section and we'll try to solve it.
https://youtu.be/wRAG9i8O_44
