### ISSUE TITLE
Couldn't complie

### ISSUE THREAD

**Issue by sanyadeveloper2000** [insidesherpa/JPMC-tech-task-2-PY3#123]
![Screenshot (110)](https://user-images.githubusercontent.com/47472176/81100403-1ad84180-8f2a-11ea-80c3-8a571fe97e36.png)
![Screenshot (111)](https://user-images.githubusercontent.com/47472176/81100419-2166b900-8f2a-11ea-8769-d9f4896201ce.png)
Hi, pls help me with this issue.
Thanks a lot.

**Comment by HaripriyaB** [comment]
Having same problem. Did u solve this issue?

**Comment by prafful98** [comment]
Try running this command `npm install @jpmorganchase/perspective`

**Comment by rahulsingh2301** [comment]
C:\Users\Rahul Singh\Desktop\JPMC-tech-task-2-PY3\datafeed>server3.py
Traceback (most recent call last):
  File "C:\Users\Rahul Singh\Desktop\JPMC-tech-task-2-PY3\datafeed\server3.py", line 320, in <module>
    run(App())
  File "C:\Users\Rahul Singh\Desktop\JPMC-tech-task-2-PY3\datafeed\server3.py", line 244, in __init__
    self._sim_start, _, _  = next(self._data_1)
StopIteration
i have tried turning off the firewall and changing port from 8080 to 8085 in server.py file.

**Comment by sanyadeveloper2000** [comment]
Thankyou
