### ISSUE TITLE
npm Install and npm start

### ISSUE THREAD

**Issue by sumit276** [insidesherpa/JPMC-tech-task-2-PY3#130]
I am having problem with npm install and npm start. Can anyone please help me out with this.
![Screenshot (74)](https://user-images.githubusercontent.com/41253436/81145441-ee590f80-8f93-11ea-99de-03d241c840e1.png)
![Screenshot (75)](https://user-images.githubusercontent.com/41253436/81145454-f2852d00-8f93-11ea-9ecb-cab4afff3d2c.png)

**Comment by Shashwat5497** [comment]
I'm also having problem.

**Comment by chhavikirtani2000** [comment]
Same Problem
