### ISSUE TITLE
Problem in npm start - OS: Windows

### ISSUE THREAD

**Issue by chhavikirtani2000** [insidesherpa/JPMC-tech-task-2-PY3#134]
![Screenshot (244)](https://user-images.githubusercontent.com/55941961/81172382-bcf43a00-8fbb-11ea-86d1-370438d7bc98.png)
At first, I got a warning of no package.json found. I looked up my folder and noticed that there existed a file named package-lock.json. To experiment with it, I renamed the package-lock.json as package.json. 
I ran the npm install and npm start commands again, and now I encounter the problem as shown in the screenshot.
Help me out. Thanks

**Comment by thetechlord21** [comment]
Try using npm install command in elevated command prompt (administrator) or use powershell it might solve the issue.

**Comment by chhavikirtani2000** [comment]
I did as you said and npm install completed successfully. But now when I run npm start, it gives me the following error.
![Screenshot (247)](https://user-images.githubusercontent.com/55941961/81173821-499ff780-8fbe-11ea-9179-c915d6eac841.png)

**Comment by thetechlord21** [comment]
try downloading node_modules from this link and extract to JPMC task dir and then run npm start 
https://drive.google.com/file/d/1ML6nECK18J0jM3hhfJdSCRtCNLssruYQ/view

**Comment by thetechlord21** [comment]
did u try powershell in any case ?
for me in powershell it worked.

**Comment by chhavikirtani2000** [comment]
It is not working, I tried PowerShell and downloading node_modules fro the link you gave. All give the same error as shown in the last comment

**Comment by thetechlord21** [comment]
u are in the task 1 directory switch to the task 2 directory and try again.
task 2 directory has the react scripts

**Comment by Shashwat5497** [comment]
I'm also having the same problem ,i had tried all the things mentioned above,here is the screen shot ,please help i'm stuck at this past 2 days.
i am using python 2.7
node 11.0.0
npm 6.14.4
nvm 1.1.7
![er4](https://user-images.githubusercontent.com/49050458/81274525-0c933e00-906e-11ea-8bf6-4164013c7b82.png)

**Comment by thetechlord21** [comment]
In our setup node-gyp is called by way of npm, so in order for you to avoid the
error, you have to explicitly tell npm what python version to use. Thus, you
have to set npm's 'python' config key to the appropriate value:

**npm config set python /path/to/executable/python where /path/to/executable/python is the
directory where the python2.7.x binary is, for example in /usr/bin/python usually in linux/mac or
C:\\Python27 for Windows**

try these out and see if it works out else install python 3 and then install to path in environment variables and then repeat the steps again.

**Comment by bibhupad123** [comment]
I am also encountering same problem. I also tried doing all the process in power shell. Please Help. Thanks
