### ISSUE TITLE
error while doing npm install

### ISSUE THREAD

**Issue by dhruval-p** [insidesherpa/JPMC-tech-task-2-PY3#135]
![image](https://user-images.githubusercontent.com/45992807/81175852-dbf5ca80-8fc1-11ea-97f9-548329319358.png)

can anyone please help me to solve this ?

**Comment by abhi17uec009bansal** [comment]
You have to change your directory where JPMC-tech-task-2-PY3 is there.
![query](https://user-images.githubusercontent.com/64954536/81273945-4283f280-906d-11ea-8635-ace29d672d46.PNG)

**Comment by SiddhlodaAyyar** [comment]
Watch this video and if you still get the error comment down in the youtube section and we'll try to solve it.
https://youtu.be/wRAG9i8O_44
