### ISSUE TITLE
Error on npm start : Failed at the bank-merge-co-task-2@0.1.0 start script

### ISSUE THREAD

**Issue by chhavikirtani2000** [insidesherpa/JPMC-tech-task-2-PY3#138]
Error is shown in the screenshot. Any suggestions?

![Screenshot (249)](https://user-images.githubusercontent.com/55941961/81218572-06fd1000-8ffc-11ea-981a-f047cf4b59a8.png)

**Comment by thetechlord21** [comment]
u are in the task 1 directory switch to the task 2 directory and try again.
task 2 directory has the react scripts.

**Comment by chhavikirtani2000** [comment]
Thanks for that. Must have missed that :D 
I am getting an error while running server3.py as shown:
`Traceback (most recent call last):
  File "C:\Users\CHHAVI KIRTANI\Downloads\JPMC-tech-task-2-PY3-master\JPMC-tech-task-2-PY3-master\datafeed\server3.py", line 320, in <module>
    run(App())
  File "C:\Users\CHHAVI KIRTANI\Downloads\JPMC-tech-task-2-PY3-master\JPMC-tech-task-2-PY3-master\datafeed\server3.py", line 244, in __init__
    self._sim_start, _, _  = next(self._data_1)
StopIteration`
Any suggestions on this?

**Comment by thetechlord21** [comment]
Can u provide a screenshot with the same ? Like not just text of it ).
Also did u try adding python 3 to path in environment variables section?
also just asking :   did u execute the command in elevated command prompt (administrator) or powershell ?

**Comment by chhavikirtani2000** [comment]
Yeah, python is added to the path and I am running in administrator mode only. The following is the screenshot of the error.
![Screenshot (251)](https://user-images.githubusercontent.com/55941961/81293397-ea5be900-908a-11ea-8298-b2b36da51447.png)

**Comment by thetechlord21** [comment]
Try running it using python3 command instead of just python . if it still doesn't work then I do not 
have much idea as to what exactly the problem is

**Comment by chhavikirtani2000** [comment]
I had to catch the stopIteration exception everywhere whenever next was called because I looked it up and it is normal for the next function to throw an exception. Weird anybody else didn't get this exception :D 
Anyways it is solved now, Thanks!
