### ISSUE TITLE
Web page freezes after clicking start streaming data 

### ISSUE THREAD

**Issue by Tg0o0** [insidesherpa/JPMC-tech-task-2-PY3#14]
Hi there, my webpage just hangs when I click start streaming data, I'm currently using windows subsystem linux to compile npm install and npm start. when I click the start streaming data this shows on the terminal 
![image](https://user-images.githubusercontent.com/46705969/68769508-638bfd80-065f-11ea-8cb8-a7ff7e7bd1e5.png)
and this shows in the web browser
![image](https://user-images.githubusercontent.com/46705969/68769591-89b19d80-065f-11ea-8418-a1752ef4485e.png)

**Comment by jbf-insidesherpa** [comment]
@Tg0o0 try using a different browser to check localhost:3000. e.g. use Google chrome
