### ISSUE TITLE
npm install showing error

### ISSUE THREAD

**Issue by abhi17uec009bansal** [insidesherpa/JPMC-tech-task-2-PY3#143]
![jpmc](https://user-images.githubusercontent.com/64954536/81273249-3ba8b000-906c-11ea-95f4-0213bbf14665.PNG)

**Comment by saisriteja** [comment]
did u find any answer even I am getting the same error

**Comment by rahulsingh2301** [comment]
same here.

**Comment by saisriteja** [comment]
i did 
npm install get some error in .log content
continue with npm start by that a browser window pop up 
good luck

**Comment by rahulsingh2301** [comment]
Thanks, my issue was resolved.

**Comment by abhi17uec009bansal** [comment]
While doing npm start it is showing 'react-scripts' is not recognized as an internal or external command, 
![jpmc2](https://user-images.githubusercontent.com/64954536/81419775-709c2c00-916c-11ea-9ffa-a1eb1b50d029.PNG)
operable program or batch file.
