### ISSUE TITLE
Server application stuck. CMD doesn't respond.

### ISSUE THREAD

**Issue by IFHAM99** [insidesherpa/JPMC-tech-task-2-PY3#159]
![Capture](https://user-images.githubusercontent.com/50768671/81460803-49257d80-91c5-11ea-85d8-e74d309f6a8b.PNG)

**Comment by Rupesh-rkgit** [comment]
your server application has been started,now you have to open client application in another prompt.

**Comment by IFHAM99** [comment]
Okay. Thank you!
