### ISSUE TITLE
Windows npm install issue

### ISSUE THREAD

**Issue by MythreyanGanesh** [insidesherpa/JPMC-tech-task-2-PY3#16]
I am getting a bunch of errors when I try to install npm. Please help me, thanks. Attached are 2 screenshots
![Untitled](https://user-images.githubusercontent.com/56330768/68987014-e7bebc00-07ea-11ea-96f4-aa30fe5e89e0.png)
![Untitled2](https://user-images.githubusercontent.com/56330768/68987015-ea211600-07ea-11ea-94e8-f55af663f048.png)

**Comment by akshatbahety** [comment]
Please add this to #15 its about the same thing it would be better for moderators to work on it.

**Comment by jbf-insidesherpa** [comment]
@MythreyanGanesh and @akshatbahety the same potential solution to this issue is discussed in this thread:
https://github.com/insidesherpa/JPMC-tech-task-2/issues/11#issuecomment-554755677
