### ISSUE TITLE
Nothing returning after entering command npm config set msvs_version 2017

### ISSUE THREAD

**Issue by shashankvaranasi** [insidesherpa/JPMC-tech-task-2-PY3#165]
I*I have latest VS 2019
*Did not install windows 10 sdk(it was in optional components)
*Have python 3.8.2

Even npm install command returns error

What am I missing out on?
Even if I write npm config set msvs_version 2019
Nothing returns

**Comment by LordUttam** [comment]
Dont worry `npm config set msvs_version 2017` returns nothing. You need to execute `npm install` in datafeed folder. If it is returning error try `npm install --ignore-scripts` then go for `npm start`.

**Comment by Shiwani19890** [comment]
even after using `npm install --ignore-scripts` error is there

![Screenshot (1059)](https://user-images.githubusercontent.com/64477234/81473600-2e7ef300-921d-11ea-8ed4-2c6c173db58d.png)

**Comment by shashankvaranasi** [comment]
@LordUttam I did what you told by going through your previous posts and yes it solved the issue for me.
Thanks.

**Comment by LordUttam** [comment]
@Shiwani19890 Your issue is different. Here this might help: https://stackoverflow.com/questions/52586594/eslint-error-on-deployment-on-local-server-of-react-web-app
@shashankvaranasi Glad to help. Don't forget to close the issue .
