### ISSUE TITLE
nvm installation error

### ISSUE THREAD

**Issue by abhi4554** [insidesherpa/JPMC-tech-task-2-PY3#166]
which version is compatible with 32 bit??

**Comment by SiddhlodaAyyar** [comment]
Watch this video and if you still get the error comment down in the youtube section and we'll try to solve it.
https://youtu.be/wRAG9i8O_44

**Comment by abhi4554** [comment]
> Watch this video and if you still get the error comment down in the youtube section and we'll try to solve it.
> https://youtu.be/wRAG9i8O_44

it worked half a way then while installing npm its showing npm' is not recognized as an internal or external command,
operable program or batch file.
