### ISSUE TITLE
Network error after clicking start streaming data

### ISSUE THREAD

**Issue by ankitmpatil** [insidesherpa/JPMC-tech-task-2-PY3#17]
![Capture](https://user-images.githubusercontent.com/48452845/69281164-d3e1d400-0bb5-11ea-8f82-6ba823e94bd6.PNG)

FYI : I changed the port to 8085 port on server3.py

**Comment by jbf-insidesherpa** [comment]
@ankitmpatil you should have also changed the port on the clientside through src/DataStreamer.ts
Make sure you're also running the server script when you rerun npm start
