### ISSUE TITLE
NVM not installing.

### ISSUE THREAD

**Issue by IFHAM99** [insidesherpa/JPMC-tech-task-2-PY3#170]

**Comment by IFHAM99** [comment]
Shows nvm is not recognized as internal or external command.

**Comment by SiddhlodaAyyar** [comment]
Watch this video and if you still get the error comment down in the youtube section and we'll try to solve it.
https://youtu.be/wRAG9i8O_44

**Comment by IFHAM99** [comment]
Thank you.
