### ISSUE TITLE
Having issue that no such file or directory? Anyone plz help

### ISSUE THREAD

**Issue by Pratyaksh6666** [insidesherpa/JPMC-tech-task-2-PY3#178]
![error](https://user-images.githubusercontent.com/64814406/81504498-429f1f00-9307-11ea-9caa-0593c3c9fcac.png)

**Comment by SiddhlodaAyyar** [comment]
Watch this video and if you still get the error comment down in the youtube section and we'll try to solve it.
https://youtu.be/wRAG9i8O_44

**Comment by Pratyaksh6666** [comment]
> Watch this video and if you still get the error comment down in the youtube section and we'll try to solve it.
> https://youtu.be/wRAG9i8O_44



> Watch this video and if you still get the error comment down in the youtube section and we'll try to solve it.
> https://youtu.be/wRAG9i8O_44

Thank you so much.....
