### ISSUE TITLE
server3.py StopIteration

### ISSUE THREAD

**Issue by vkmanojk** [insidesherpa/JPMC-tech-task-2-PY3#179]
There seems to be some error with the next function used in the App class. This is the error that occurred:
```
Traceback (most recent call last):
  File "server3.py", line 320, in <module>
    run(App())
  File "server3.py", line 244, in __init__
    self._sim_start, __, _  = next(self._data_1)
StopIteration

```

**Comment by SiddhlodaAyyar** [comment]
Watch this video and if you still get the error comment down in the youtube section and we'll try to solve it.
https://youtu.be/wRAG9i8O_44

**Comment by Raj2367** [comment]
@vkmanojk  Use the command "python datafeed/server3.py" and if you are getting the same error again then change the port number 8080 to 8085 in server3.py using any text editor. otherwise, turn off your firewall for some time.

**Comment by vkmanojk** [comment]
@Raj2367  The error still persists. Changing port numbers doesn't seem to work.

**Comment by vkmanojk** [comment]
Thanks @SiddhlodaAyyar  and @Raj2367 . It works fine when I use 

> python datafeed/server3.py 
but the error occurs when I use 

> python server3.py 
inside the datafeed folder. I am not sure why. Can you brief on the same ?
