### ISSUE TITLE
error while installing npm

### ISSUE THREAD

**Issue by bhavyanagpal** [insidesherpa/JPMC-tech-task-2-PY3#180]
C:\Users\BHAVYA>npm install
npm WARN deprecated rollup-plugin-buble@0.16.0: This module has been deprecated and is no longer maintained. Please use @rollup/plugin-buble.
npm WARN deprecated circular-json@0.3.3: CircularJSON is in maintenance only, flatted is its successor.
npm ERR! code EEXIST
npm ERR! path C:\Users\BHAVYA\node_modules\acorn\bin\acorn
npm ERR! dest C:\Users\BHAVYA\acorn
npm ERR! EEXIST: file already exists, cmd shim 'C:\Users\BHAVYA\node_modules\acorn\bin\acorn' -> 'C:\Users\BHAVYA\acorn'npm ERR! File exists: C:\Users\BHAVYA\acorn
npm ERR! Remove the existing file and try again, or run npm
npm ERR! with --force to overwrite files recklessly.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\BHAVYA\AppData\Roaming\npm-cache\_logs\2020-05-10T06_09_41_228Z-debug.log

**Comment by SiddhlodaAyyar** [comment]
Watch this video and if you still get the error comment down in the youtube section and we'll try to solve it.
https://youtu.be/wRAG9i8O_44

**Comment by Pratyaksh6666** [comment]
Just run "npm install --ignore-scripts" . Ignore the warnings. And go for npm start again.
It should run properly now.
