### ISSUE TITLE
installing npm issue

### ISSUE THREAD

**Issue by JShimonov** [insidesherpa/JPMC-tech-task-2-PY3#19]
<img width="1920" alt="Screen Shot 2019-11-24 at 1 49 36 PM" src="https://user-images.githubusercontent.com/44530028/69499573-71dce380-0ec1-11ea-93e3-1f9fbe4d9c84.png">

**Comment by jbf-insidesherpa** [comment]
@JShimonov your issue can be solved if you look through the troubleshooting slides in the setup guide: https://insidesherpa.s3.amazonaws.com/vinternships/companyassets/Sj7temL583QAYpHXD/setup_devenv_m2_v8.pdf (for mac it's in the proximity of slides 24/95)

You'll probably need to `npm config set python /path/to/executable/python` where **/path/to/executable/python** is the
directory where the python2.7.x binary is, for example in /usr/bin/python usually in linux/mac or
C:\\Python27 for Windows

If you have python in your system, you can check where the binary is by executing `which python` in the terminal. Ideally this should be python 2.7.x
