### ISSUE TITLE
NetworkError: Failed to execute 'send' on 'XMLHttpRequest': Failed to load

### ISSUE THREAD

**Issue by hussainyasir23** [insidesherpa/JPMC-tech-task-2-PY3#198]
**Type error: Cannot find module '@jpmorganchase/perspective'.  TS2307**

    1 | import React, { Component } from 'react';
  > 2 | import { Table } from '@jpmorganchase/perspective';
      |                       ^
    3 | import { ServerRespond } from './DataStreamer';
    4 | import './Graph.css';
    5 |

**Comment by hussainyasir23** [comment]
**npm WARN bootstrap@4.2.1 requires a peer of jquery@1.9.1 - 3 but none is installed. You must install peer dependencies yourself.
npm WARN bootstrap@4.2.1 requires a peer of popper.js@^1.14.6 but none is installed. You must install peer dependencies yourself.
npm WARN extract-text-webpack-plugin@3.0.2 requires a peer of webpack@^3.1.0 but none is installed. You must install peer dependencies yourself.**

**Comment by hussainyasir23** [comment]
![Capture1](https://user-images.githubusercontent.com/48673014/81735683-09a3ad80-94b3-11ea-9090-7b4e82c33b8e.JPG)
I've used all correct versions as stated in guide

**Comment by SiddhlodaAyyar** [comment]
Watch this video and if you still get the error comment down in the youtube section and we'll try to solve it.
https://youtu.be/wRAG9i8O_44

**Comment by hussainyasir23** [comment]
Looks like the issue resolved but again another raised.
**NetworkError: Failed to execute 'send' on 'XMLHttpRequest': Failed to load 'http://localhost:8080/query?id=1'. #205**

**Comment by hussainyasir23** [comment]
Command Prompt Output

./src/Graph.tsx
  Line 64:37:  Unexpected mix of '&&' and '||'  no-mixed-operators
  Line 64:57:  Unexpected mix of '&&' and '||'  no-mixed-operators
  Line 65:37:  Unexpected mix of '&&' and '||'  no-mixed-operators
  Line 65:57:  Unexpected mix of '&&' and '||'  no-mixed-operators

Search for the keywords to learn more about each warning.
To ignore, add // eslint-disable-next-line to the line before.
