### ISSUE TITLE
npm start error

### ISSUE THREAD

**Issue by mbbharti** [insidesherpa/JPMC-tech-task-2-PY3#199]
i have installed npm but while running npm start command i am getting error
npm err path
npm err code
![image](https://user-images.githubusercontent.com/55251151/81735264-6e123d00-94b2-11ea-8975-06f4afae0eef.png)

**Comment by cef1998** [comment]
You are getting this error as `package.json` file is missing on current path.
Change your working directory to **JPMC-tech-task-2-PY3** , if you are using python3.x, and then run 
`npm install`   ignore the warnings  (no need to perform `npm audit fix`after this) then,
`npm start`   it will start your server and you can see localhost popup on your browser.

Hope this may solve your problem.

**Comment by mryupyup** [comment]
It doesn't work . It is still showing error

**Comment by SiddhlodaAyyar** [comment]
Watch this video and if you still get the error comment down in the youtube section and we'll try to solve it.
https://youtu.be/wRAG9i8O_44

**Comment by jamaltariqcheema** [comment]
I got the same errors. Even tried `npm audit fix` but not working.
<img width="746" alt="Screenshot 2020-05-15 at 8 03 04 AM" src="https://user-images.githubusercontent.com/37561305/82007010-8fc21e80-9682-11ea-81e8-44518e5936d5.png">
