### ISSUE TITLE
server3.py Error

### ISSUE THREAD

**Issue by shivamurali** [insidesherpa/JPMC-tech-task-2-PY3#2]
When running the python3 server3.py command, I run into the following error: 

(base) Shivas-MacBook-Pro-4:JPMC-tech-task-2-PY3 shiva$ python3 server3.py
python3: can't open file 'server3.py': [Errno 2] No such file or directory

Any help would be appreciated!

**Comment by zoluu** [comment]
The server3.py file is inside the folder datafeed, so perhaps try something like python3 datafeed/server3.py instead.

**Comment by jbf-insidesherpa** [comment]
Thanks for helping clear the issues @zoluu  ! we've also updated the readme. Should be using the same updates on the module pages themselves. cc @shivamurali
