### ISSUE TITLE
npm start running error -  Cannot find module '@jpmorganchase/perspective'.

### ISSUE THREAD

**Issue by pashovt** [insidesherpa/JPMC-tech-task-2-PY3#20]
Hi,

I am working through the second task for the JP Morgan internship.
I am using Windows 10 with python 3.8.0.

I have installed npm and I am using v 13.2.0.

When I try to run it I get the "Cannot find module '@jpmorganchase/perspective'" massage.

Type error: Cannot find module '@jpmorganchase/perspective'.  TS2307

    1 | import React, { Component } from 'react';
  > 2 | import { Table } from '@jpmorganchase/perspective';
      |                       ^
    3 | import { ServerRespond } from './DataStreamer';
    4 | import './Graph.css';
    5 |

The python file is running without a problem.

What do I need to do in order to make the web application work?

Kind Regrdas,
Tsvetomir Pashiv

**Comment by jbf-insidesherpa** [comment]
@pashovt please reread the setup guide. the proper node and npm version that's supposed to be used is mentioned there (i.e. node v11.0.0 and npm 6.4.1). You need to use nvm to properly manage those version. Also you need python2.7.x installed in your system as well as a node dependency, i.e. node-gyp needs that (the setup guide also discusses this (see troubleshooting slides)). It's okay to have multiple versions of python installed in your system.

**Comment by jbf-insidesherpa** [comment]
@pashovt I'm closing this issue now since it's been a while. Feel free to re-open if necessary
