### ISSUE TITLE
not able to create patch file 

### ISSUE THREAD

**Issue by managha** [insidesherpa/JPMC-tech-task-2-PY3#202]
git commit -m 'Create Patch File'
error: pathspec 'Patch' did not match any file(s) known to git
error: pathspec 'File'' did not match any file(s) known to git

im in the /JPMC-tech-task-2-PY3 directory itself

and using the command
>git format-patch -1 HEAD
gives me
0001-Update-README-setupv8.patch

but im not sure if it is the updated one.pls help out

**Comment by SiddhlodaAyyar** [comment]
Watch this video and if you still get the error comment down in the youtube section and we'll try to solve it.
https://youtu.be/wRAG9i8O_44
