### ISSUE TITLE
error while running Python3 server3.py

### ISSUE THREAD

**Issue by aaavinash85** [insidesherpa/JPMC-tech-task-2-PY3#203]
I cloned the repo to my local machine
I cd into task 2 python3 - datafeed and try to run $python3 server3.py and I run into following error
ryuk@ryuk:~/JP_Morgan/JPMC-tech-task-2-PY3/datafeed$ python3 server3.py

Traceback (most recent call last):
File "server3.py", line 320, in
run(App())
File "server3.py", line 244, in init
self._sim_start, _, _ = next(self._data_1)
StopIteration

I have the folloeing versions
node -v -- V11.0.0
npm -v -- 6.4.1
python3 --version -- 3.7.5

I am using Ubuntu 19.10

**Comment by aaavinash85** [comment]
I found the solution in someone else Question ..
Thanks, I am closing the issue

**Comment by Swarag-N** [comment]
#179  for people who are confused with this issue
