### ISSUE TITLE
NetworkError: Failed to execute 'send' on 'XMLHttpRequest': Failed to load 'http://localhost:8080/query?id=1'.

### ISSUE THREAD

**Issue by hussainyasir23** [insidesherpa/JPMC-tech-task-2-PY3#205]
**NetworkError: Failed to execute 'send' on 'XMLHttpRequest': Failed to load 'http://localhost:8080/query?id=1'.**
Function.getData
D:/JPMC-tech-task-2/src/DataStreamer.ts:36
  33 |       }
  34 |     }
  35 | 
> 36 |     request.send();
  37 |   }
  38 | }
  39 | 
View compiled
App.getDataFromServer
D:/JPMC-tech-task-2/src/App.tsx:39
  36 |  * Get new data from server and update the state with the new data
  37 |  */
  38 | getDataFromServer() {
> 39 |   DataStreamer.getData((serverResponds: ServerRespond[]) => {
     | ^  40 |     // Update the state by creating a new array of data that consists of
  41 |     // Previous data in the state and the new data from server
  42 |     this.setState({ data: [...this.state.data, ...serverResponds] });
View compiled
onClick
D:/JPMC-tech-task-2/src/App.tsx:62
  59 |   // As part of your task, update the getDataFromServer() function
  60 |   // to keep requesting the data every 100ms until the app is closed
  61 |   // or the server does not return anymore data.
> 62 |   onClick={() => {this.getDataFromServer()}}>
     | ^  63 |   Start Streaming Data
  64 | </button>
  65 | <div className="Graph">
View compiled
▶ 22 stack frames were collapsed.

**Comment by hussainyasir23** [comment]
Changing Port to 8085 resolved

- Using any text editor, open the datafeed/server.py in the repository using your code editor and look for the line where it says port = 8080. change that to port = 8085
- Similarly, open the src/DataStreamer.ts and change the line where it has 8080 to 8085

**Comment by Narayamini** [comment]
> Changing Port to 8085 resolved
> 
> * Using any text editor, open the datafeed/server.py in the repository using your code editor and look for the line where it says port = 8080. change that to port = 8085
> * Similarly, open the src/DataStreamer.ts and change the line where it has 8080 to 8085

 

Can you please help in opening src/DataStreamer.ts file,it is a video file right?

**Comment by hussainyasir23** [comment]
Hey @Narayamini , It is not a video file. Just right click on the file and choose "Open With" and then "Notepad"(or any text editor).

**Comment by Narayamini** [comment]
> Hey @Narayamini , It is not a video file. Just right click on the file and choose "Open With" and then "Notepad"(or any text editor).

Thank you very much ,previously it only viewed the options of media player ,I didnt explore the option of notepad!!

**Comment by souromisen** [comment]
> Changing Port to 8085 resolved
> 
> * Using any text editor, open the datafeed/server.py in the repository using your code editor and look for the line where it says port = 8080. change that to port = 8085
> * Similarly, open the src/DataStreamer.ts and change the line where it has 8080 to 8085

hi! i did this and the page is unresponsive. any suggestions?

**Comment by ashk3301** [comment]
> Changing Port to 8085 resolved
> 
> * Using any text editor, open the datafeed/server.py in the repository using your code editor and look for the line where it says port = 8080. change that to port = 8085
> * Similarly, open the src/DataStreamer.ts and change the line where it has 8080 to 8085

Thank you so much. This is the fix if anyone is doing this task in 2023.
