### ISSUE TITLE
Cannot find module '@jpmorganchase/perspective'

### ISSUE THREAD

**Issue by Khaliqfaiz** [insidesherpa/JPMC-tech-task-2-PY3#214]
I have run the command 'npm start' in my terminal. As soon as my browser opens up at port number 3000, I am getting the above mentioned error.
Please try to help me out if anyone is wishing to help.
Thanks in advance!

There is a screenshot of the error in the below link.
https://drive.google.com/file/d/1jmNN0mKFZfFEGXzraIEfZ4vemF2eHnFG/view

**Comment by roshniverma21** [comment]
try the following steps they solved my issue hope will help you too:-
_npm install 
Execute npm install --ignore-scripts
npm audit fix
npm start_

**Comment by Khaliqfaiz** [comment]
Thanks Roshni Verma!
I got rid of that error and I am able to see the web page successfully by
following your instructions :)

**Comment by Cyberkid2311** [comment]
I also have the same problem please help me out

**Comment by Khaliqfaiz** [comment]
Just run the below commands after running the server(seperately):
*npm install*


*Execute npm install --ignore-scriptsnpm audit fixnpm start*

*Hope this works for you*

**Comment by TubaAli** [comment]
Thank you Roshini. I was facing a similar problem. It worked now with the following commands:
$ npm install
$ npm install --ignore-scripts
$ npm audit fix
$ npm start

**Comment by roshniverma21** [comment]
https://github.com/insidesherpa/JPMC-tech-task-2-PY3/issues/217#issuecomment-629135268
your welcome !!
Don't forget to close issue when the problem is resolved.
