### ISSUE TITLE
Compile Error !!

### ISSUE THREAD

**Issue by roshniverma21** [insidesherpa/JPMC-tech-task-2-PY3#217]
Failed to compile
C:/Users/hp/JPMC-tech-task-3-PY3/src/Graph.tsx
TypeScript error in C:/Users/hp/JPMC-tech-task-3-PY3/src/Graph.tsx(2,23):
Cannot find module '@jpmorganchase/perspective' or its corresponding type declarations.  TS2307

    1 | import React, { Component } from 'react';
  > 2 | import { Table } from '@jpmorganchase/perspective';
      |                       ^
    3 | import { ServerRespond } from './DataStreamer';
    4 | import { DataManipulator } from './DataManipulator';
    5 | import './Graph.css';

**Comment by keyur1625** [comment]
npm i @jpmorganchase/perspective
try this

**Comment by roshniverma21** [comment]
Solved : 
Deleted python-task2 folder 
Git clone python-task2 folder
Cd path-name
npm install
Execute npm install --ignore-scripts
npm audit fix
npm start

**Comment by its-me-Zavion** [comment]
ty ty

**Comment by aruvasrikesh0702** [comment]
> Solved :
> Deleted python-task2 folder
> Git clone python-task2 folder
> Cd path-name
> npm install
> Execute npm install --ignore-scripts
> npm audit fix
> npm start

**Comment by aruvasrikesh0702** [comment]
> Solved :
> Deleted python-task2 folder
> Git clone python-task2 folder
> Cd path-name
> npm install
> Execute npm install --ignore-scripts
> npm audit fix
> npm start

do we need to install npm again
