### ISSUE TITLE
npm start issue

### ISSUE THREAD

**Issue by jamaltariqcheema** [insidesherpa/JPMC-tech-task-2-PY3#218]
Tried everything that I could find but still showing this error even tried `npm audit fix`

<img width="746" alt="Screenshot 2020-05-15 at 8 03 04 AM" src="https://user-images.githubusercontent.com/37561305/82024141-bf841d00-96a8-11ea-918d-79402c9da9a7.png">

**Comment by roshniverma21** [comment]
try the following steps they solved my issue hope will help you too:-
npm install
Execute npm install --ignore-scripts
npm audit fix
npm start

**Comment by EliaTorre** [comment]
It still gives the same error @roshniverma21

**Comment by roshniverma21** [comment]
Restart it from the git clone step after deleting python-task 2 folder

**Comment by EliaTorre** [comment]
Already tried, any other suggestion?

**Comment by EliaTorre** [comment]
Solved: 

- Delete python-task 2 folder
- git clone python-task 2 folder
- start the server on a kernel
- on another kernel enter the folder  python-task 2 folder
- substitute the node_modules with the ones given by JPMorgan
- run "unset HOST"
- run npm start

**Comment by jamaltariqcheema** [comment]
Worked for me too. Thanks
