### ISSUE TITLE
Unable to run Server

### ISSUE THREAD

**Issue by enexspecial** [insidesherpa/JPMC-tech-task-2-PY3#22]
I keep getting this error whenever i try to run the server3.py
Traceback (most recent call last):
  File "C:/Users/user/Documents/jpMorganChase/JPMC-tech-task-2-PY3/datafeed/server3.py", line 320, in <module>
    run(App())
  File "C:/Users/user/Documents/jpMorganChase/JPMC-tech-task-2-PY3/datafeed/server3.py", line 244, in __init__
    self._sim_start, _, _ = next(self._data_1)
StopIteration

Please how do i solve this ?

**Comment by jbf-insidesherpa** [comment]
@enexspecial are you trying to run this within the datafeed/ folder? i.e. is your command line's current working directory context inside `JPMC-tech-task-2-PY3/datafeed/` and you're just executing the command, `python server3.py` ? if so, can you try going out of the datafeed folder via `cd ..`, thus making your command line's current working directory context just `JPMC-tech-task2-PY3` and then running `python datafeed/server3.py` 

Let me know how it goes

**Comment by jbf-insidesherpa** [comment]
Closing this ticket as it's been quite some time already. @enexspecial feel free to open if it's still relevant

**Comment by c0deek** [comment]
@jbf-insidesherpa I was facing the same problem. Starting the server from the main folder helped but can you please explain the reason for this error.

**Comment by ssanjanapai** [comment]
After typing 'python3 datafeed/server3.py ' in the prompt ,I dont get any error or response message.

**Comment by rajatmenon** [comment]
> After typing 'python3 datafeed/server3.py ' in the prompt ,I dont get any error or response message.

same for me ..it does not do anything after running the cmd 'python3 datafeed/server3.py'

**Comment by ManishSongara** [comment]
![image](https://user-images.githubusercontent.com/31859160/82154352-dbdfaf80-988a-11ea-81e9-21f94d3e5d0a.png)

it do  not showing any error . but also it do not perform any task

**Comment by Adityakanyal** [comment]
you should install pip and run this command pip install python-dateutil

**Comment by harshdubey16** [comment]
> you should install pip and run this command 'pip install python-dateutil'

if you're using python3 then 'pip3 install python-dateutil'
Well I did the above but still after running 'python3 datafeed/server3' nothing appears! What do I do now?
...........................................................................................................................................................................................................
C:\Users\harsh\JPMC-tech-task-2-PY3>pip3 install python-dateutil
Collecting python-dateutil
  Downloading https://files.pythonhosted.org/packages/d4/70/d60450c3dd48ef87586924207ae8907090de0b306af2bce5d134d78615cb/python_dateutil-2.8.1-py2.py3-none-any.whl (227kB)
     |████████████████████████████████| 235kB 930kB/s
Collecting six>=1.5 (from python-dateutil)
  Downloading https://files.pythonhosted.org/packages/ee/ff/48bde5c0f013094d729fe4b0316ba2a24774b3ff1c52d924a8a4cb04078a/six-1.15.0-py2.py3-none-any.whl
Installing collected packages: six, python-dateutil
Successfully installed python-dateutil-2.8.1 six-1.15.0
WARNING: You are using pip version 19.2.3, however version 20.1.1 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.

C:\Users\harsh\JPMC-tech-task-2-PY3>python -m pip install --upgrade pip
Collecting pip
  Downloading https://files.pythonhosted.org/packages/43/84/23ed6a1796480a6f1a2d38f2802901d078266bda38388954d01d3f2e821d/pip-20.1.1-py2.py3-none-any.whl (1.5MB)
     |████████████████████████████████| 1.5MB 3.3MB/s
Installing collected packages: pip
  Found existing installation: pip 19.2.3
    Uninstalling pip-19.2.3:
      Successfully uninstalled pip-19.2.3
Successfully installed pip-20.1.1

C:\Users\harsh\JPMC-tech-task-2-PY3>python datafeed/server3.py

**Comment by Shreyas1042** [comment]
The same problem. After executing 'python3 datafeed/server3' nothing appears to be happening.

**Comment by harshdubey16** [comment]
> The same problem. After executing 'python3 datafeed/server3' nothing appears to be happening.

what you can do is just execute the server3.py file of jpm_module_1 folder instead of executing this one as both the files are same, and later on just run the npm start command on command prompt 
It did worked for me, so let me know if this works for you??

**Comment by ManishSongara** [comment]
![image](https://user-images.githubusercontent.com/31859160/82843356-90687980-9efa-11ea-8b31-7fe9e917f417.png)
i had solve my problem by following thses steps

**Comment by ujjwaljainnn** [comment]
I am facing a problem in the same part. I am getting no output after "python datafeed/server3.py" command. I believe there's an issue because the slides showed some output after this. I should already have pip installed in my pc since I'm using python3 from a month now. But I get an error message when trying to check pip version on cmd. Hope someone can help
![issue](https://user-images.githubusercontent.com/64335584/82893576-d7905200-9f6e-11ea-8b1d-0a300c405fed.png)

**Comment by ManishSongara** [comment]
> I am facing a problem in the same part. I am getting no output after "python datafeed/server3.py" command. I believe there's an issue because the slides showed some output after this. I should already have pip installed in my pc since I'm using python3 from a month now. But I get an error message when trying to check pip version on cmd. Hope someone can help
> EDIT: I'm getting the same output(no output) for both "python datafeed/server3.py" and "python datafeed/server.py"
> ![image](https://user-images.githubusercontent.com/64335584/82894735-aca6fd80-9f70-11ea-96df-088abccc6073.png)
i have face same problem then i used python at place of python3 and it's work 
use----> python datafeed/server.py

**Comment by ManishSongara** [comment]
have install python-dateutil

**Comment by Daksh04** [comment]
> have you install python-dateutil?

I have installed python-dateutil but I haven't got any output...

**Comment by SufyanParkar** [comment]
do `python datafeed/server3.py`

and not `python server3.py`

**DO NOT GO INSIDE THE DATAFEED DIRECTORY**

yes PLEASE do not go in that directory 

just do 

`python datafeed/server3.py`

**Comment by i-am-manish** [comment]
> do `python datafeed/server3.py`
> 
> and not `python server3.py`
> 
> **DO NOT GO INSIDE THE DATAFEED DIRECTORY**
> 
> yes PLEASE do not go in that directory
> 
> just do
> 
> `python datafeed/server3.py

U solved my error bruh. I was stuck on it past a week. Thanks:)

**Comment by mupotsal** [comment]
Thanks

**Comment by P3NGUIN12** [comment]
> python datafeed/server3.py

Perfect solution , error solved!

**Comment by mehernv** [comment]
i m also getting no output and no response after python datafeed/server3.py
![piperror](https://user-images.githubusercontent.com/62346828/87521276-c972ce00-c6a1-11ea-9536-3f55a5f999cc.jpg)

**Comment by gamedevat92** [comment]
As i type pip install python-dateutil, it says requirement already fulfilled in anaconda scripts
However it is still not returning any output after using python datafeed/server3.py

**Comment by i-am-manish** [comment]
> As i type pip install python-dateutil, it says requirement already fulfilled in anaconda scripts
> However it is still not returning any output after using python datafeed/server3.py

try using python3 datafeed/server3.py

**Comment by i-am-manish** [comment]
> i m also getting no output and no response after python datafeed/server3.py
> ![piperror](https://user-images.githubusercontent.com/62346828/87521276-c972ce00-c6a1-11ea-9536-3f55a5f999cc.jpg)

Use python3 datafeed/server3.py

**Comment by Avanish07** [comment]
> do `python datafeed/server3.py`
> 
> and not `python server3.py`
> 
> **DO NOT GO INSIDE THE DATAFEED DIRECTORY**
> 
> yes PLEASE do not go in that directory
> 
> just do
> 
> `python datafeed/server3.py`

Thanks it worked.....
