### ISSUE TITLE
python: can't open file 'datafeed/server.py': [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by MaitriGurey** [insidesherpa/JPMC-tech-task-2-PY3#225]
![ss1](https://user-images.githubusercontent.com/56483420/82107876-80a5a400-9748-11ea-9b3a-03b909de192f.png)
  
how to solve this issue?

**Comment by Shirley817950** [comment]
You can try to type python3 datafeed/server.py

**Comment by divyanshu450** [comment]
Or just use “py file_name.py” .

**Comment by ShreyaR14** [comment]
I'm also facing the same issue. Please help with how to resolve this issue?

**Comment by tharsh95** [comment]
If you are using Python version 3 then run 'python datafeed/server3.py
'

**Comment by ghost** [comment]
Use python datafeed/server3.py or instead use
cd datafeed
python server3.py
