### ISSUE TITLE
Preexisting Visual Studio 2019 installation causes conflicts with environment setup

### ISSUE THREAD

**Issue by Tanner-Tran** [insidesherpa/JPMC-tech-task-2-PY3#23]
Hello,

It turns out that my preexisting install of Visual Studio 2019 was giving me issues when attempting 'npm install'. To be specific, I was getting:

"gyp ERR! stack Error: spawn C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\15.0\Bin\MSBuild.exe ENOENT"

I was able to solve the issue by following user joaocgreis' advice found here:
https://github.com/nodejs/node-gyp/issues/1747

For whatever reason, 'npm config set msvs_version 2017' was not solving the issue.

I just wanted to bring this to your attention.

Thanks!

**Comment by jbf-insidesherpa** [comment]
Thanks for the notice @Tanner-Tran. We'll use your comment here as reference for others who might experience the issue.

**Comment by Jakejaga5** [comment]
Guys i have was facing this issue for an entire day at my work, just now solved by just copy pasting the MSBuild.exe file in **C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\MSBuild\Current\Bin** to **C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\MSBuild\15.0\Bin.**

I tried all the suggested methods in this thread none worked. If anyone happened to face this issue straight away use **npm install --global --production windows-build-tools --vs2019 or --vs2017** .
and copy paste the exe file.
