### ISSUE TITLE
compile error mac

### ISSUE THREAD

**Issue by 12ayush12** [insidesherpa/JPMC-tech-task-2-PY3#234]
<img width="499" alt="Screenshot 2020-05-17 at 12 10 50 AM" src="https://user-images.githubusercontent.com/49794477/82127657-f0f90780-97d2-11ea-90a6-99e8e4adc9b9.png">

**Comment by smerapala** [comment]
I'm having the same issue. Any suggestions on how to fix it?

**Comment by 12ayush12** [comment]
In the graph.tsx file there is a header import table, in there change it to
( import { Table } from '@finos/perspective'; )
and in the terminal go to the jp task directory and download finos perspective file there i.e., run the command on the terminal while in the task directory, the instructions to download finos perspective are available on the net.really really sorry for the late reply
