### ISSUE TITLE
Cannot find module '@jpmorganchase/prespective'

### ISSUE THREAD

**Issue by shivamadlakha** [insidesherpa/JPMC-tech-task-2-PY3#235]
Task 2
Problem while launching localhost:3000
npm start

![jp problem](https://user-images.githubusercontent.com/47023454/82137752-6945e400-9838-11ea-99a5-efa48da9c4b6.PNG)

**Comment by roshniverma21** [comment]
https://github.com/insidesherpa/JPMC-tech-task-2-PY3/issues/217#issuecomment-629135268

**Comment by bhavinf** [comment]
https://drive.google.com/file/d/1amF7C-4mRZCi3Ab5xuH0XCRQubp4aa_t/view

Download this zip file and replace the node_modules folder in JPMC-tech-task-2-PY3 with this, and after that run "npm install" and "npm start" commands again

**Comment by sri-samurai28** [comment]
> https://drive.google.com/file/d/1amF7C-4mRZCi3Ab5xuH0XCRQubp4aa_t/view
> 
> Download this zip file and replace the node_modules folder in JPMC-tech-task-2-PY3 with this, and after that run "npm install" and "npm start" commands again

it didn't help
