### ISSUE TITLE
npm ERR! Cannot read property 'resolve' of undefined  npm ERR! A complete log of this run can be found in:

### ISSUE THREAD

**Issue by Narayamini** [insidesherpa/JPMC-tech-task-2-PY3#236]
Can anyone please help me with this issue

when I am using npm start ,the following is being displayed
bank-merge-co-task-2@0.1.0 start C:\Users\Narayamini\JPMC-tech-task-2-PY3
> react-scripts start

'react-scripts' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! bank-merge-co-task-2@0.1.0 start: `react-scripts start`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bank-merge-co-task-2@0.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:

**Comment by bhavinf** [comment]
I hope you are running your command prompt as an administrator. If yes, try closing the cmd and open it again. After this run the command "npm install" again and then run "npm start". Restarting the command prompt made a difference for me (I don't know how, but it did)

**Comment by Narayamini** [comment]
> I hope you are running your command prompt as an administrator. If yes, try closing the cmd and open it again. After this run the command "npm install" again and then run "npm start". Restarting the command prompt made a difference for me (I don't know how, but it did)

Yeah!!Thank you it helped me too!!

**Comment by bhavinf** [comment]
That's great! I'm glad I could help
