### ISSUE TITLE
jp morgan virtual internship

### ISSUE THREAD

**Issue by gupabhi100** [insidesherpa/JPMC-tech-task-2-PY3#237]
![Screenshot (56)](https://user-images.githubusercontent.com/59078878/82142312-20ebed80-985b-11ea-9884-8aa8e0f1edc6.png)
I am not getting the yellow line graph ? @insidesherpa  @jbf-insidesherpa  could you please resolve my issue asap?
I am waiting for ur reply

**Comment by ShivaneePanchal** [comment]
Hey did you get it resolved? I am facing the same issue...

**Comment by gupabhi100** [comment]
Hey hi ,
I just forgot the issue ,
Would u please remind me so that I can help u?

**Comment by gupabhi100** [comment]
I uploaded the file with same graph

**Comment by ShivaneePanchal** [comment]
okay thanks :)
