### ISSUE TITLE
Npm install error

### ISSUE THREAD

**Issue by chaitanya642000** [insidesherpa/JPMC-tech-task-2-PY3#241]
I got error while installing npm
here is the screenshot
![npminstallerror](https://user-images.githubusercontent.com/48641297/82148410-a084b700-9871-11ea-8276-b5af923a4706.png)

**Comment by vidhya-raman** [comment]
Hey, I got the similar error. Try `npm install -g node-gyp`

**Comment by chaitanya642000** [comment]
Hey thanks for your help but I got another error
Here is the screenshot
![error2](https://user-images.githubusercontent.com/48641297/82151537-8bac2180-9879-11ea-9b59-389c63178bd8.png)

**Comment by chaitanya642000** [comment]
I solved the problem , anyone facing similar problem just check https://github.com/insidesherpa/JPMC-tech-task-2-PY3/issues/214
