### ISSUE TITLE
server do not run

### ISSUE THREAD

**Issue by ManishSongara** [insidesherpa/JPMC-tech-task-2-PY3#242]
![image](https://user-images.githubusercontent.com/31859160/82154440-8eb00d80-988b-11ea-8f9a-2c6b85021d83.png)

i do not showing any error but also it do not  perform any task as well!

**Comment by imNKnavin** [comment]
same issue I have, can anyone solve this?

**Comment by bhavinf** [comment]
This is because you are using Forward Slash to get into datafeed directory which is wrong. Since you are using Windows, you must use backslash to get into that directory. So try the command "python datafeed\server3.py" or "python datafeed\server3.py" whichever works for you

**Comment by ManishSongara** [comment]
it didn't work for me!

**Comment by imNKnavin** [comment]
change the port number 8080 to 8085 in both server3.py and DataStreamer.ts, after that run again the command. python datafeed/server3.py

**Comment by bhavinf** [comment]
> it didn't work for me!

I'm sorry if that didn't work. You can try what @imNKnavin is telling you to try. If that doesn't work either, just check if you have python in your path

**Comment by ManishSongara** [comment]
![image](https://user-images.githubusercontent.com/31859160/82221671-f030b480-993d-11ea-99c0-a8e76ab5f7fd.png)

i have found that ----->error import dateutil.parser ModuleNotFoundError: No module named 'dateutil' in windows
so first install dateutil.parser then run
