### ISSUE TITLE
Failed to connect to server

### ISSUE THREAD

**Issue by amel-er** [insidesherpa/JPMC-tech-task-2-PY3#25]
![Screenshot 2019-12-19 at 16 27 32](https://user-images.githubusercontent.com/59019018/71185826-77d5a280-227c-11ea-9bf1-54e7c70452e8.png)
This is what I get when I run npm start....

**Comment by amel-er** [comment]
FYI. I have already tried the steps indicated in the troubleshooting guide i.e. changed the port to port = 8085 in both of the doc. In addition, my firewall is off.

**Comment by jbf-insidesherpa** [comment]
@amel-er did you encounter any errors when doing **npm install** ? Also what is your python version? What's your npm and node version too?

**Comment by vpascaln** [comment]
My server will not start. I tried all the troubleshooting suggesting but nothing is working.
![image](https://user-images.githubusercontent.com/35489699/71334077-8c2ecf00-250a-11ea-8516-cbd0af1fe4fd.png)

**Comment by jbf-insidesherpa** [comment]
@vpascaln go outside of the datafeed folder by doing **cd ..** then execute the server script from there : **python3 datafeed/server3.py**

**Comment by vpascaln** [comment]
Thank you!

**Comment by amel-er** [comment]
I had to install npm 6.4.1 and now its all working! 
Thank you for your help!
