### ISSUE TITLE
npm install_error

### ISSUE THREAD

**Issue by MohammadHirani** [insidesherpa/JPMC-tech-task-2-PY3#252]
**I am getting all these errors while executing npm install , can anyone help me ??**

npm WARN tarball tarball data for ajv@5.5.2 (sha1-c7Xuyj+rZT49P5Qis0GtQiBdyWU=) seems to be corrupted. Trying one more time.
npm WARN tarball tarball data for dotenv@6.0.0 (sha512-FlWbnhgjtwD+uNLUGHbMykMOYQaTivdHEmYwAKFjn6GKe/CqY0fNae93ZHTd20snh9ZLr8mTzIL9m0APQ1pjQg==) seems to be corrupted. Trying one more time.
npm WARN tarball tarball data for core-js@2.6.3 (sha512-l00tmFFZOBHtYhN4Cz7k32VM7vTn3rE2ANjQDxdEN6zmXZ/xq1jQuutnmHvMG1ZJ7xd72+TA5YpUK8wz3rWsfQ==) seems to be corrupted. Trying one more time.
npm WARN tarball tarball data for typescript@3.2.4 (sha512-0RNDbSdEokBeEAkgNbxJ+BLwSManFy9TeXz8uW+48j/xhEXv1ePME60olyzw2XzUqUBNAYFeJadIqAgNqIACwg==) seems to be corrupted. Trying one more time.
npm WARN tarball tarball data for chroma-js@1.4.1 (sha512-jTwQiT859RTFN/vIf7s+Vl/Z2LcMrvMv3WUFmd/4u76AdlFC0NTNgqEEFPcRiHmAswPsMiQEDZLM8vX8qXpZNQ==) seems to be corrupted. Trying one more time.
npm WARN tarball tarball data for fsevents@1.2.4 (sha512-z8H8/diyk76B7q5wg+Ud0+CqzcAF3mBBI/bA5ne5zrRUUIvNkJY//D3BqyH571KuAC4Nr7Rw7CjWX4r0y9DvNg==) seems to be corrupted. Trying one more time.
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\lapshop.in\JPMC-tech-task-2-PY3\node_modules\.staging\circular-json-dbcd28a1\build\circular-json.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\lapshop.in\JPMC-tech-task-2-PY3\node_modules\.staging\circular-json-dbcd28a1\build\circular-json.max.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\lapshop.in\JPMC-tech-task-2-PY3\node_modules\.staging\chroma-js-c0d52067\docs\assets\bg.png'
npm WARN tar ENOENT: no such file or directory, lstat 'C:\Users\lapshop.in\JPMC-tech-task-2-PY3\node_modules\.staging\chroma-js-c0d52067\docs'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\lapshop.in\JPMC-tech-task-2-PY3\node_modules\.staging\chroma-js-c0d52067\docs\index.html'
npm WARN tar ENOENT: no such file or directory, lstat 'C:\Users\lapshop.in\JPMC-tech-task-2-PY3\node_modules\.staging\fsevents-621a2617\node_modules\iconv-lite\encodings'
npm WARN tar ENOENT: no such file or directory, lstat 'C:\Users\lapshop.in\JPMC-tech-task-2-PY3\node_modules\.staging\fsevents-621a2617\node_modules'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\lapshop.in\JPMC-tech-task-2-PY3\node_modules\.staging\deep-equal-01f2b78f\test\cmp.js'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\fsevents):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: Cannot cd into 'C:\Users\lapshop.in\JPMC-tech-task-2-PY3\node_modules\.staging\fsevents-621a2617'

npm ERR! Maximum call stack size exceeded
npm WARN tarball tarball data for highcharts@6.1.0 (sha512-YZotALyZD1xJixB8pNOKqBpmxV/NrOpMHQ3l7/CMB1hn5U7KRSviaeyv8/1MT7/rTgEFPOW85mdaFKFr2EfeAw==) seems to be corrupted. Trying one more time.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\lapshop.in\AppData\Roaming\npm-cache\_logs\2020-05-19T15_05_03_791Z-debug.log

**Comment by sachinfab** [comment]
- Download [**node_modules**](https://drive.google.com/file/d/1ML6nECK18J0jM3hhfJdSCRtCNLssruYQ/view)
- Replace The  **node_modules** Inside Your Repo With The Downloaded File
- Directly Execute **npm start**
