### ISSUE TITLE
Patch file size exceeds 250 MB

### ISSUE THREAD

**Issue by ankitkashyap12** [insidesherpa/JPMC-tech-task-2-PY3#256]
while submitting patch file it shows that patch file size exceeds 250 MB(it is of around 350 MB),
Any help will be appreciated.
Should I remove the node modules file?

**Comment by ShivaniGupta1604** [comment]
> while submitting patch file it shows that patch file size exceeds 250 MB(it is of around 350 MB),
> Any help will be appreciated.
> Should I remove the node modules file?

Can you please help me with how to make patch file?
![Screenshot (140)](https://user-images.githubusercontent.com/56301436/82531497-25ffb400-9b5d-11ea-8c32-826a202ae1b9.png)
I'am facing this error.

**Comment by ankitkashyap12** [comment]
Replace single quites in 'Create Patch File' with double quotes.
Like this
git commit -m "Create Patch File"

**Comment by khanh4** [comment]
hi @ankitkashyap12 can you please help me out too
![IMG_0788 (1)](https://user-images.githubusercontent.com/65410306/82575777-e7ff9180-9b56-11ea-90fc-ba332b6b4a0f.jpg)

**Comment by khanh4** [comment]
i am getting this error can you please help.

**Comment by ankitkashyap12** [comment]
That's not error I guess.Go ahead and create your patch file.
