### ISSUE TITLE
Error in npm install and npm start

### ISSUE THREAD

**Issue by Naman-1234** [insidesherpa/JPMC-tech-task-2-PY3#257]
// My operating system is windows 10
// Please resolve it as soon as possible otherwise i will  remain stuck at this.
I have downloaded the Node js installer then after that what happened is below:
It shows the version as
6.14.4

But When Type npm install

npm WARN saveError ENOENT: no such file or directory, open 'C:\Windows\system32\package.json'
npm WARN enoent ENOENT: no such file or directory, open 'C:\Windows\system32\package.json'
npm WARN system32 No description
npm WARN system32 No repository field.
npm WARN system32 No README data
npm WARN system32 No license field.

and when I type npm start

npm ERR! code ENOENT
npm ERR! syscall open
npm ERR! path C:\Windows\system32\package.json
npm ERR! errno -4058
npm ERR! enoent ENOENT: no such file or directory, open 'C:\Windows\system32\package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Naman\AppData\Roaming\npm-cache\_logs\2020-05-20T10_47_40_839Z-debug.log

**Comment by IkyaVenus** [comment]
You have to run that npm install command in "C:\\Users\****\JPMC-tech-task-2-PY3-master" folder. Move to this directory first and run.

**Comment by Naman-1234** [comment]
Thankyou  IkyaVenus it worked out but i have  stuck in another problem ,please also solve this,
This says about c++ build tools but i have installed them already  and checked it using command prompt

When i run npm install
it says

C:\Windows\system32>cd C:\Users\Naman\JPMC-tech-task-2

C:\Users\Naman\JPMC-tech-task-2>npm install

> bufferutil@3.0.5 install C:\Users\Naman\JPMC-tech-task-2\node_modules\bufferutil
> prebuild-install || node-gyp rebuild

prebuild-install WARN install No prebuilt binaries found (target=12.16.3 runtime=node arch=x64 platform=win32)

C:\Users\Naman\JPMC-tech-task-2\node_modules\bufferutil>if not defined npm_config_node_gyp (node "C:\Users\Naman\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\Naman\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "-m" switch.
  bufferutil.cc
  win_delay_load_hook.cc
C:\Users\Naman\JPMC-tech-task-2\node_modules\bufferutil\node_modules\nan\nan_converters_43_inl.h(22,1): warning C4996:
'v8::Value::ToBoolean': was declared deprecated (compiling source file ..\src\bufferutil.cc) [C:\Users\Naman\JPMC-tech-
task-2\node_modules\bufferutil\build\bufferutil.vcxproj]
C:\Users\Naman\JPMC-tech-task-2\node_modules\bufferutil\node_modules\nan\nan_converters_43_inl.h(40,1): warning C4996:
'v8::Value::BooleanValue': was declared deprecated (compiling source file ..\src\bufferutil.cc) [C:\Users\Naman\JPMC-te
ch-task-2\node_modules\bufferutil\build\bufferutil.vcxproj]
C:\Users\Naman\JPMC-tech-task-2\node_modules\bufferutil\node_modules\nan\nan_implementation_12_inl.h(103,37): error C26
64: 'v8::MaybeLocal<v8::Function> v8::Function::New(v8::Local<v8::Context>,v8::FunctionCallback,v8::Local<v8::Value>,in
t,v8::ConstructorBehavior,v8::SideEffectType)': cannot convert argument 1 from 'v8::Isolate *' to 'v8::Local<v8::Contex
t>' (compiling source file ..\src\bufferutil.cc) [C:\Users\Naman\JPMC-tech-task-2\node_modules\bufferutil\build\bufferu
til.vcxproj]
C:\Users\Naman\JPMC-tech-task-2\node_modules\bufferutil\node_modules\nan\nan_implementation_12_inl.h(105,32): message :
 No constructor could take the source type, or constructor overload resolution was ambiguous (compiling source file ..\
src\bufferutil.cc) [C:\Users\Naman\JPMC-tech-task-2\node_modules\bufferutil\build\bufferutil.vcxproj]
C:\Users\Naman\AppData\Local\node-gyp\Cache\12.16.3\include\node\v8.h(4275,31): message : see declaration of 'v8::Funct
ion::New' (compiling source file ..\src\bufferutil.cc) [C:\Users\Naman\JPMC-tech-task-2\node_modules\bufferutil\build\b
ufferutil.vcxproj]
C:\Users\Naman\JPMC-tech-task-2\node_modules\bufferutil\node_modules\nan\nan_implementation_12_inl.h(337,37): error C26
60: 'v8::StringObject::New': function does not take 1 arguments (compiling source file ..\src\bufferutil.cc) [C:\Users\
Naman\JPMC-tech-task-2\node_modules\bufferutil\build\bufferutil.vcxproj]
C:\Users\Naman\AppData\Local\node-gyp\Cache\12.16.3\include\node\v8.h(5531,23): message : see declaration of 'v8::Strin
gObject::New' (compiling source file ..\src\bufferutil.cc) [C:\Users\Naman\JPMC-tech-task-2\node_modules\bufferutil\bui
ld\bufferutil.vcxproj]
C:\Users\Naman\JPMC-tech-task-2\node_modules\bufferutil\node_modules\nan\nan_implementation_12_inl.h(337,60): error C20
59: syntax error: ')' (compiling source file ..\src\bufferutil.cc) [C:\Users\Naman\JPMC-tech-task-2\node_modules\buffer
util\build\bufferutil.vcxproj]
C:\Users\Naman\JPMC-tech-task-2\node_modules\bufferutil\node_modules\nan\nan.h(1034,1): error C2661: 'v8::Value::ToStri
ng': no overloaded function takes 0 arguments (compiling source file ..\src\bufferutil.cc) [C:\Users\Naman\JPMC-tech-ta
sk-2\node_modules\bufferutil\build\bufferutil.vcxproj]
C:\Users\Naman\JPMC-tech-task-2\node_modules\bufferutil\node_modules\nan\nan.h(1044,1): error C2664: 'int v8::String::W
riteUtf8(v8::Isolate *,char *,int,int *,int) const': cannot convert argument 1 from 'char *' to 'v8::Isolate *' (compil
ing source file ..\src\bufferutil.cc) [C:\Users\Naman\JPMC-tech-task-2\node_modules\bufferutil\build\bufferutil.vcxproj
]
C:\Users\Naman\JPMC-tech-task-2\node_modules\bufferutil\node_modules\nan\nan.h(1044,37): message : Types pointed to are
 unrelated; conversion requires reinterpret_cast, C-style cast or function-style cast (compiling source file ..\src\buf
ferutil.cc) [C:\Users\Naman\JPMC-tech-task-2\node_modules\bufferutil\build\bufferutil.vcxproj]
C:\Users\Naman\AppData\Local\node-gyp\Cache\12.16.3\include\node\v8.h(2878,7): message : see declaration of 'v8::String
::WriteUtf8' (compiling source file ..\src\bufferutil.cc) [C:\Users\Naman\JPMC-tech-task-2\node_modules\bufferutil\buil
d\bufferutil.vcxproj]
C:\Users\Naman\JPMC-tech-task-2\node_modules\bufferutil\node_modules\nan\nan.h(1818,26): warning C4996: 'v8::Object::Se
t': was declared deprecated (compiling source file ..\src\bufferutil.cc) [C:\Users\Naman\JPMC-tech-task-2\node_modules\
bufferutil\build\bufferutil.vcxproj]
C:\Users\Naman\JPMC-tech-task-2\node_modules\bufferutil\node_modules\nan\nan.h(1824,26): warning C4996: 'v8::Object::Se
t': was declared deprecated (compiling source file ..\src\bufferutil.cc) [C:\Users\Naman\JPMC-tech-task-2\node_modules\
bufferutil\build\bufferutil.vcxproj]
C:\Users\Naman\JPMC-tech-task-2\node_modules\bufferutil\node_modules\nan\nan.h(1830,26): warning C4996: 'v8::Object::Se
t': was declared deprecated (compiling source file ..\src\bufferutil.cc) [C:\Users\Naman\JPMC-tech-task-2\node_modules\
bufferutil\build\bufferutil.vcxproj]
C:\Users\Naman\JPMC-tech-task-2\node_modules\bufferutil\node_modules\nan\nan.h(1836,30): warning C4996: 'v8::Object::Ge
t': was declared deprecated (compiling source file ..\src\bufferutil.cc) [C:\Users\Naman\JPMC-tech-task-2\node_modules\
bufferutil\build\bufferutil.vcxproj]
C:\Users\Naman\JPMC-tech-task-2\node_modules\bufferutil\node_modules\nan\nan.h(1842,46): warning C4996: 'v8::Object::Ge
t': was declared deprecated (compiling source file ..\src\bufferutil.cc) [C:\Users\Naman\JPMC-tech-task-2\node_modules\
bufferutil\build\bufferutil.vcxproj]
C:\Users\Naman\JPMC-tech-task-2\node_modules\bufferutil\node_modules\nan\nan.h(1847,46): warning C4996: 'v8::Object::Ge
t': was declared deprecated (compiling source file ..\src\bufferutil.cc) [C:\Users\Naman\JPMC-tech-task-2\node_modules\
bufferutil\build\bufferutil.vcxproj]
C:\Users\Naman\JPMC-tech-task-2\node_modules\bufferutil\node_modules\nan\nan_object_wrap.h(24,1): error C2039: 'IsNearD
eath': is not a member of 'Nan::Persistent<v8::Object,v8::NonCopyablePersistentTraits<T>>' [C:\Users\Naman\JPMC-tech-ta
sk-2\node_modules\bufferutil\build\bufferutil.vcxproj]
          with
          [
              T=v8::Object
          ] (compiling source file ..\src\bufferutil.cc)
C:\Users\Naman\JPMC-tech-task-2\node_modules\bufferutil\node_modules\nan\nan.h(1859): message : see declaration of 'Nan
::Persistent<v8::Object,v8::NonCopyablePersistentTraits<T>>' [C:\Users\Naman\JPMC-tech-task-2\node_modules\bufferutil\b
uild\bufferutil.vcxproj]
          with
          [
              T=v8::Object
          ] (compiling source file ..\src\bufferutil.cc)
C:\Users\Naman\JPMC-tech-task-2\node_modules\bufferutil\node_modules\nan\nan_object_wrap.h(67,17): warning C4996: 'v8::
PersistentBase<v8::Object>::MarkIndependent': was declared deprecated (compiling source file ..\src\bufferutil.cc) [C:\
Users\Naman\JPMC-tech-task-2\node_modules\bufferutil\build\bufferutil.vcxproj]
C:\Users\Naman\JPMC-tech-task-2\node_modules\bufferutil\node_modules\nan\nan_object_wrap.h(124,1): error C2039: 'IsNear
Death': is not a member of 'Nan::Persistent<v8::Object,v8::NonCopyablePersistentTraits<T>>' [C:\Users\Naman\JPMC-tech-t
ask-2\node_modules\bufferutil\build\bufferutil.vcxproj]
          with
          [
              T=v8::Object
          ] (compiling source file ..\src\bufferutil.cc)
C:\Users\Naman\JPMC-tech-task-2\node_modules\bufferutil\node_modules\nan\nan.h(1859): message : see declaration of 'Nan
::Persistent<v8::Object,v8::NonCopyablePersistentTraits<T>>' [C:\Users\Naman\JPMC-tech-task-2\node_modules\bufferutil\b
uild\bufferutil.vcxproj]
          with
          [
              T=v8::Object
          ] (compiling source file ..\src\bufferutil.cc)
C:\Users\Naman\JPMC-tech-task-2\node_modules\bufferutil\src\bufferutil.cc(12,64): error C2660: 'v8::Value::Int32Value':
 function does not take 0 arguments [C:\Users\Naman\JPMC-tech-task-2\node_modules\bufferutil\build\bufferutil.vcxproj]
C:\Users\Naman\AppData\Local\node-gyp\Cache\12.16.3\include\node\v8.h(2709,40): message : see declaration of 'v8::Value
::Int32Value' (compiling source file ..\src\bufferutil.cc) [C:\Users\Naman\JPMC-tech-task-2\node_modules\bufferutil\bui
ld\bufferutil.vcxproj]
C:\Users\Naman\JPMC-tech-task-2\node_modules\bufferutil\src\bufferutil.cc(13,39): error C2660: 'v8::Value::Int32Value':
 function does not take 0 arguments [C:\Users\Naman\JPMC-tech-task-2\node_modules\bufferutil\build\bufferutil.vcxproj]
C:\Users\Naman\AppData\Local\node-gyp\Cache\12.16.3\include\node\v8.h(2709,40): message : see declaration of 'v8::Value
::Int32Value' (compiling source file ..\src\bufferutil.cc) [C:\Users\Naman\JPMC-tech-task-2\node_modules\bufferutil\bui
ld\bufferutil.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Current\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\Naman\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:310:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Windows_NT 10.0.17763
gyp ERR! command "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Users\\Naman\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\Naman\JPMC-tech-task-2\node_modules\bufferutil
gyp ERR! node -v v12.16.3
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
npm WARN rollback Rolling back readable-stream@2.3.6 failed (this is probably harmless): EPERM: operation not permitted, scandir 'C:\Users\Naman\JPMC-tech-task-2\node_modules\fsevents\node_modules'
npm WARN rollback Rolling back node-pre-gyp@0.10.0 failed (this is probably harmless): EPERM: operation not permitted, lstat 'C:\Users\Naman\JPMC-tech-task-2\node_modules\fsevents\node_modules'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! bufferutil@3.0.5 install: `prebuild-install || node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bufferutil@3.0.5 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Naman\AppData\Roaming\npm-cache\_logs\2020-05-22T07_48_51_121Z-debug.log

**Comment by KratikaArora** [comment]
I am having the exactly same error. Have you resolved it??

**Comment by IkyaVenus** [comment]
You might be using python version 3.8.x something. npm can be installed only through Python 2.7.x versions. So try installing py version 2.7.x and change path environment to 2.7.x temporarily. after installing npm you can switch back to your original python version.

**Comment by Naman-1234** [comment]
Still got no lead,it did not help,it shows the error given below.Please help

C:\Windows\system32>python --version
Python 2.7.11

C:\Windows\system32>cd C:\Users\Naman\JPMC-tech-task-2-PY3

C:\Users\Naman\JPMC-tech-task-2-PY3>npm install

> bufferutil@3.0.5 install C:\Users\Naman\JPMC-tech-task-2-PY3\node_modules\bufferutil
> prebuild-install || node-gyp rebuild

prebuild-install WARN install No prebuilt binaries found (target=12.16.3 runtime=node arch=x64 platform=win32)

C:\Users\Naman\JPMC-tech-task-2-PY3\node_modules\bufferutil>if not defined npm_config_node_gyp (node "C:\Users\Naman\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\Naman\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "-m" switch.
  bufferutil.cc
  win_delay_load_hook.cc
C:\Users\Naman\JPMC-tech-task-2-PY3\node_modules\bufferutil\node_modules\nan\nan_converters_43_inl.h(22,1): warning C49
96: 'v8::Value::ToBoolean': was declared deprecated (compiling source file ..\src\bufferutil.cc) [C:\Users\Naman\JPMC-t
ech-task-2-PY3\node_modules\bufferutil\build\bufferutil.vcxproj]
C:\Users\Naman\JPMC-tech-task-2-PY3\node_modules\bufferutil\node_modules\nan\nan_converters_43_inl.h(40,1): warning C49
96: 'v8::Value::BooleanValue': was declared deprecated (compiling source file ..\src\bufferutil.cc) [C:\Users\Naman\JPM
C-tech-task-2-PY3\node_modules\bufferutil\build\bufferutil.vcxproj]
C:\Users\Naman\JPMC-tech-task-2-PY3\node_modules\bufferutil\node_modules\nan\nan_implementation_12_inl.h(103,37): error
 C2664: 'v8::MaybeLocal<v8::Function> v8::Function::New(v8::Local<v8::Context>,v8::FunctionCallback,v8::Local<v8::Value
>,int,v8::ConstructorBehavior,v8::SideEffectType)': cannot convert argument 1 from 'v8::Isolate *' to 'v8::Local<v8::Co
ntext>' (compiling source file ..\src\bufferutil.cc) [C:\Users\Naman\JPMC-tech-task-2-PY3\node_modules\bufferutil\build
\bufferutil.vcxproj]
C:\Users\Naman\JPMC-tech-task-2-PY3\node_modules\bufferutil\node_modules\nan\nan_implementation_12_inl.h(105,32): messa
ge : No constructor could take the source type, or constructor overload resolution was ambiguous (compiling source file
 ..\src\bufferutil.cc) [C:\Users\Naman\JPMC-tech-task-2-PY3\node_modules\bufferutil\build\bufferutil.vcxproj]
C:\Users\Naman\AppData\Local\node-gyp\Cache\12.16.3\include\node\v8.h(4275,31): message : see declaration of 'v8::Funct
ion::New' (compiling source file ..\src\bufferutil.cc) [C:\Users\Naman\JPMC-tech-task-2-PY3\node_modules\bufferutil\bui
ld\bufferutil.vcxproj]
C:\Users\Naman\JPMC-tech-task-2-PY3\node_modules\bufferutil\node_modules\nan\nan_implementation_12_inl.h(337,37): error
 C2660: 'v8::StringObject::New': function does not take 1 arguments (compiling source file ..\src\bufferutil.cc) [C:\Us
ers\Naman\JPMC-tech-task-2-PY3\node_modules\bufferutil\build\bufferutil.vcxproj]
C:\Users\Naman\AppData\Local\node-gyp\Cache\12.16.3\include\node\v8.h(5531,23): message : see declaration of 'v8::Strin
gObject::New' (compiling source file ..\src\bufferutil.cc) [C:\Users\Naman\JPMC-tech-task-2-PY3\node_modules\bufferutil
\build\bufferutil.vcxproj]
C:\Users\Naman\JPMC-tech-task-2-PY3\node_modules\bufferutil\node_modules\nan\nan_implementation_12_inl.h(337,60): error
 C2059: syntax error: ')' (compiling source file ..\src\bufferutil.cc) [C:\Users\Naman\JPMC-tech-task-2-PY3\node_module
s\bufferutil\build\bufferutil.vcxproj]
C:\Users\Naman\JPMC-tech-task-2-PY3\node_modules\bufferutil\node_modules\nan\nan.h(1034,1): error C2661: 'v8::Value::To
String': no overloaded function takes 0 arguments (compiling source file ..\src\bufferutil.cc) [C:\Users\Naman\JPMC-tec
h-task-2-PY3\node_modules\bufferutil\build\bufferutil.vcxproj]
C:\Users\Naman\JPMC-tech-task-2-PY3\node_modules\bufferutil\node_modules\nan\nan.h(1044,1): error C2664: 'int v8::Strin
g::WriteUtf8(v8::Isolate *,char *,int,int *,int) const': cannot convert argument 1 from 'char *' to 'v8::Isolate *' (co
mpiling source file ..\src\bufferutil.cc) [C:\Users\Naman\JPMC-tech-task-2-PY3\node_modules\bufferutil\build\bufferutil
.vcxproj]
C:\Users\Naman\JPMC-tech-task-2-PY3\node_modules\bufferutil\node_modules\nan\nan.h(1044,37): message : Types pointed to
 are unrelated; conversion requires reinterpret_cast, C-style cast or function-style cast (compiling source file ..\src
\bufferutil.cc) [C:\Users\Naman\JPMC-tech-task-2-PY3\node_modules\bufferutil\build\bufferutil.vcxproj]
C:\Users\Naman\AppData\Local\node-gyp\Cache\12.16.3\include\node\v8.h(2878,7): message : see declaration of 'v8::String
::WriteUtf8' (compiling source file ..\src\bufferutil.cc) [C:\Users\Naman\JPMC-tech-task-2-PY3\node_modules\bufferutil\
build\bufferutil.vcxproj]
C:\Users\Naman\JPMC-tech-task-2-PY3\node_modules\bufferutil\node_modules\nan\nan.h(1818,26): warning C4996: 'v8::Object
::Set': was declared deprecated (compiling source file ..\src\bufferutil.cc) [C:\Users\Naman\JPMC-tech-task-2-PY3\node_
modules\bufferutil\build\bufferutil.vcxproj]
C:\Users\Naman\JPMC-tech-task-2-PY3\node_modules\bufferutil\node_modules\nan\nan.h(1824,26): warning C4996: 'v8::Object
::Set': was declared deprecated (compiling source file ..\src\bufferutil.cc) [C:\Users\Naman\JPMC-tech-task-2-PY3\node_
modules\bufferutil\build\bufferutil.vcxproj]
C:\Users\Naman\JPMC-tech-task-2-PY3\node_modules\bufferutil\node_modules\nan\nan.h(1830,26): warning C4996: 'v8::Object
::Set': was declared deprecated (compiling source file ..\src\bufferutil.cc) [C:\Users\Naman\JPMC-tech-task-2-PY3\node_
modules\bufferutil\build\bufferutil.vcxproj]
C:\Users\Naman\JPMC-tech-task-2-PY3\node_modules\bufferutil\node_modules\nan\nan.h(1836,30): warning C4996: 'v8::Object
::Get': was declared deprecated (compiling source file ..\src\bufferutil.cc) [C:\Users\Naman\JPMC-tech-task-2-PY3\node_
modules\bufferutil\build\bufferutil.vcxproj]
C:\Users\Naman\JPMC-tech-task-2-PY3\node_modules\bufferutil\node_modules\nan\nan.h(1842,46): warning C4996: 'v8::Object
::Get': was declared deprecated (compiling source file ..\src\bufferutil.cc) [C:\Users\Naman\JPMC-tech-task-2-PY3\node_
modules\bufferutil\build\bufferutil.vcxproj]
C:\Users\Naman\JPMC-tech-task-2-PY3\node_modules\bufferutil\node_modules\nan\nan.h(1847,46): warning C4996: 'v8::Object
::Get': was declared deprecated (compiling source file ..\src\bufferutil.cc) [C:\Users\Naman\JPMC-tech-task-2-PY3\node_
modules\bufferutil\build\bufferutil.vcxproj]
C:\Users\Naman\JPMC-tech-task-2-PY3\node_modules\bufferutil\node_modules\nan\nan_object_wrap.h(24,1): error C2039: 'IsN
earDeath': is not a member of 'Nan::Persistent<v8::Object,v8::NonCopyablePersistentTraits<T>>' [C:\Users\Naman\JPMC-tec
h-task-2-PY3\node_modules\bufferutil\build\bufferutil.vcxproj]
          with
          [
              T=v8::Object
          ] (compiling source file ..\src\bufferutil.cc)
C:\Users\Naman\JPMC-tech-task-2-PY3\node_modules\bufferutil\node_modules\nan\nan.h(1859): message : see declaration of
'Nan::Persistent<v8::Object,v8::NonCopyablePersistentTraits<T>>' [C:\Users\Naman\JPMC-tech-task-2-PY3\node_modules\buff
erutil\build\bufferutil.vcxproj]
          with
          [
              T=v8::Object
          ] (compiling source file ..\src\bufferutil.cc)
C:\Users\Naman\JPMC-tech-task-2-PY3\node_modules\bufferutil\node_modules\nan\nan_object_wrap.h(67,17): warning C4996: '
v8::PersistentBase<v8::Object>::MarkIndependent': was declared deprecated (compiling source file ..\src\bufferutil.cc)
[C:\Users\Naman\JPMC-tech-task-2-PY3\node_modules\bufferutil\build\bufferutil.vcxproj]
C:\Users\Naman\JPMC-tech-task-2-PY3\node_modules\bufferutil\node_modules\nan\nan_object_wrap.h(124,1): error C2039: 'Is
NearDeath': is not a member of 'Nan::Persistent<v8::Object,v8::NonCopyablePersistentTraits<T>>' [C:\Users\Naman\JPMC-te
ch-task-2-PY3\node_modules\bufferutil\build\bufferutil.vcxproj]
          with
          [
              T=v8::Object
          ] (compiling source file ..\src\bufferutil.cc)
C:\Users\Naman\JPMC-tech-task-2-PY3\node_modules\bufferutil\node_modules\nan\nan.h(1859): message : see declaration of
'Nan::Persistent<v8::Object,v8::NonCopyablePersistentTraits<T>>' [C:\Users\Naman\JPMC-tech-task-2-PY3\node_modules\buff
erutil\build\bufferutil.vcxproj]
          with
          [
              T=v8::Object
          ] (compiling source file ..\src\bufferutil.cc)
C:\Users\Naman\JPMC-tech-task-2-PY3\node_modules\bufferutil\src\bufferutil.cc(12,64): error C2660: 'v8::Value::Int32Val
ue': function does not take 0 arguments [C:\Users\Naman\JPMC-tech-task-2-PY3\node_modules\bufferutil\build\bufferutil.v
cxproj]
C:\Users\Naman\AppData\Local\node-gyp\Cache\12.16.3\include\node\v8.h(2709,40): message : see declaration of 'v8::Value
::Int32Value' (compiling source file ..\src\bufferutil.cc) [C:\Users\Naman\JPMC-tech-task-2-PY3\node_modules\bufferutil
\build\bufferutil.vcxproj]
C:\Users\Naman\JPMC-tech-task-2-PY3\node_modules\bufferutil\src\bufferutil.cc(13,39): error C2660: 'v8::Value::Int32Val
ue': function does not take 0 arguments [C:\Users\Naman\JPMC-tech-task-2-PY3\node_modules\bufferutil\build\bufferutil.v
cxproj]
C:\Users\Naman\AppData\Local\node-gyp\Cache\12.16.3\include\node\v8.h(2709,40): message : see declaration of 'v8::Value
::Int32Value' (compiling source file ..\src\bufferutil.cc) [C:\Users\Naman\JPMC-tech-task-2-PY3\node_modules\bufferutil
\build\bufferutil.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Current\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\Naman\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:310:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Windows_NT 10.0.17763
gyp ERR! command "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Users\\Naman\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\Naman\JPMC-tech-task-2-PY3\node_modules\bufferutil
gyp ERR! node -v v12.16.3
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
npm WARN bootstrap@4.2.1 requires a peer of jquery@1.9.1 - 3 but none is installed. You must install peer dependencies yourself.
npm WARN bootstrap@4.2.1 requires a peer of popper.js@^1.14.6 but none is installed. You must install peer dependencies yourself.
npm WARN extract-text-webpack-plugin@3.0.2 requires a peer of webpack@^3.1.0 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! bufferutil@3.0.5 install: `prebuild-install || node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bufferutil@3.0.5 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Naman\AppData\Roaming\npm-cache\_logs\2020-05-22T11_52_34_184Z-debug.log

**Comment by KratikaArora** [comment]
I have also installed 2.7x version still it is showing the error.

**Comment by Naman-1234** [comment]
After installing npm uninstall python 2.7 then install python 3.8,Try to do so even after that if u get some error then upload either photo of error and also make sure to include python in path,for safety
Also upload screenshot of path variables.
