### ISSUE TITLE
Issue in creating patch file

### ISSUE THREAD

**Issue by ShivaniGupta1604** [insidesherpa/JPMC-tech-task-2-PY3#259]
![Screenshot (140)](https://user-images.githubusercontent.com/56301436/82465180-9dd9ca00-9adc-11ea-9276-50cc53781691.png)

**Comment by harmankaur23** [comment]
try using "" for create patch file worked for me

**Comment by Miguel-7** [comment]
Thanks @harmankaur23 ! I fixed this issue with your tip.
