### ISSUE TITLE
Having trouble with npm install and npm start

### ISSUE THREAD

**Issue by Charleneshanshan** [insidesherpa/JPMC-tech-task-2-PY3#26]
This happens when I typed: npm install
<img width="571" alt="Screenshot 2019-12-19 at 18 14 48" src="https://user-images.githubusercontent.com/59060296/71198454-baeb4200-228b-11ea-9a9b-023706635c94.png">
This happens when I typed: npm start:
<img width="571" alt="Screenshot 2019-12-19 at 18 15 07" src="https://user-images.githubusercontent.com/59060296/71198505-d22a2f80-228b-11ea-8dbb-4ae7b3c2bd2a.png">

I am using Mac and also install python 2.7x and python 3.19 has already existed as I have anaconda. I tried to solve the problems but failed every time.

**Comment by Charleneshanshan** [comment]
I also use the command to map with my python 2.7x version, still failed.

**Comment by amel-er** [comment]
I had the same and I typed "npm audit fix" and it worked. But I also have the same when I type npm start

**Comment by jbf-insidesherpa** [comment]
@Charleneshanshan python 3.19 is pretty old for the python3 versions, try using a more recent one e.g. python3.6 onwards. If it still fails, try using your python2.7 and use the python2.7 version for this task i.e. https://github.com/insidesherpa/JPMC-tech-task-2

**Comment by neissacodes** [comment]
I am using python 3.7 and it gives me the same issue.  
![JPMCtask2](https://user-images.githubusercontent.com/47401355/71945177-16766480-3194-11ea-92e8-f7cca7654f7b.PNG)

**Comment by jbf-insidesherpa** [comment]
@neissacodes based on your screenshot, your command line is in the wrong folder. You're supposed to be inside the repository before you execute any of the instructed commands e.g. **npm install**

You have to change directory first (i.e. you can use the **cd** command for this). You need to make the present working directory context of your command line to be inside the repository.
