### ISSUE TITLE
Different App.tsx

### ISSUE THREAD

**Issue by neissacodes** [insidesherpa/JPMC-tech-task-2-PY3#28]
While editing the App.tsx code I realized that I have a different code than the one in the guide and now I do not know to properly edit it. 
![App JPMC](https://user-images.githubusercontent.com/47401355/71642419-befa6500-2c78-11ea-948c-dda348c18a42.PNG)

**Comment by jbf-insidesherpa** [comment]
@neissacodes from the looks of it, it seems you opened the wrong App.tsx here.
You're need to edit the App.tsx inside the **src** folder from the root of the repository. In your screenshot, you're editing an App.tsx file that is in the deep end of the **node_modules** repo. The **node_modules** folder is not some place you usually edit in as those files are produced after doing the **npm install**
