### ISSUE TITLE
Error Once Clicking "Start Streaming Data"

### ISSUE THREAD

**Issue by briannaxlee** [insidesherpa/JPMC-tech-task-2-PY3#280]
When I click "Start Streaming Data", nothing happens. I don't get any chart or any data appear but in my terminal, I get an error. I've attached a screenshot of what happens when I click the button, I get the error in the photo below. I installed pip and my npm but I'm unsure how to fix the problem. I use a Mac.

<img width="989" alt="Screen Shot 2020-05-23 at 1 02 36 PM" src="https://user-images.githubusercontent.com/30237363/82736199-bf61ce00-9cf5-11ea-9a90-365eb86a7575.png">

**Comment by bumblebee26** [comment]
Is it similar ??
 
![image](https://user-images.githubusercontent.com/47007437/82736488-c87b8b00-9d47-11ea-8be9-be2de86db5a2.png)

**Comment by briannaxlee** [comment]
> Is it similar ??
> 
> ![image](https://user-images.githubusercontent.com/47007437/82736488-c87b8b00-9d47-11ea-8be9-be2de86db5a2.png)

The only difference I think between mine is that I never see the NetworkError? I've attached screenshots to show what my screen looks like. I'm able to open the three dots but I still don't get any data popping up and get the same error pop up in my terminal?

<img width="729" alt="Screen Shot 2020-05-23 at 1 31 23 PM" src="https://user-images.githubusercontent.com/30237363/82736838-752f1b80-9cfa-11ea-9b72-1f73a3facbc1.png">
<img width="637" alt="Screen Shot 2020-05-23 at 1 31 12 PM" src="https://user-images.githubusercontent.com/30237363/82736839-752f1b80-9cfa-11ea-9248-79330249898e.png">

**Comment by bumblebee26** [comment]
Ok so the problem was from my end as I didn't run server3.py file
Now I think its working pretty good

![image](https://user-images.githubusercontent.com/47007437/82736913-aafbf080-9d4a-11ea-8da9-0c5f82b03edf.png)

**Comment by briannaxlee** [comment]
Is there anything else that you did differently? I'm also running the server3.py file but haven't been able to figure out what's going out.

**Comment by bumblebee26** [comment]
No, I just had this fix. Also, I am on Windows and python 3.7.5
I looked up your issue and it seems like this could help 

remove the whole encoding method from bytes input (wild try I don't know if it'll work)
Good luck

**Comment by souromisen** [comment]
hi! I am getting the same error in task 3, but my server3.py is running and its still not working! any solutions?
