### ISSUE TITLE
For those are getting error in npm install .TRY THIS.

### ISSUE THREAD

**Issue by Nimish-0** [insidesherpa/JPMC-tech-task-2-PY3#282]
First of all. Do everything properly till slide or page 46.
then,  you are instructed to type the following commands:
nvm install v11.0.0
nvm use 11.0.0

dont use this version please its outdated, instead go to this website https://nodejs.org/en/ 
which shows you the latest node version, type that version.
for example currently its 14.3.0
type :
nvm install 14.3.0
nvm use 14.3.0
(make sure you are in the right path in command prompt i.e where your task files are)

after that,
npm config set msvs_version 2019
(2019 is latest version u downloaded not 2017)

npm install
(series of error will appear dont worry)
npm install --force
npm audit fix
npm start

There you go :)

**Comment by jc11499** [comment]
> First of all. Do everything properly till slide or page 46.
> then, you are instructed to type the following commands:
> nvm install v11.0.0
> nvm use 11.0.0
> 
> dont use this version please its outdated, instead go to this website https://nodejs.org/en/
> which shows you the latest node version, type that version.
> for example currently its 14.3.0
> type :
> nvm install 14.3.0
> nvm use 14.3.0
> (make sure you are in the right path in command prompt i.e where your task files are)
> 
> after that,
> npm config set msvs_version 2019
> (2019 is latest version u downloaded not 2017)
> 
> npm install
> (series of error will appear dont worry)
> npm install --force
> npm audit fix
> npm start
> 
> There you go :)

Same errors are getting displayed
