### ISSUE TITLE
Graph Isn't Showing Up and Start Streaming Data Button Isn't Working

### ISSUE THREAD

**Issue by briannaxlee** [insidesherpa/JPMC-tech-task-2-PY3#283]
I'm coming across an issue where I'm unable to click on the "Start Streaming Data" button. If I do, i get this long error message in Terminal. I had this issue before, but I was able to see the three dots then and click on it get a whole set up with menus that dragged down. Now, I don't have any of that and unable to figure out what the problem is. I've tried to restart Terminal and possibly look for syntax errors but I've fixed everything from the Network Error. I use a Mac and would love if anyone could help me out with this.

<img width="409" alt="Screen Shot 2020-05-24 at 1 53 00 AM" src="https://user-images.githubusercontent.com/30237363/82746759-6e87bf00-9d61-11ea-8701-9a7edebd5460.png">
<img width="947" alt="Screen Shot 2020-05-24 at 1 52 50 AM" src="https://user-images.githubusercontent.com/30237363/82746760-6e87bf00-9d61-11ea-8614-2ebc40970627.png">

**Comment by Kam149** [comment]
Are you running python datafeed/server2.py simultaneously in another cmd?

**Comment by briannaxlee** [comment]
i'm running it in server3, is it supposed to be 2?

**Comment by Kam149** [comment]
Which version of python are you using python 3.x or python 2.x?

**Comment by briannaxlee** [comment]
I'm using python 3 for this

**Comment by Kam149** [comment]
But the error in the screenshots is pointing error in python 2.7? Why is it so?

**Comment by briannaxlee** [comment]
Sorry for the late response.

I'm not sure but I'm using the Python 3 repository. Does this mean that my computer didn't install python 3 even though I downloaded it in the beginning? Should I try to use the other repository and see if it works?

**Comment by Kam149** [comment]
You can go for it.
