### ISSUE TITLE
npm install failed

### ISSUE THREAD

**Issue by bosenli** [insidesherpa/JPMC-tech-task-2-PY3#29]
This is what i have for the error after i typed "npm install" at the command line. I also tried to use different method to install npm but also failed. 

![image](https://user-images.githubusercontent.com/36967751/72085980-390f9700-32d4-11ea-8ac4-95ecd87f8df4.png)

![image](https://user-images.githubusercontent.com/36967751/72086165-7bd16f00-32d4-11ea-93d5-7fef5d1b1028.png)

**Comment by jbf-insidesherpa** [comment]
The setup guide discusses how to deal with this issue (see page 61/95). i.e. you have to specify to npm what python executable/binary to use

![image](https://user-images.githubusercontent.com/54832297/72229122-fe18a680-35e6-11ea-8bf9-bd4bac5273cb.png)
