### ISSUE TITLE
Patch file issue(Task 2)

### ISSUE THREAD

**Issue by harshdubey16** [insidesherpa/JPMC-tech-task-2-PY3#291]
C:\Users\harsh\JPMC-tech-task-2-PY3>git commit -m 'Create Patch File'
error: pathspec 'Patch' did not match any file(s) known to git
error: pathspec 'File'' did not match any file(s) known to git
@jbf-insidesherpa how do I solve this issue????
tried every error solving:
eg. git fetch 
but still no success.

**Comment by nehasingh24** [comment]
https://github.com/insidesherpa/JPMC-tech-task-2-PY3/issues/291#issue-624207288 
hi did you find thesolution for above? or we can just continuew as next line is working

**Comment by PCD-Consultancy-Services** [comment]
how did you solve this ?
