### ISSUE TITLE
Dateutil

### ISSUE THREAD

**Issue by Naman-1234** [insidesherpa/JPMC-tech-task-2-PY3#298]
I have already installed dateutil as shown in command given below but when i try to import it it says no dateutil found. Pls help as I have been kind of stuck in task 2 for about a week.

Requirement already satisfied: python-dateutil in c:\users\naman\appdata\local\programs\python\python38\lib\site-packages (2.8.1)
Requirement already satisfied: six>=1.5 in c:\users\naman\appdata\roaming\python\python38\site-packages (from python-dateutil) (1.14.0)

**Comment by JKeerthi-21** [comment]
Same here...Someone please help me with this

**Comment by adititiwari19** [comment]
Install pip/Update pip and then runthe following command :
pip install python-dateutil

You could also refer to page 56 of https://insidesherpa.s3.amazonaws.com/vinternships/companyassets/Sj7temL583QAYpHXD/setup_devenv_m2_v8.pdf

**Comment by Naman-1234** [comment]
![Screenshot (431)](https://user-images.githubusercontent.com/63748249/82990657-247d3280-a01a-11ea-9f42-0ba5a1d2c145.png)
@adititiwari19  I have already installed pip and dateutil but maybe problem is in the path,I am unable to find the problem,Please look down to the screenshot given above and give the solution.
In this it is showing that pip version is 19.213 which shows that pip is installed and then it also installed dateutil for the first time,but when I tried to use it it stated that No Module Named Dateutil,So I thought that maybe dateutil was not installed and I tried to install it then it says requirement already satisfied which clearly states that it is installed but for some reason I am unable to use it,Kindly Help.
[](url)

**Comment by Geno2208** [comment]
@Naman-1234 
That's probably because  the python version being used is python 2. You can check that by typing python --version. 
Solution:
1. Remove Python 2 path from the PATH variable in Environment Variables.
2. python --version. Run this command again. You'll then see it now uses Python3.
There will be no further error since dateutil is present in python3.

**Comment by Naman-1234** [comment]
@Geno2208  But I am already using python 3.8,I installed python 2.7 but have already uninstalledn it from my system. Pls help 
![Screenshot (434)](https://user-images.githubusercontent.com/63748249/83029757-a9833e80-a050-11ea-8f76-316c6bc1558a.png)

**Comment by Naman-1234** [comment]
There might be problem in my path,I am giving below its screenshots,It will be very nice if anyone can see a mistake and help me to correct it
![Screenshot (436)](https://user-images.githubusercontent.com/63748249/83033179-688d2900-a054-11ea-82d4-a376e0692132.png)

**Comment by Geno2208** [comment]
Everything looks fine. Can you try the following:
1. Update pip using python -m pip install --upgrade pip and check.
If that doesn't work:
2. Try removing the Python38-32 path from the PATH variable.

**Comment by Naman-1234** [comment]
@Geno2208  Thnku so much,It was creating that mess all the time. I am very grateful to you for solving that error.
