### ISSUE TITLE
Failed To Complile

### ISSUE THREAD

**Issue by mjki4hj3** [insidesherpa/JPMC-tech-task-2-PY3#3]
Hello,

After following the steps in the guideline the following compilation error appeared. I am using macOS.

![image](https://user-images.githubusercontent.com/48074310/68089362-08d4f380-fe60-11e9-9156-33273b231f0f.png)

**Comment by mjki4hj3** [comment]
When I tried to update npm I get the following error which I suspect why it is not working
![image](https://user-images.githubusercontent.com/48074310/68089478-10e16300-fe61-11e9-8937-c4ecfd94cf4d.png)

**Comment by jbf-insidesherpa** [comment]
@mjki4hj3 what are your node and npm versions? 
You can check them by doing the ff commands
`node -v`
`npm -v`

**Comment by abdulmateen-1** [comment]
I carefully followed the step and procedures but I still got a compilation error, I also tried to download perspective, which showed the same result.
Node version: v11.0.0
npm version: 6.4.1


Failed to compile
C:/Users/akind/JPMC-tech-task-2-PY3/src/Graph.tsx
Type error: Cannot find module '@jpmorganchase/perspective'.  TS2307

    1 | import React, { Component } from 'react';
  > 2 | import { Table } from '@jpmorganchase/perspective';
      |                       ^
    3 | import { ServerRespond } from './DataStreamer';
    4 | import './Graph.css';
    5 |

**Comment by jbf-insidesherpa** [comment]
@abdulmateen-1 can you provide the following info:
- What is your OS?
- What was the output of npm install in your command line / terminal 
- Do you have python2.7.x on your system too?

**Comment by abdulmateen-1** [comment]
-Windows 10
- 
![npm3](https://user-images.githubusercontent.com/46570153/68191035-99085b00-ff7c-11e9-94af-f2e6e33c2049.PNG)
- I have python3.8 installed in.

**Comment by jbf-insidesherpa** [comment]
@abdulmateen-1 can you post the result/output of your `npm install` from the JPMC-tech-task2-PY3 directory?

**Comment by abdulmateen-1** [comment]
Ok
![npm1](https://user-images.githubusercontent.com/46570153/68191646-fc46bd00-ff7d-11e9-9bbf-1f8f5740f874.PNG)

**Comment by abdulmateen-1** [comment]
![npm4](https://user-images.githubusercontent.com/46570153/68192454-5a27d480-ff7f-11e9-949a-7644613e46b2.PNG)

**Comment by jbf-insidesherpa** [comment]
@abdulmateen-1 so the reason the client app is not compiling on your end is because `npm install` fails hence not all dependencies are installed.
From the looks of the error you got, it seems it's related to python on your system
![image](https://user-images.githubusercontent.com/54832297/68193879-ede4b980-ffee-11e9-899c-c3aafcf18439.png)

How did you output your python version btw? The error seems to indicate python is not in your system's environment variables. So how do you execute a python script on your machine? (i.e.what command do you use?)

**Comment by abdulmateen-1** [comment]
![pythonV](https://user-images.githubusercontent.com/46570153/68194203-9ad51d00-ff82-11e9-844a-b5cb3d269c4b.PNG)

**Comment by jbf-insidesherpa** [comment]
@abdulmateen-1 can you check your system environment variables? Here's what mine looks like
![image](https://user-images.githubusercontent.com/54832297/68194659-5d0edd80-fff0-11e9-9495-9aa70ebdaad9.png)

**Comment by abdulmateen-1** [comment]
![var1](https://user-images.githubusercontent.com/46570153/68195134-4f237300-ff84-11e9-9acc-85ea95599803.PNG)

**Comment by abdulmateen-1** [comment]
I recently deleted my python2.7, I have no idea how it's still showing up there.

**Comment by jbf-insidesherpa** [comment]
@abdulmateen-1 try reinstalling it again. No harm in having 2 python versions. If you saw my screen shot I have both 2.7 and 3 on the windows machine. 

Just make sure you add the properly in the  system environment variables. On the windows machine I have I can `python` is mapped to 2.7.x while `python3` is mapped to 3.8.x
![image](https://user-images.githubusercontent.com/54832297/68196095-08209680-fff3-11e9-9d1b-df016f35afac.png)

**Comment by abdulmateen-1** [comment]
I have it working now, thanks.

**Comment by spencerj411** [comment]
Hi @jbf-insidesherpa , I'm also getting errors when trying to run `npm install`. I'm using Windows 10, Python 3.7.3:
`node -v` returns _v11.0.0_
`npm -v` returns _6.4.1_

Output after running `npm install`:
![image](https://user-images.githubusercontent.com/24206502/68210034-c579b100-0028-11ea-9a76-bea22b995e82.png)

**Comment by jbf-insidesherpa** [comment]
@spencerj411 I presume you're running on Windows?
Can you show me your system's environment variables? Like the screenshot I sent @abdulmateen-1 earlier.

It would also help if you tried installing python 2.7.x in your system (even if you have python 3.x) and add it in your system's environment variables as well. You can use my system's environment variable settings as reference i.e. https://user-images.githubusercontent.com/54832297/68194659-5d0edd80-fff0-11e9-9495-9aa70ebdaad9.png

**Comment by spencerj411** [comment]
So I did some research and according to [the robotjs github](https://github.com/octalmage/robotjs), Windows requires the _windows-build-tools npm package_. I installed it, and after runnig `npm install` it outputted this:
![image](https://user-images.githubusercontent.com/24206502/68212692-28ba1200-002e-11ea-9491-6ad232f8c434.png)

I'm not sure what those _vulnerabilities_ are but when I run `npm start` it seems to work:
![image](https://user-images.githubusercontent.com/24206502/68212740-47200d80-002e-11ea-863a-5cdcfc06bc0d.png)

**Comment by jbf-insidesherpa** [comment]
@spencerj411 yes. We mentioned this in the [slides](https://insidesherpa.s3.amazonaws.com/vinternships/companyassets/Sj7temL583QAYpHXD/setup_devenv_m2_v4.pdf) too (slide 38/64). 

I think windows build tools will install the python2.7.x as well.

But yes, glad it works for you now :)

**Comment by spencerj411** [comment]
@jbf-insidesherpa thank you! Unfortunately, I have another problem. when I run `python server3.py` I get this:
![image](https://user-images.githubusercontent.com/24206502/68216258-b993ec00-0034-11ea-8a61-4c3f25599556.png)
Any ideas as to what the cause could be? Thanks!

**Comment by jbf-insidesherpa** [comment]
@spencerj411 let me clarify, is this error the entire error you get and do you get this error right after running `python datafeed/server3.py` (i.e. not yet running the client application?)

**Comment by spencerj411** [comment]
@jbf-insidesherpa oh I was in the _datafeed_ folder, ran `python server3.py` from there and it didn't work. I cd'd to _JPMC-tech-task-2-PY3_, ran `python datafeed\server3.py` and it worked. Thanks again for responding so promptly!

**Comment by erickapham** [comment]
I'm also running into a similar issue when I ran npm install. I'm using macOS.

<img width="1259" alt="Screen Shot 2019-11-05 at 3 04 13 PM" src="https://user-images.githubusercontent.com/38639602/68254071-7f97fb00-ffde-11e9-841f-ea58094f5469.png">

**Comment by jbf-insidesherpa** [comment]
@erickapham can you install python2.7.x on your system too?  (you can still keep python3) And retry. Also if that doesn't work, try following the instructions on how to fix installation for node-gyp here: https://github.com/nodejs/node-gyp#on-macos

**Comment by erickapham** [comment]
@jbf-insidesherpa Installing python2.7x solved the issue. Thank you!!

**Comment by stanislav-i-slavov** [comment]
Hello, I use Windows 10 and I ran into the same difficulties with npm install. I installed Python 2.7, tried reinstalling nvm and everything, but I still get the same error: 

![error_log](https://user-images.githubusercontent.com/45547687/68817123-aee9e000-064e-11ea-8999-9b96f26048c0.PNG)
Is there something else I could do

**Comment by jbf-insidesherpa** [comment]
@stanislav-i-slavov I think this has something to do with how you installed the visual build tools as instructed in [slide 38/64 of the setup guide](https://insidesherpa.s3.amazonaws.com/vinternships/companyassets/Sj7temL583QAYpHXD/setup_devenv_m2_v4.pdf).
 
Can I confirm if you followed that properly?

**Comment by stanislav-i-slavov** [comment]
@jbf-insidesherpa Yes, I followed the guide and got the screen on the next slide. I configured npm to use visual tools by the given command. I still get the same error.

**Comment by jbf-insidesherpa** [comment]
@stanislav-i-slavov can you try uninstalling your visual studio build tools and follow the one for node-gyp here
https://github.com/nodejs/node-gyp#option-2

**Comment by olatunbosunoyeleke94** [comment]
![FTC (npm install React)](https://user-images.githubusercontent.com/34801047/69228916-c06a4500-0b84-11ea-90b4-1c05eabb7abe.png)
![FTC (npm start React)](https://user-images.githubusercontent.com/34801047/69228918-c06a4500-0b84-11ea-97dd-1320c676e302.png)

this is the error I get when i try both codes, from my client terminal

**Comment by jbf-insidesherpa** [comment]
@olatunbosunoyeleke94 can you delete the entire **node_modules** folder inside the repository and redo **npm install**. Let me know if you encounter errors after that

**Comment by olatunbosunoyeleke94** [comment]
I have deleted the directory and the issue still persists @jbf-insidesherpa 
![Error](https://user-images.githubusercontent.com/34801047/69289411-b3893800-0bfc-11ea-8e5c-aaaaea6de741.png)

**Comment by jbf-insidesherpa** [comment]
> I have deleted the directory and the issue still persists @jbf-insidesherpa
> ![Error](https://user-images.githubusercontent.com/34801047/69289411-b3893800-0bfc-11ea-8e5c-aaaaea6de741.png)

did you redo **npm install**? I'm curious what the output is when you delete node_modules and you redo npm install. can you show me that?

**Comment by olatunbosunoyeleke94** [comment]
![2](https://user-images.githubusercontent.com/34801047/69290240-999d2480-0bff-11ea-8058-d62b22da531a.png)
![1](https://user-images.githubusercontent.com/34801047/69290241-999d2480-0bff-11ea-918e-57255d5a7018.png)
here @jbf-insidesherpa

**Comment by jbf-insidesherpa** [comment]
what's your node and npm version @olatunbosunoyeleke94

**Comment by olatunbosunoyeleke94** [comment]
node - 12.13.0
npm - 6.12.0
nvm - 0.35.1

**Comment by jbf-insidesherpa** [comment]
@olatunbosunoyeleke94 you should use node v11.0.0 and npm 6.4.1
make sure to do **nvm install v11.0.0** then **nvm use 11.0.0**.
Then clear your node_modules again and do npm install again

**Comment by olatunbosunoyeleke94** [comment]
i still got issues @jbf-insidesherpa 
![error](https://user-images.githubusercontent.com/34801047/69352244-e07d2f80-0c7c-11ea-9362-cda08ba3e0f7.png)

**Comment by jbf-insidesherpa** [comment]
@olatunbosunoyeleke94 that's fine. it's just puppeteer. you can remove it from package.json (I think it's at line 14) 

For some reason the installation of chromium failed for your end but it should be fine to remove that from your package.json.

**Comment by olatunbosunoyeleke94** [comment]
how do i remove this from package.json, and i have chromium on my OS already @jbf-insidesherpa

**Comment by jbf-insidesherpa** [comment]
@olatunbosunoyeleke94 yes just remove the line

**Comment by olatunbosunoyeleke94** [comment]
> @olatunbosunoyeleke94 yes just remove the line

then just run npm install again?

**Comment by olatunbosunoyeleke94** [comment]
this is what i still get @jbf-insidesherpa 
![error](https://user-images.githubusercontent.com/34801047/69354964-453a8900-0c81-11ea-8460-32be8fead261.png)

**Comment by jbf-insidesherpa** [comment]
@olatunbosunoyeleke94 sent you an email. Please check

**Comment by timothykmulenga** [comment]
`npm ERR! code EJSONPARSE
npm ERR! JSON.parse Failed to parse json
npm ERR! JSON.parse Unexpected string in JSON at position 578 while parsing '{
npm ERR! JSON.parse   "name": "bank-merge-co-task-2",
npm ERR! JSON.parse   "v'
npm ERR! JSON.parse Failed to parse package.json data.
npm ERR! JSON.parse package.json must be actual JSON, not just JavaScript.
`
i got this error after doing everything up there

**Comment by jbf-insidesherpa** [comment]
@timothykmulenga have made any changes to the files already?  can you put screenshots of the outputs of **npm install** and **npm start** on your end?

**Comment by timothykmulenga** [comment]
Yes i have made several changes based on previous debugging comments but nothing seems to work
Here is the screen shot for `npm install
![Screenshot from 2020-02-08 07-23-05](https://user-images.githubusercontent.com/60673572/74079777-b7cb3180-4a44-11ea-8430-8572cd9953f7.png)
`

**Comment by timothykmulenga** [comment]
Uploading Screenshot from 2020-02-08 07-23-05.png…

**Comment by timothykmulenga** [comment]
![Screenshot from 2020-02-08 07-23-05](https://user-images.githubusercontent.com/60673572/74079809-2c05d500-4a45-11ea-9e21-13a99e4e8047.png)

**Comment by timothykmulenga** [comment]
![Screenshot from 2020-02-08 07-36-21](https://user-images.githubusercontent.com/60673572/74079863-c239fb00-4a45-11ea-888b-9829b2587301.png)
now there server3.py is also failing to load

**Comment by jbf-insidesherpa** [comment]
@timothykmulenga for the npm errors you're getting it seems like it's due to a syntax error you've made in one of the files you've changed (if you've changed any of the files already). If not can you restart the state of the repo by doing
```
git checkout -- .
```
Then show the output of npm install for you

As for the python error, it seems you haven't installed the date-util dependency. Please refer to the troubleshooting slides in the setup guide. A lot of the common issues are discussed there.

**Comment by timothykmulenga** [comment]
@jbf-insidesherpa i uninstalled everything and made a redo, the server is running properly now but um getting the following error for `npm install`

![Screenshot from 2020-02-08 08-17-39](https://user-images.githubusercontent.com/60673572/74080391-4d1df400-4a4c-11ea-9ffd-ec5c09fb563b.png)

**Comment by spk3012** [comment]
![Screenshot from 2020-04-05 05-29-33](https://user-images.githubusercontent.com/51240818/78458614-66e85a00-76d0-11ea-97e9-17914ca18854.png)
Getting this error on running "npm install"
and 
![Screenshot from 2020-04-05 05-31-12](https://user-images.githubusercontent.com/51240818/78458639-9bf4ac80-76d0-11ea-9c46-57889c9467f0.png)
This on running "npm start"

**Comment by jbf-insidesherpa** [comment]
@timothykmulenga @spk3012 the troubleshooting slides discuss why you get those errors. You need to also have a python2.7.17 version with you because node-gyp needs that. Then you have to map your npm to use that python version i.e. by doing

**npm config set python <path to python2.7.17 in your machine>**

so for instance, my python2.7.17 location is in /usr/bin/python

I would do

**npm config set python /usr/bin/python**

The location would vary in your machines so if you're using linux you can check it be first knowing which python command maps to the 2.7.17 version. You can do something like:
```
python --version
py --version
python2 --version
```
check which one works for you

Then you can check the location by using the **which** command
**which python**

For windows, there's a different way that you can just check the location via the start command. Make sure it's not the shortcut though...

**Comment by Mohitgupta943** [comment]
> @abdulmateen-1 can you check your system environment variables? Here's what mine looks like
> ![image](https://user-images.githubusercontent.com/54832297/68194659-5d0edd80-fff0-11e9-9495-9aa70ebdaad9.png)

Thank you, It worked.

**Comment by smarthardik10** [comment]
![Capture2](https://user-images.githubusercontent.com/37779127/80954689-7ff14180-8e1b-11ea-8b20-20c4f349662a.PNG)
![Capture](https://user-images.githubusercontent.com/37779127/80954694-82539b80-8e1b-11ea-8aa7-913cce4587c0.PNG)
getting this error after doing nvm use 11.0.0 and npm install
attached environment and npm install error

**Comment by sag-007** [comment]
![jpmc](https://user-images.githubusercontent.com/44050943/80957541-fa709000-8e20-11ea-8034-1a6c1071bf90.PNG)
 

getting this error i  am running python 3.8
node 11.0.0
nvm 6.4.1

**Comment by sag-007** [comment]
![jpmc1](https://user-images.githubusercontent.com/44050943/80960351-4e31a800-8e26-11ea-9ea1-914e1f149920.PNG)
what is the error @jbf-insidesherpa

**Comment by sagaruniyal** [comment]
C:/Users/SAGAR/Desktop/JPMC-tech-task-2-PY3/src/Graph.tsx
Type error: Cannot find module '@jpmorganchase/perspective'.  TS2307

    1 | import React, { Component } from 'react';
  > 2 | import { Table } from '@jpmorganchase/perspective';
      |                       ^
    3 | import { ServerRespond } from './DataStreamer';
    4 | import './Graph.css';
    5 |

**Comment by sayanpr8175** [comment]
C:/Users/sayan/JPMC-tech-task-2-PY3/src/Graph.tsx
**### Type error: Cannot find module '@jpmorganchase/perspective'.**  TS2307

    1 | import React, { Component } from 'react';
  > 2 | import { Table } from '@jpmorganchase/perspective';
      |                       ^
    3 | import { ServerRespond } from './DataStreamer';
    4 | import './Graph.css';
    5 | 

The problem says it can not find module '**@jpmorganchase/perspective**
In the Pdf there is a link of the Google drive [(https://drive.google.com/uc?id=1ML6nECK18J0jM3hhfJdSCRtCNLssruYQ&export=download)]

![drive_link_pdf](https://user-images.githubusercontent.com/41745417/81401899-ef35a100-914d-11ea-98e1-85f428ba9024.png)
Download it. 
unzip it
and  place it inside **JPMC-tech-task-2-PY3**
and rename the file **node_modules**
and discard or change the name of previous **node_modules**

like in the image
![solution](https://user-images.githubusercontent.com/41745417/81402203-961a3d00-914e-11ea-8e73-92059ac0550c.png)

**Comment by sagaruniyal** [comment]
Thanks  for Reply

**Comment by ridzz-213** [comment]
even i am getting similiar error.
![image](https://user-images.githubusercontent.com/47481680/81531240-f8a64f80-937f-11ea-9bf0-b2e24fabb73a.png)
![image](https://user-images.githubusercontent.com/47481680/81531305-1673b480-9380-11ea-948f-03ac34c42f68.png)

**Comment by aaavinash85** [comment]
I cloned the repo to my local machine 
I cd into task 2 python3 - datafeed and try to run $python3 server3.py  and I run into following error
ryuk@ryuk:~/JP_Morgan/JPMC-tech-task-2-PY3/datafeed$ python3 server3.py 

Traceback (most recent call last):
  File "server3.py", line 320, in <module>
    run(App())
  File "server3.py", line 244, in __init__
    self._sim_start, _, _  = next(self._data_1)
StopIteration


node -v                  --  V11.0.0
npm -v                   -- 6.4.1
python3 --version  -- 3.7.5

I am using Ubuntu 19.10

**Comment by neelabhkrishna** [comment]
@finos/perspective-viewer @finos/perspective-viewer-d3fc @finos/perspective-viewer-datagrid

**Comment by swatisolanki2406** [comment]
> @jbf-insidesherpa thank you! Unfortunately, I have another problem. when I run `python server3.py` I get this:
> ![image](https://user-images.githubusercontent.com/24206502/68216258-b993ec00-0034-11ea-8a61-4c3f25599556.png)
> Any ideas as to what the cause could be? Thanks!

Did you find out, the solution for this?

**Comment by THEBEAST310** [comment]
You need to remove the parenthesis App"()". Then it works fine.

**Comment by lakshay96** [comment]
![image](https://user-images.githubusercontent.com/56135786/83573155-8b35ab00-a548-11ea-89cd-3424223c6664.png)
can someone help me fix my bug?

**Comment by SaiBharathReddy** [comment]
C:\Users\HP\Desktop\JPMC-tech-task-2-PY3>npm install

> bufferutil@3.0.5 install C:\Users\HP\Desktop\JPMC-tech-task-2-PY3\node_modules\bufferutil
> prebuild-install || node-gyp rebuild

prebuild-install WARN install No prebuilt binaries found (target=11.0.0 runtime=node arch=x64 platform=win32)

C:\Users\HP\Desktop\JPMC-tech-task-2-PY3\node_modules\bufferutil>if not defined npm_config_node_gyp (node "C:\Users\HP\Desktop\NVM\nvm\v11.0.0\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\HP\Desktop\NVM\nvm\v11.0.0\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
gyp ERR! configure error
gyp ERR! stack Error: Command failed: C:\ProgramData\Anaconda3\python.EXE -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                                ^
gyp ERR! stack SyntaxError: invalid syntax
gyp ERR! stack
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:289:12)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at maybeClose (internal/child_process.js:962:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
gyp ERR! System Windows_NT 10.0.18362
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\HP\\Desktop\\NVM\\nvm\\v11.0.0\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\HP\Desktop\JPMC-tech-task-2-PY3\node_modules\bufferutil
gyp ERR! node -v v11.0.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm WARN bootstrap@4.2.1 requires a peer of jquery@1.9.1 - 3 but none is installed. You must install peer dependencies yourself.
npm WARN bootstrap@4.2.1 requires a peer of popper.js@^1.14.6 but none is installed. You must install peer dependencies yourself.
npm WARN extract-text-webpack-plugin@3.0.2 requires a peer of webpack@^3.1.0 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! bufferutil@3.0.5 install: `prebuild-install || node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bufferutil@3.0.5 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\HP\AppData\Roaming\npm-cache\_logs\2020-06-13T09_29_42_001Z-debug.log

C:\Users\HP\Desktop\JPMC-tech-task-2-PY3>npm install

> bufferutil@3.0.5 install C:\Users\HP\Desktop\JPMC-tech-task-2-PY3\node_modules\bufferutil
> prebuild-install || node-gyp rebuild

prebuild-install WARN install No prebuilt binaries found (target=11.0.0 runtime=node arch=x64 platform=win32)

C:\Users\HP\Desktop\JPMC-tech-task-2-PY3\node_modules\bufferutil>if not defined npm_config_node_gyp (node "C:\Users\HP\Desktop\NVM\nvm\v11.0.0\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\HP\Desktop\NVM\nvm\v11.0.0\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
gyp ERR! configure error
gyp ERR! stack Error: Command failed: C:\ProgramData\Anaconda3\python.EXE -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                                ^
gyp ERR! stack SyntaxError: invalid syntax
gyp ERR! stack
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:289:12)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at maybeClose (internal/child_process.js:962:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
gyp ERR! System Windows_NT 10.0.18362
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\HP\\Desktop\\NVM\\nvm\\v11.0.0\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\HP\Desktop\JPMC-tech-task-2-PY3\node_modules\bufferutil
gyp ERR! node -v v11.0.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm WARN bootstrap@4.2.1 requires a peer of jquery@1.9.1 - 3 but none is installed. You must install peer dependencies yourself.
npm WARN bootstrap@4.2.1 requires a peer of popper.js@^1.14.6 but none is installed. You must install peer dependencies yourself.
npm WARN extract-text-webpack-plugin@3.0.2 requires a peer of webpack@^3.1.0 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! bufferutil@3.0.5 install: `prebuild-install || node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bufferutil@3.0.5 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\HP\AppData\Roaming\npm-cache\_logs\2020-06-13T15_51_48_297Z-debug.log

HELP ME TO RESOLVE THIS

**Comment by Darknight471** [comment]
Failed to compile
./src/App.tsx
SyntaxError: /mnt/g/Project/JP Morgan/Task 2/JPMC-tech-task-2-PY3/src/App.tsx: Unexpected token, expected ";" (45:19)

  43 |   	const interval =setInterval(() => {
  44 |     DataStreamer.getData((serverResponds: ServerRespond[]) => {
> 45 |       this.setState{
     |                    ^
  46 |       	data: serverResponds,
  47 |       	showGraph: true,
  48 |       });
This error occurred during the build time and cannot be dismissed.

**Comment by veersan** [comment]
The @jpmorgan file itself wasnt there in the nodes_module
So I copied that from the node files(Download it from slide 92).
The error does'nt show anymore.
Try this.

**Comment by chaseroldan** [comment]
> The @jpmorgan file itself wasnt there in the nodes_module
> So I copied that from the node files(Download it from slide 92).
> The error does'nt show anymore.
> Try this.

This solved it for me

**Comment by Christysss** [comment]
> @timothykmulenga @spk3012 the troubleshooting slides discuss why you get those errors. You need to also have a python2.7.17 version with you because node-gyp needs that. Then you have to map your npm to use that python version i.e. by doing
> 
> **npm config set python **
> 
> so for instance, my python2.7.17 location is in /usr/bin/python
> 
> I would do
> 
> **npm config set python /usr/bin/python**
> 
> The location would vary in your machines so if you're using linux you can check it be first knowing which python command maps to the 2.7.17 version. You can do something like:
> 
> ```
> python --version
> py --version
> python2 --version
> ```
> 
> check which one works for you
> 
> Then you can check the location by using the **which** command
> **which python**
> 
> For windows, there's a different way that you can just check the location via the start command. Make sure it's not the shortcut though...

I installed the both python2.7 and 3.7, in the folder task-2-py3, ran npm start gives me this:

![image](https://user-images.githubusercontent.com/49929520/109234864-7fef7300-779a-11eb-802f-4076baafc8d5.png)


windows
`python --version `        Python3.7.4
`py --version`       Python2.7.18
`node -v `       v11.0.0
`npm -v `        6.4.1

added python2.7 in system's environment variables
downloaded node_modules from ppt and replaced it in the folder
Still not works, then I use `where py`
`npm config set python C:\Windows\py.exe`
`npm install`

now, have this issue:
![InkedOHO_21NO%@X$J3)`1C{NZF4_LI](https://user-images.githubusercontent.com/49929520/109236583-e4600180-779d-11eb-8bf0-4b717fbcbf91.jpg)


BTW, even if I run
`npm update caniuse-lite browserslist`

Still not works

npm install:
![00](https://user-images.githubusercontent.com/49929520/109236678-196c5400-779e-11eb-8fc4-afdfbc2337c1.jpg)

@jbf-insidesherpa

Can some help me to fix this?

**Comment by megactrl** [comment]
You can skip npm install step by downloading the node_modules from // https://drive.google.com/file/d/1amF7C-4mRZCi3Ab5xuH0XCRQubp4aa_t/view //. And replace the node_modules folder inside JPMC-tech-task-2-PY3 with the one you downloaded from the link mentioned above.
Now you just need to execute `npm start`

**Comment by woolosh** [comment]
I'm using a PC, Windows 10, and a Chrome browser.  I get the "Failed to compile" error after running "npm start".  I got even more errors before that when running "npm install".  

The **Failed to compile** error points to the _Graph.tsx_ file in the _src_ folder.  Specifically to line 2:  **import { Table } from '@jpmorganchase/perspective';**

The error goes away, and it all seems to load fine for me when I change "jpmorganchase" to "finos".
As in: 

import { Table } from '@**jpmorganchase**/perspective';

**changes to**

import { Table } from '@**finos**/perspective';

**Comment by miguelfa77** [comment]
<img width="986" alt="Screenshot 2022-03-30 at 13 48 23" src="https://user-images.githubusercontent.com/100728907/161337320-a15dd3e7-f8de-4602-b9c6-c8468aead0ae.png">
I have MacOS Monterey
node.js is version v16.14.2
npm is  v8.5.0
Had to change node version from v11.0.0 as it told me it wasn't compatible with npm
Installed node_modules and put it inside JPMC-tech-task-2-PY3 folder and still fails to compile.
