### ISSUE TITLE
npm install error

### ISSUE THREAD

**Issue by adititiwari19** [insidesherpa/JPMC-tech-task-2-PY3#302]
I've been working on this for days and have tried about every route possible to fix my issues. Every different thing I do that someone recommends, I get another error set.
![Capture2](https://user-images.githubusercontent.com/60397028/82965281-4b6d4180-9fe5-11ea-8596-1596431700b8.JPG)
![Capture](https://user-images.githubusercontent.com/60397028/82965288-4d370500-9fe5-11ea-9f61-880f82fca1cd.JPG)

**Comment by adititiwari19** [comment]
I tried everything from the very beginning again...still the same.
![Capture](https://user-images.githubusercontent.com/60397028/82967614-fbdd4480-9fe9-11ea-8ed6-243882e90800.JPG)

**Comment by JKeerthi-21** [comment]
Use the following commands:

npm install
npm install --ignore-scripts
npm audit fix
npm start

It worked :)

**Comment by adititiwari19** [comment]
It works now.
Thankyou for your help :)
