### ISSUE TITLE
npm error in troubleshooting

### ISSUE THREAD

**Issue by Roshni-Bajpai** [insidesherpa/JPMC-tech-task-2-PY3#304]
after running npm start command, i am getting following:
npm ERR! cide ENOENT
npm ERR! syscall open
npm ERR! path C:\Users\ROSHNI\package.json
npm ERR! enoent ENOENT: no such file or directory, open 'C:\Users\ROSHNI\package.json'
npm ERR! A complete log of this run can be found in:
npm ERR!  C:\Users\ROSHNI\AppData\Roaming\npm-cache\_logs\2020-05-27T13_22_20_585Z-debug.log

**Comment by Geno2208** [comment]
@Roshni-Bajpai  run the npm command in the JPMC-tech-task folder that you downloaded.

**Comment by Roshni-Bajpai** [comment]
can't i use visual studio code instead of vs build tools?
