### ISSUE TITLE
 Load the table in the perspective-viewer

### ISSUE THREAD

**Issue by neissacodes** [insidesherpa/JPMC-tech-task-2-PY3#31]
I am having trouble writing this code and believe that's why my graph is not showing. 
![persp](https://user-images.githubusercontent.com/47401355/73314650-6036f580-41fc-11ea-8fc3-8c46c75a1838.PNG)

**Comment by aayush1204** [comment]
how did u solve this error?. I think im having the same problem

**Comment by neissacodes** [comment]
Make sure that all quotes are closed. That was my issue.
