### ISSUE TITLE
Cannot clone files from GitHub 

### ISSUE THREAD

**Issue by Yedzinovich** [insidesherpa/JPMC-tech-task-2-PY3#32]
"LibreSSL SSL_connect: SSL_ERROR_SYSCALL in connection to github.com:443"

This is the ere that I have when I try to clone from GitHub to MacOS. 
I have this issue after updating git and stopping Kaspersky. 

Can you help me with it?

**Comment by jbf-insidesherpa** [comment]
@Yedzinovich can you post a screenshot of what you're doing on your terminal
