### ISSUE TITLE
Error on command npm install and start

### ISSUE THREAD

**Issue by nitindang** [insidesherpa/JPMC-tech-task-2-PY3#339]
C:\Users\Dell>**npm install**
npm WARN saveError ENOENT: no such file or directory, open 'C:\Users\Dell\package.json'
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\Dell\package.json'
npm WARN Dell No description
npm WARN Dell No repository field.
npm WARN Dell No README data
npm WARN Dell No license field.

audited 3 packages in 1.172s
found 0 vulnerabilities

C:\Users\Dell>**npm start**
npm ERR! path C:\Users\Dell\package.json
npm ERR! code ENOENT
npm ERR! errno -4058
npm ERR! syscall open
npm ERR! enoent ENOENT: no such file or directory, open 'C:\Users\Dell\package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Dell\AppData\Roaming\npm-cache\_logs\2020-06-07T13_01_43_729Z-debug.log

**Comment by MahimaJindalMJ** [comment]
I am facing the same problem. Somebody please help.

If I run the **npm start** command in **JPMC-tech-task-2-PY3** directory, I get the error given below.

C:\Users\Mahima\JPMC-tech-task-2-PY3>**npm start**

> bank-merge-co-task-2@0.1.0 start C:\Users\Mahima\JPMC-tech-task-2-PY3
> react-scripts start

'react-scripts' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! bank-merge-co-task-2@0.1.0 start: `react-scripts start`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bank-merge-co-task-2@0.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Mahima\AppData\Roaming\npm-cache\_logs\2020-06-07T12_59_29_788Z-debug.log

**Comment by nitindang** [comment]
> I am facing the same problem. Somebody please help.
> 
> If I run the **npm start** command in **JPMC-tech-task-2-PY3** directory, I get the error given below.
> 
> C:\Users\Mahima\JPMC-tech-task-2-PY3>**npm start**
> 
> > bank-merge-co-task-2@0.1.0 start C:\Users\Mahima\JPMC-tech-task-2-PY3
> > react-scripts start
> 
> 'react-scripts' is not recognized as an internal or external command,
> operable program or batch file.
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! bank-merge-co-task-2@0.1.0 start: `react-scripts start`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the bank-merge-co-task-2@0.1.0 start script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR! C:\Users\Mahima\AppData\Roaming\npm-cache_logs\2020-06-07T12_59_29_788Z-debug.log

My current error is this 
I ran it in the JPMC task 2 directory now but I am still facing these issues

C:\Users\Dell\JPMC-tech-task-2-PY3>npm install

bufferutil@3.0.5 install C:\Users\Dell\JPMC-tech-task-2-PY3\node_modules\bufferutil
prebuild-install || node-gyp rebuild

prebuild-install WARN install No prebuilt binaries found (target=11.0.0 runtime=node arch=x64 platform=win32)

C:\Users\Dell\JPMC-tech-task-2-PY3\node_modules\bufferutil>if not defined npm_config_node_gyp (node "C:\Users\Dell\AppData\Roaming\nvm\v11.0.0\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\....\node_modules\node-gyp\bin\node-gyp.js" rebuild ) else (node "C:\Users\Dell\AppData\Roaming\nvm\v11.0.0\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
Traceback (most recent call last):
File "C:\Users\Dell\AppData\Roaming\nvm\v11.0.0\node_modules\npm\node_modules\node-gyp\gyp\gyp_main.py", line 16, in
sys.exit(gyp.script_main())
File "C:\Users\Dell\AppData\Roaming\nvm\v11.0.0\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp_init_.py", line 545, in script_main
return main(sys.argv[1:])
File "C:\Users\Dell\AppData\Roaming\nvm\v11.0.0\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp_init_.py", line 538, in main
return gyp_main(args)
File "C:\Users\Dell\AppData\Roaming\nvm\v11.0.0\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp_init_.py", line 514, in gyp_main
options.duplicate_basename_check)
File "C:\Users\Dell\AppData\Roaming\nvm\v11.0.0\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp_init_.py", line 98, in Load
generator.CalculateVariables(default_variables, params)
File "C:\Users\Dell\AppData\Roaming\nvm\v11.0.0\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\generator\msvs.py", line 1916, in CalculateVariables
generator_flags.get('msvs_version', 'auto'))
File "C:\Users\Dell\AppData\Roaming\nvm\v11.0.0\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\MSVSVersion.py", line 434, in SelectVisualStudioVersion
versions = _DetectVisualStudioVersions(version_map[version], 'e' in version)
KeyError: '2019'
gyp ERR! configure error
gyp ERR! stack Error: gyp failed with exit code: 1
gyp ERR! stack at ChildProcess.onCpExit (C:\Users\Dell\AppData\Roaming\nvm\v11.0.0\node_modules\npm\node_modules\node-gyp\lib\configure.js:345:16)
gyp ERR! stack at ChildProcess.emit (events.js:182:13)
gyp ERR! stack at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)
gyp ERR! System Windows_NT 10.0.18363
gyp ERR! command "C:\Program Files\nodejs\node.exe" "C:\Users\Dell\AppData\Roaming\nvm\v11.0.0\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\Dell\JPMC-tech-task-2-PY3\node_modules\bufferutil
gyp ERR! node -v v11.0.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm WARN rollback Rolling back node-pre-gyp@0.10.0 failed (this is probably harmless): EPERM: operation not permitted, lstat 'C:\Users\Dell\JPMC-tech-task-2-PY3\node_modules\fsevents\node_modules'
npm WARN bootstrap@4.2.1 requires a peer of jquery@1.9.1 - 3 but none is installed. You must install peer dependencies yourself.
npm WARN bootstrap@4.2.1 requires a peer of popper.js@^1.14.6 but none is installed. You must install peer dependencies yourself.
npm WARN extract-text-webpack-plugin@3.0.2 requires a peer of webpack@^3.1.0 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! bufferutil@3.0.5 install: prebuild-install || node-gyp rebuild
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bufferutil@3.0.5 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR! C:\Users\Dell\AppData\Roaming\npm-cache_logs\2020-06-07T14_33_42_883Z-debug.log

**Comment by nitindang** [comment]
> I am facing the same problem. Somebody please help.
> 
> If I run the **npm start** command in **JPMC-tech-task-2-PY3** directory, I get the error given below.
> 
> C:\Users\Mahima\JPMC-tech-task-2-PY3>**npm start**
> 
> > bank-merge-co-task-2@0.1.0 start C:\Users\Mahima\JPMC-tech-task-2-PY3
> > react-scripts start
> 
> 'react-scripts' is not recognized as an internal or external command,
> operable program or batch file.
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! bank-merge-co-task-2@0.1.0 start: `react-scripts start`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the bank-merge-co-task-2@0.1.0 start script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR! C:\Users\Mahima\AppData\Roaming\npm-cache_logs\2020-06-07T12_59_29_788Z-debug.log




Use the following commands:

npm install
npm install --ignore-scripts
npm audit fix
npm start

It worked :)

**Comment by MahimaJindalMJ** [comment]
> > I am facing the same problem. Somebody please help.
> > If I run the **npm start** command in **JPMC-tech-task-2-PY3** directory, I get the error given below.
> > C:\Users\Mahima\JPMC-tech-task-2-PY3>**npm start**
> > > bank-merge-co-task-2@0.1.0 start C:\Users\Mahima\JPMC-tech-task-2-PY3
> > > react-scripts start
> > 
> > 
> > 'react-scripts' is not recognized as an internal or external command,
> > operable program or batch file.
> > npm ERR! code ELIFECYCLE
> > npm ERR! errno 1
> > npm ERR! bank-merge-co-task-2@0.1.0 start: `react-scripts start`
> > npm ERR! Exit status 1
> > npm ERR!
> > npm ERR! Failed at the bank-merge-co-task-2@0.1.0 start script.
> > npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> > npm ERR! A complete log of this run can be found in:
> > npm ERR! C:\Users\Mahima\AppData\Roaming\npm-cache_logs\2020-06-07T12_59_29_788Z-debug.log
> 
> Use the following commands:
> 
> npm install
> npm install --ignore-scripts
> npm audit fix
> npm start
> 
> It worked :)

Yes npm install worked using your given commands but npm start is not working in my case.

C:\Users\Mahima\JPMC-tech-task-2-PY3>**npm start**

> bank-merge-co-task-2@0.1.0 start C:\Users\Mahima\JPMC-tech-task-2-PY3
> react-scripts start


There might be a problem with the project dependency tree.
It is likely not a bug in Create React App, but something you need to fix locally.

The react-scripts package provided by Create React App requires a dependency:

  "babel-loader": "8.0.4"

Don't try to install it manually: your package manager does it automatically.
However, a different version of babel-loader was detected higher up in the tree:

  C:\Users\Mahima\JPMC-tech-task-2-PY3\node_modules\babel-loader (version: 8.1.0)

Manually installing incompatible versions is known to cause hard-to-debug issues.

If you would prefer to ignore this check, add SKIP_PREFLIGHT_CHECK=true to an .env file in your project.
That will permanently disable this message but you might encounter other issues.

To fix the dependency tree, try following the steps below in the exact order:

  1. Delete package-lock.json (not package.json!) and/or yarn.lock in your project folder.
  2. Delete node_modules in your project folder.
  3. Remove "babel-loader" from dependencies and/or devDependencies in the package.json file in your project folder.
  4. Run npm install or yarn, depending on the package manager you use.

In most cases, this should be enough to fix the problem.
If this has not helped, there are a few other things you can try:

  5. If you used npm, install yarn (http://yarnpkg.com/) and repeat the above steps with it instead.
     This may help because npm has known issues with package hoisting which may get resolved in future versions.

  6. Check if C:\Users\Mahima\JPMC-tech-task-2-PY3\node_modules\babel-loader is outside your project directory.
     For example, you might have accidentally installed something in your home folder.

  7. Try running npm ls babel-loader in your project folder.
     This will tell you which other package (apart from the expected react-scripts) installed babel-loader.

If nothing else helps, add SKIP_PREFLIGHT_CHECK=true to an .env file in your project.
That would permanently disable this preflight check in case you want to proceed anyway.

P.S. We know this message is long but please read the steps above :-) We hope you find them helpful!

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! bank-merge-co-task-2@0.1.0 start: `react-scripts start`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bank-merge-co-task-2@0.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Mahima\AppData\Roaming\npm-cache\_logs\2020-06-08T12_46_40_167Z-debug.log

I am getting this error now. Don't know what to do :(
