### ISSUE TITLE
NPM start issue

### ISSUE THREAD

**Issue by jsto5983** [insidesherpa/JPMC-tech-task-2-PY3#34]
Hi I receive the following issue when trying to NPM start
<img width="729" alt="NPM Start" src="https://user-images.githubusercontent.com/50561570/73940605-d4ca0c80-493f-11ea-9d9d-43259544557e.png">
This is the output when I run NPM install:
<img width="910" alt="NPM Install" src="https://user-images.githubusercontent.com/50561570/73940635-e3182880-493f-11ea-9e72-5491be8f443a.png">

And I have mapped the npm python command to python 2.7 as suggested in the installation instructions.
.

**Comment by timothykmulenga** [comment]
Failed to compile
/home/tim/Desktop/project_jp/JPMC-tech-task-2-PY3/src/Graph.tsx
Type error: Cannot find module '@jpmorganchase/perspective'.  TS2307

    1 | import React, { Component } from 'react';
  > 2 | import { Table } from '@jpmorganchase/perspective';
      |                       ^
    3 | import { ServerRespond } from './DataStreamer';
    4 | import './Graph.css';
    5 | 
This error occurred during the build time and cannot be dismissed.

> For me when i run npm start i the browser opens but i keep getting this error after the page load. help
[screencapture-localhost-3000-2020-02-07-08_27_57 (2).pdf](https://github.com/insidesherpa/JPMC-tech-task-2-PY3/files/4169308/screencapture-localhost-3000-2020-02-07-08_27_57.2.pdf)
![screencapture-localhost-3000-2020-02-07-08_27_57](https://user-images.githubusercontent.com/60673572/74006561-b1758080-4984-11ea-9557-0e9ab2f22a0d.png)

**Comment by jbf-insidesherpa** [comment]
> Hi I receive the following issue when trying to NPM start
> <img alt="NPM Start" width="729" src="https://user-images.githubusercontent.com/50561570/73940605-d4ca0c80-493f-11ea-9d9d-43259544557e.png">
> This is the output when I run NPM install:
> <img alt="NPM Install" width="910" src="https://user-images.githubusercontent.com/50561570/73940635-e3182880-493f-11ea-9e72-5491be8f443a.png">
> 
> And I have mapped the npm python command to python 2.7 as suggested in the installation instructions.
> .

@jsto5983 try this: https://stackoverflow.com/questions/53912056/npm-start-on-new-create-react-app-build-returns-elifecycle-error

**Comment by jbf-insidesherpa** [comment]
> Failed to compile
> /home/tim/Desktop/project_jp/JPMC-tech-task-2-PY3/src/Graph.tsx
> Type error: Cannot find module '@jpmorganchase/perspective'. TS2307
> 
> ```
> 1 | import React, { Component } from 'react';
> ```
> 
> > 2 | import { Table } from '@jpmorganchase/perspective';
> > |                       ^
> > 3 | import { ServerRespond } from './DataStreamer';
> > 4 | import './Graph.css';
> > 5 |
> > This error occurred during the build time and cannot be dismissed.
> 
> > For me when i run npm start i the browser opens but i keep getting this error after the page load. help
> > [screencapture-localhost-3000-2020-02-07-08_27_57 (2).pdf](https://github.com/insidesherpa/JPMC-tech-task-2-PY3/files/4169308/screencapture-localhost-3000-2020-02-07-08_27_57.2.pdf)
> > ![screencapture-localhost-3000-2020-02-07-08_27_57](https://user-images.githubusercontent.com/60673572/74006561-b1758080-4984-11ea-9557-0e9ab2f22a0d.png)

@timothykmulenga you probably encountered errors when you ran `npm install`. please check the error output you got and refer to the troubleshooting slides in the setup guide as we've discussed the issues there

**Comment by jsto5983** [comment]
> > Hi I receive the following issue when trying to NPM start
> > <img alt="NPM Start" width="729" src="https://user-images.githubusercontent.com/50561570/73940605-d4ca0c80-493f-11ea-9d9d-43259544557e.png">
> > This is the output when I run NPM install:
> > <img alt="NPM Install" width="910" src="https://user-images.githubusercontent.com/50561570/73940635-e3182880-493f-11ea-9e72-5491be8f443a.png">
> > And I have mapped the npm python command to python 2.7 as suggested in the installation instructions.
> > .
> 
> @jsto5983 try this: https://stackoverflow.com/questions/53912056/npm-start-on-new-create-react-app-build-returns-elifecycle-error

Thanks so much! That did progress things but I now get the following error and can't connect to the local host: 

<img width="763" alt="Screen Shot 2020-02-08 at 5 25 15 pm" src="https://user-images.githubusercontent.com/50561570/74080431-31d8d600-4a98-11ea-935b-8c76a1445aae.png">

**Comment by jsto5983** [comment]
> > Hi I receive the following issue when trying to NPM start
> > <img alt="NPM Start" width="729" src="https://user-images.githubusercontent.com/50561570/73940605-d4ca0c80-493f-11ea-9d9d-43259544557e.png">
> > This is the output when I run NPM install:
> > <img alt="NPM Install" width="910" src="https://user-images.githubusercontent.com/50561570/73940635-e3182880-493f-11ea-9e72-5491be8f443a.png">
> > And I have mapped the npm python command to python 2.7 as suggested in the installation instructions.
> > .
> 
> @jsto5983 try this: https://stackoverflow.com/questions/53912056/npm-start-on-new-create-react-app-build-returns-elifecycle-error

Thanks so much! It is now working!
