### ISSUE TITLE
Server Not Running: Type Error / ThreadedHTTPServer troubles

### ISSUE THREAD

**Issue by lenghuang** [insidesherpa/JPMC-tech-task-2-PY3#35]
## Can't Start the Server
Hello, I'm having issues with starting the server. When I run `python3 server3.py` it gives me the below terminal error. When I open the file on VSCode, it raises the bellow VSCode errors. How can I get the server runnning?

## Terminal Error
![Screen Shot 2020-03-17 at 1 07 00 PM](https://user-images.githubusercontent.com/32604574/76882250-c4675480-6850-11ea-8318-981691651672.png)

## VSCode Error
![Screen Shot 2020-03-17 at 1 11 58 PM](https://user-images.githubusercontent.com/32604574/76882346-e7920400-6850-11ea-875e-fdb6d553acfe.png)

**Comment by jbf-insidesherpa** [comment]
@lenghuang sorry to get back to this only now. It probably has to do with your python3 version. Please use Python3.7 to be safe.
