### ISSUE TITLE
Error: Cannot find module on windows 10 and python 3.7.3 

### ISSUE THREAD

**Issue by Ishitajindal99** [insidesherpa/JPMC-tech-task-2-PY3#358]
Failed to compile
C:/Users/HP/JPMC-tech-task-2-PY3/src/Graph.tsx
Type error: Cannot find module '@jpmorganchase/perspective'.  TS2307

    1 | import React, { Component } from 'react';
  > 2 | import { Table } from '@jpmorganchase/perspective';
      |                       ^
    3 | import { ServerRespond } from './DataStreamer';
    4 | import './Graph.css';
    5 |

**Comment by rb-ctrl** [comment]
https://github.com/insidesherpa/JPMC-tech-task-2/issues/174#issuecomment-634612840

Go back on to the terminal and type the following:

npm install
npm install --ignore-scripts
npm audit fix
npm start

Worked for me!
