### ISSUE TITLE
Getting error when NPM Install and NPM Start

### ISSUE THREAD

**Issue by vermakriti** [insidesherpa/JPMC-tech-task-2-PY3#381]
![Screenshot from 2020-06-21 09-49-10](https://user-images.githubusercontent.com/48256667/85216782-8aa16f00-b3a6-11ea-83f8-f2234b6789ad.png)
![Screenshot from 2020-06-21 10-02-11](https://user-images.githubusercontent.com/48256667/85216784-8e34f600-b3a6-11ea-8eda-0ebdad6bb39e.png)

Please help me out

**Comment by utkarsh5474** [comment]
Since it's closed, can you let me know how you handled the error

**Comment by vermakriti** [comment]
> Since it's closed, can you let me know how you handled the error

before executing the command " npm install" we have to execute "npm init -g " where g make it global. It will create package.json file where in "script" key there will be only one value which is "test".There should be one more key "start". so put it over there like "start": ""
Hope It will help you :)
