### ISSUE TITLE
npm install causing dependencies warnings

### ISSUE THREAD

**Issue by samhithatarra** [insidesherpa/JPMC-tech-task-2-PY3#39]
<img width="680" alt="Screen Shot 2020-03-31 at 11 40 37 PM" src="https://user-images.githubusercontent.com/50003533/78106884-3ab79b00-73a9-11ea-879a-98b4ad6c0726.png">

**Comment by Priyandubey** [comment]
Hey, @samhithatarra  have you got a solution to this?

**Comment by samhithatarra** [comment]
nope

**Comment by Priyandubey** [comment]
Just run this line after "npm install"  :-
"npm audit fix" it fixed for me.

**Comment by samhithatarra** [comment]
<img width="569" alt="Screen Shot 2020-04-01 at 10 30 50 PM" src="https://user-images.githubusercontent.com/50003533/78213849-a6147200-7468-11ea-8896-12ce0f950866.png">


hmm this is what I get when I run that, still more errors

**Comment by jbf-insidesherpa** [comment]
@samhithatarra those are just warnings. Those shouldn't block you.
