### ISSUE TITLE
pip dependencies issue

### ISSUE THREAD

**Issue by FatimaR-SE** [insidesherpa/JPMC-tech-task-2-PY3#4]
before making any change to task 2, I ran the server and client without any issue. as soon as I made changes to the src/App.tsx and src/Graph.tsx and try to run server3.py in Datafeed folder( i am using python 3) it starts giving me pip dateutil dependencies issue. I installed pip multiple times and also set with the Windows environment path but the issue is still there. any suggestion.

**Comment by jbf-insidesherpa** [comment]
@FatimaR-SE have you resolved this issue?

**Comment by Naman-1234** [comment]
@FatimaR-SE  Pls can u tell us if u have resolved this issue as this same issue is with me amd ,any others, I have too installed pip  and then set it on environment variable but even it says that dateutil.parser not found
It will be very kind of you if u share how u resolved it,Pls resolve it
