### ISSUE TITLE
issue with server3.py not running

### ISSUE THREAD

**Issue by nmnick18** [insidesherpa/JPMC-tech-task-2-PY3#40]
issue is on line 244 with self._sim_start. Its apparently a StopIteration error. not exactly sure why this is an issue, cause I looked at the code and it should work.

**Comment by Barb0ra** [comment]
I'm getting the same thing. This is from the admin command prompt
`C:\Users\CS\JPMC-tech-task-2-PY3\datafeed>python server3.py
Traceback (most recent call last):
  File "server3.py", line 320, in <module>
    run(App())
  File "server3.py", line 244, in __init__
    self._sim_start, _, _  = next(self._data_1)
StopIteration`

**Comment by nmnick18** [comment]
> I'm getting the same thing. This is from the admin command prompt
> `C:\Users\CS\JPMC-tech-task-2-PY3\datafeed>python server3.py Traceback (most recent call last): File "server3.py", line 320, in <module> run(App()) File "server3.py", line 244, in __init__ self._sim_start, _, _ = next(self._data_1) StopIteration`

Have u found a solution. I wrote some code to stop the iteration error.

**Comment by nmnick18** [comment]
It's not right, and it doesn't fix the situation. I also went In to the linux terminal and listened to the port 8080, nothing was on it either

**Comment by jbf-insidesherpa** [comment]
@Barb0ra execute the command outside of the datafeed folder. i.e. you should be in the root folder of the repo and that should work. cc @nmnick18

**Comment by 9916103020** [comment]
@Barb0ra do you run cmd as administrator??

**Comment by arunprakashpj** [comment]
I am also facing the same issue! I am running the cmd as an administrator only!

**Comment by 9916103020** [comment]
@nmnick18 if your problem is resolved please close this issue:)
