### ISSUE TITLE
Type error: Cannot find module '@jpmorganchase/perspective'.  TS2307

### ISSUE THREAD

**Issue by abhishekthakur0** [insidesherpa/JPMC-tech-task-2-PY3#402]

**Comment by abhishekthakur0** [comment]
I tried installing updated version of node and npm but still this error is showing.
what is issue with this and how to solve it?

**Comment by MrSandman34** [comment]
I got the same error as well. It showed 'Fail to compile' in Chrome, as well as in the terminal.

**Comment by allenwu038** [comment]
I also had this error, in Safari as well.

**Comment by allenwu038** [comment]
Upon some digging into past issues, I found this series of commands from issue #386 and it worked for me !

npm install
npm install --ignore-scripts
npm audit fix
npm start

**Comment by abhishekthakur0** [comment]
@allenwu038 Thanks
