### ISSUE TITLE
Failed to compile on executing npm start

### ISSUE THREAD

**Issue by KRN05** [insidesherpa/JPMC-tech-task-2-PY3#41]
I am getting an error when I am trying to start the development server using command **npm start**.
It says **Can't resolve 'react' in 'C:\Users\krnbd\JPMC-tech-task-2-PY3\src**.
Although it redirects me to Bank & Merger Co webpage, there also I get the same error.

I restarted everything and encountered a new error on a command python datafeed/server3.py.
It says, ImportError: No module named dateutil.parser

Please help me in resolving these issues
![Screenshot (277)](https://user-images.githubusercontent.com/35370516/78141311-f4b21400-7448-11ea-83a3-21382b2d1308.png)
![Screenshot (279)](https://user-images.githubusercontent.com/35370516/78141334-fc71b880-7448-11ea-9b1a-5099e37d9375.png)
![Screenshot (278)](https://user-images.githubusercontent.com/35370516/78141349-009dd600-7449-11ea-9694-b8c87ebe4b15.png)

**Comment by jbf-insidesherpa** [comment]
@KRN05 apologies for just getting back to you on this. Have you done **npm install** properly with no errors? (warnings are fine but errors are not). If your **npm install** throws errors in the command line after, please send your screenshot here (the troubleshooting slides also address the common ones btw)

As for the python error you got, that's also discussed in the troubleshooting slides. You need to install pip first and then install python dateutil package by doing **pip install python-dateutil**

**Comment by 9916103020** [comment]
@KRN05 above error "Can't resolve 'react' in 'C:\Users\krnbd\JPMC-tech-task-2-PY3\src" only appears when you have not installed npm correctly and second error just types pip install python-dateutil in your command prompt. As told by @jbf-insidesherpa.
The second option you can go to troubleshooting page and directly install node modules and paste in the JPMtech folder and run npm start.

**Comment by KRN05** [comment]
Thanks @9916103020 

@jbf-insidesherpa I restarted everything from the beginning and now the error is different, I have added a new issue to begin fresh. Please respond to that issue.

Thanks.
