### ISSUE TITLE
Issue with starting up NPM

### ISSUE THREAD

**Issue by DamiAdesola** [insidesherpa/JPMC-tech-task-2-PY3#424]
<img width="1440" alt="Screen Shot 2020-07-14 at 3 31 49 PM" src="https://user-images.githubusercontent.com/63448215/87420919-31181300-c5e7-11ea-8abc-ccdfa4ab91df.png">

Upon running "npm start", there is an error that pops up in the Graph.tsx file stating," Cannot find module '@jpmorganchase/perspective' or its corresponding type declarations.ts(2307)".

Please assist me in sorting out this issue. I have additionally attached screenshots for reference.
<img width="1440" alt="Screen Shot 2020-07-14 at 4 47 05 PM" src="https://user-images.githubusercontent.com/63448215/87427377-bc96a180-c5f1-11ea-8943-56c7624ac7c3.png">

**Comment by taransuresh** [comment]
I am also having the same problem on MacOS, running python3.

**Comment by taransuresh** [comment]
Found a good fix in this thread. https://github.com/insidesherpa/JPMC-tech-task-2-PY3/issues/411#issuecomment-653245056. Worked for me.
