### ISSUE TITLE
NPM install error

### ISSUE THREAD

**Issue by jslalen** [insidesherpa/JPMC-tech-task-2-PY3#43]
I am using windows 10, I have installed everything except npm, "npm config set python /path/to/executable/python" I can't see the effect of this command too. I have  set python in my system to map to python2.7.x
![Screenshot (66)](https://user-images.githubusercontent.com/50656151/78427732-b3607500-7691-11ea-8667-fd20ad661483.png)

**Comment by loueff** [comment]
I'm seeing a simplify failure for node-gyp.  Using the Python 3 version of the repository, but I've used npm config to set the path to the Python 2.7 executable.

**Comment by loueff** [comment]
Can confirm that removing the old `node_modules` from the folder and replacing it with the version provided via Google Drive appears to solve the issue.

**Comment by jslalen** [comment]
Thanks for the suggestion, but now there is an issue with npm start, installation process is complete with some warnings. I have changed the path back to python 3.8 again after installing the npm.
![Screenshot (67)](https://user-images.githubusercontent.com/50656151/78452763-d3e8f900-76aa-11ea-8f82-f52bad531ba3.png)

**Comment by jbf-insidesherpa** [comment]
@jslalen make sure you copied the node_modules correctly. It seems some downloads fail and that's why when you extract it you get missing folders/files like what's happened in your case.

**Comment by jslalen** [comment]
I was using the wrong link earlier, I saw the correct link for windows in slides and now it works, thanks @loueff and @jbf-insidesherpa .

**Comment by Faizi-alpha** [comment]
I am facing the same issue. Help me out please.I am running python 3.8 and also installed python 2.7 which comes with windows-build-tools. when I type npm config set msvs_version 2017 in cmd (As Admin) nothing happens . Please help me out . I have Visual Studio 2019 version installed
