### ISSUE TITLE
npm isn't getting installed,  it fails at bufferutil@3.0.5

### ISSUE THREAD

**Issue by gbhanuteja23** [insidesherpa/JPMC-tech-task-2-PY3#431]
for Task-2 of JPMorgan Chase & Co Virtual Experience programme.

I am facing difficulties in installing npm.

nvm is successfully installed and I can see it's version

But when I try to install npm using install npm, I am getting errors.

I even tried to copy and paste node_modules which I have downloaded from the link provided in the pdf and then when I type start npm,  I am still getting errors.

I have tried installing npm three times but always, it gets failed at bufferutil.    

[2020-07-18T12_57_54_702Z-debug.log](https://github.com/insidesherpa/JPMC-tech-task-2-PY3/files/4941686/2020-07-18T12_57_54_702Z-debug.log)
![Task-2 npm install error pic-2](https://user-images.githubusercontent.com/45899803/87853170-a22c3300-c925-11ea-8657-e1304020faea.jpg)
![Task-2 npm install error](https://user-images.githubusercontent.com/45899803/87853177-aeb08b80-c925-11ea-85cc-9b22213b8315.jpg)

**Comment by Saib098765** [comment]
i got the same error too

**Comment by gbhanuteja23** [comment]
> i got the same error too

After copying node_modules which I have downloaded from the link which was provided in the pdf to git Repository. " npm start" command is running and web app gets opened in localhost successfully.
