### ISSUE TITLE
LOCALHOST SHOWING FAILED TO COMPILE 

### ISSUE THREAD

**Issue by savers72** [insidesherpa/JPMC-tech-task-2-PY3#433]
![Screenshot (317)](https://user-images.githubusercontent.com/31322127/88022263-99697600-cb4c-11ea-8d44-dd94a9441a1d.png)
initially, it showed that package.json not found. I installed it. It showed the below result.
![Screenshot (315)](https://user-images.githubusercontent.com/31322127/88022521-0da41980-cb4d-11ea-8548-d06e933c1be7.png)

**Comment by aminuabdusalam** [comment]
I am having the same issue.

**Comment by savers72** [comment]
> I am having the same issue.

hey , look at #386. my issue got solved

**Comment by aminuabdusalam** [comment]
Thanks a lot. I'd check it out.
