### ISSUE TITLE
Failed to Compile: Cannot resolve 'react'

### ISSUE THREAD

**Issue by adarshrai1998** [insidesherpa/JPMC-tech-task-2-PY3#434]
Can anyone help in resolving this issue?

#Failed to compile.

./src/index.tsx
Module not found: Can't resolve 'react' in 'C:\Users\<username>\JPMC-tech-task-2-PY3\src'

![Screenshot (3)](https://user-images.githubusercontent.com/32388921/88260893-e67f5080-cce2-11ea-85ea-c4e402f9a212.png)

**Comment by sandramolina** [comment]
Hey, did you manage to fix it? thanks!
