### ISSUE TITLE
Issue with npm install and start

### ISSUE THREAD

**Issue by Tanya1999-cmyk** [insidesherpa/JPMC-tech-task-2-PY3#439]
![Screenshot (32)](https://user-images.githubusercontent.com/53026472/88524696-4fcece80-d017-11ea-859e-2d5fea2f30d4.png)
![Screenshot (33)](https://user-images.githubusercontent.com/53026472/88524700-51989200-d017-11ea-9fe1-80cc3ad84738.png)
![Screenshot (34)](https://user-images.githubusercontent.com/53026472/88524702-52312880-d017-11ea-9458-a651be035681.png)
![Screenshot (35)](https://user-images.githubusercontent.com/53026472/88524705-52312880-d017-11ea-9a17-f4e4ed90c3af.png)

I am working on windows 64 bit operating system. I have install python 3.8.4 successfully without any error but i am finding issues in installing npm . I have tried all the possible troubleshooting possible but none worked including replacing node_modules from repo. I am working on repo JPMC-tech-task-2-py3. kindly guide me!

**Comment by Chaithu97** [comment]
1. change the directory: users\Tanya\ cd JPMC-tech-task-2-PY3
2. Do: npm config set msvs_version 2017
3. npm install
4. npm start

Note: Connect to the sever through administrator, before executing in client
