### ISSUE TITLE
npm install says 0 vulnerabilities but npm start gives errors

### ISSUE THREAD

**Issue by Amgg12301** [insidesherpa/JPMC-tech-task-2-PY3#45]
I've attached screenshots for what happens when I execute 'npm install' and 'npm start'. 'npm install' provides a few warnings but says 0 vulnerabilities, and then 'npm start' says it cannot find a file somehow, even though I followed all the previous instructions exactly. 
<img width="569" alt="Screen Shot 2020-04-06 at 7 06 52 PM" src="https://user-images.githubusercontent.com/15021251/78613481-fcebc400-7839-11ea-99f3-c8e4635d5b36.png">
<img width="565" alt="Screen Shot 2020-04-06 at 7 07 12 PM" src="https://user-images.githubusercontent.com/15021251/78613504-0b39e000-783a-11ea-86ca-f8bbb68e2e2d.png">

**Comment by 9916103020** [comment]
@Amgg12301 you have to reach the JPMC-tech-task-2-PY3 folder through the terminal and then click npm install and npm start.

**Comment by Amgg12301** [comment]
Nevermind, npm start works just fine now. Thank you for the help!

**Comment by 9916103020** [comment]
@Amgg12301 could you tell me whether there is an error in bufferutil??

**Comment by Amgg12301** [comment]
I don't think there is an error with bufferutil, for me at least.
