### ISSUE TITLE
File "server3.py", line 320, in run(App()) File "server3.py", line 244, in init self._sim_start, _, _ = next(self._data_1) StopIteration  Got the above error as well

### ISSUE THREAD

**Issue by HeeketMehta** [insidesherpa/JPMC-tech-task-2-PY3#47]

**Comment by HeeketMehta** [comment]
File "server3.py", line 320, in run(App()) File "server3.py", line 244, in init self._sim_start, _, _ = next(self._data_1) StopIteration  Got the above error as well

**Comment by HeeketMehta** [comment]
I got the above error while running server3.py file on administrator command prompt

**Comment by 9916103020** [comment]
@HeeketMehta did use '''pip install python-dateutil''' ??

**Comment by HeeketMehta** [comment]
@9916103020 thank you so much - it was of great help. Might have missed out in the troubleshooting slide, anyways, thanks a lot for the help!!

**Comment by 9916103020** [comment]
@HeeketMehta is your problem solved??
If yes close this issue:)
