### ISSUE TITLE
Cannot find module '@jpmorganchase/perspective'

### ISSUE THREAD

**Issue by abhinav-bhardwaj** [insidesherpa/JPMC-tech-task-2-PY3#485]
![image](https://user-images.githubusercontent.com/35636061/104089649-8d0ddc80-5296-11eb-9b68-7ffe1202e502.png)

**Comment by Albert-Jokelin** [comment]
I deleted package-lock.json then deleted node_modules, then  opened pacakge.json and replaced the @jpmorganchase/perspectvie_%random_Strings% with
"@finos/perspective": "^0.6.0",
"@finos/perspective-viewer": "^0.6.0",

"@finos/perspective-viewer-highcharts": "^0.5.2",

and then opened graph.tsx under src and changed the imports to:

import React, { Component } from 'react';
import { Table } from '@finos/perspective';
import { ServerRespond } from './DataStreamer';
import './Graph.css';

run `python datafeed/server3.py` (I use py3)
then
 `npm install`
  `npm start`
(exact order)

For reference: 
Package.json
`{
  "name": "bank-merge-co-task-2",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "@finos/perspective": "^0.6.0",
    "@finos/perspective-viewer": "^0.6.0",
    "@finos/perspective-viewer-highcharts": "^0.5.2",
    "@types/jest": "^23.3.13",
    "@types/node": "^10.12.19",
    "@types/react": "^16.9.0",
    "@types/react-dom": "^16.0.11",
    "bootstrap": "^4.6.0",
    "puppeteer": "^1.19.0",
    "react": "^16.9.0",
    "react-dom": "^16.9.0",
    "react-scripts": "^4.0.1"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject"
  },
  "eslintConfig": {
    "extends": "react-app"
  },
  "browserslist": [
    ">0.2%",
    "not dead",
    "not ie <= 11",
    "not op_mini all"
  ],
  "devDependencies": {
    "awesome-typescript-loader": "^5.2.1",
    "source-map-loader": "^0.2.4",
    "typescript": "^3.2.4"
  }
}
`
Graph.tsx
`import React, { Component } from 'react';
import { Table } from '@finos/perspective';
import { ServerRespond } from './DataStreamer';
import './Graph.css';

/**
 * Props declaration for <Graph />
 */
interface IProps {
  data: ServerRespond[],
}

/**
 * Perspective library adds load to HTMLElement prototype.
 * This interface acts as a wrapper for Typescript compiler.
 */
interface PerspectiveViewerElement {
  load: (table: Table) => void,
}

/**
 * React component that renders Perspective based on data
 * parsed from its parent through data property.
 */
class Graph extends Component<IProps, {}> {
  // Perspective table
  table: Table | undefined;

  render() {
    return React.createElement('perspective-viewer');
  }

  componentDidMount() {
    // Get element to attach the table from the DOM.
    const elem: PerspectiveViewerElement = document.getElementsByTagName('perspective-viewer')[0] as unknown as PerspectiveViewerElement;

    const schema = {
      stock: 'string',
      top_ask_price: 'float',
      top_bid_price: 'float',
      timestamp: 'date',
    };

    if (window.perspective && window.perspective.worker()) {
      this.table = window.perspective.worker().table(schema);
    }
    if (this.table) {
      // Load the `table` in the `<perspective-viewer>` DOM reference.

      // Add more Perspective configurations here.
      elem.load(this.table);
    }
  }

  componentDidUpdate() {
    // Everytime the data props is updated, insert the data into Perspective table
    if (this.table) {
      // As part of the task, you need to fix the way we update the data props to
      // avoid inserting duplicated entries into Perspective table again.
      this.table.update(this.props.data.map((el: any) => {
        // Format the data from ServerRespond to the schema
        return {
          stock: el.stock,
          top_ask_price: el.top_ask && el.top_ask.price || 0,
          top_bid_price: el.top_bid && el.top_bid.price || 0,
          timestamp: el.timestamp,
        };
      }));
    }
  }
}

export default Graph;
`

**Comment by HaardikBhagtani** [comment]
Thank you @Albert-Jokelin for your help.
