### ISSUE TITLE
npm install and start errors

### ISSUE THREAD

**Issue by rmoh13** [insidesherpa/JPMC-tech-task-2-PY3#49]
I have a macOS Catalina, and as I tried to ran npm install I encountered the following issues after doing npm audit fix and npm start over and over again
<img width="740" alt="Screen Shot 2020-04-10 at 3 21 22 AM" src="https://user-images.githubusercontent.com/15274309/78971976-b7015b00-7ada-11ea-9494-d6239c688140.png">
<img width="738" alt="Screen Shot 2020-04-10 at 3 21 36 AM" src="https://user-images.githubusercontent.com/15274309/78971994-bcf73c00-7ada-11ea-9dd5-1180892b37d5.png">
<img width="741" alt="Screen Shot 2020-04-10 at 3 21 47 AM" src="https://user-images.githubusercontent.com/15274309/78972001-c08ac300-7ada-11ea-9d7a-cd782cc3e263.png">
<img width="752" alt="Screen Shot 2020-04-10 at 3 22 04 AM" src="https://user-images.githubusercontent.com/15274309/78972006-c2548680-7ada-11ea-8aa0-ec22a6b108eb.png">
there were just so many issues with npm install, and I thought it had to do with the fact that I was using a later version than the one in the task, but even after doing nvm use v11.0.0, nothing changed, I got the same errors

**Comment by rmoh13** [comment]
The reason why I didn't delete package-lock.json, the node_modules, and the babel-loader is because I was afraid it would modify the task execution code/web app in a bad way and I was afraid it would casue more errors. Am I wrong about this? I don't want to make any irreversible changes.

**Comment by 9916103020** [comment]
@rmoh13 you delete package-loc.json will not have any effect. From here I can see you have 2 methods to carry on.
First: delete node_modules and then again type npm install.
Second: you can go to troubleshoot and directly install the node_module folder and paste it in the JPMC-tech folder and hit npm start in command prompt.

**Comment by rmoh13** [comment]
I'm still getting the following error because the task uses outdated versions of the the packages I've installed
<img width="1021" alt="Screen Shot 2020-04-10 at 10 21 46 AM" src="https://user-images.githubusercontent.com/15274309/78997768-36138500-7b15-11ea-806f-226e6ca2d7b0.png">

**Comment by rmoh13** [comment]
I followed the instructions and skipped step 3 because eslint wasn't even in the dependencies and the devDependencies, and got the following error
<img width="1057" alt="Screen Shot 2020-04-10 at 10 41 48 AM" src="https://user-images.githubusercontent.com/15274309/78999128-02862a00-7b18-11ea-9341-5acfcfa99f87.png">

**Comment by rmoh13** [comment]
This is my logging output after copying and pasting the NPM modules from troubleshoot and deleting package-lock.json:
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/Users/rmoh13/.nvm/versions/node/v13.8.0/bin/node',
1 verbose cli   '/Users/rmoh13/.nvm/versions/node/v13.8.0/bin/npm',
1 verbose cli   'start'
1 verbose cli ]
2 info using npm@6.14.4
3 info using node@v13.8.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle bank-merge-co-task-2@0.1.0~prestart: bank-merge-co-task-2@0.1.0
6 info lifecycle bank-merge-co-task-2@0.1.0~start: bank-merge-co-task-2@0.1.0
7 verbose lifecycle bank-merge-co-task-2@0.1.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle bank-merge-co-task-2@0.1.0~start: PATH: /Users/rmoh13/.nvm/versions/node/v13.8.0/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/rmoh13/Documents/JPMC-tech-task-2-PY3/node_modules/.bin:/Users/rmoh13/.nvm/versions/node/v13.8.0/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin
9 verbose lifecycle bank-merge-co-task-2@0.1.0~start: CWD: /Users/rmoh13/Documents/JPMC-tech-task-2-PY3
10 silly lifecycle bank-merge-co-task-2@0.1.0~start: Args: [ '-c', 'react-scripts start' ]
11 silly lifecycle bank-merge-co-task-2@0.1.0~start: Returned: code: 1  signal: null
12 info lifecycle bank-merge-co-task-2@0.1.0~start: Failed to exec start script
13 verbose stack Error: bank-merge-co-task-2@0.1.0 start: `react-scripts start`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/Users/rmoh13/.nvm/versions/node/v13.8.0/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:321:20)
13 verbose stack     at ChildProcess.<anonymous> (/Users/rmoh13/.nvm/versions/node/v13.8.0/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:321:20)
13 verbose stack     at maybeClose (internal/child_process.js:1026:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
14 verbose pkgid bank-merge-co-task-2@0.1.0
15 verbose cwd /Users/rmoh13/Documents/JPMC-tech-task-2-PY3
16 verbose Darwin 19.3.0
17 verbose argv "/Users/rmoh13/.nvm/versions/node/v13.8.0/bin/node" "/Users/rmoh13/.nvm/versions/node/v13.8.0/bin/npm" "start"
18 verbose node v13.8.0
19 verbose npm  v6.14.4
20 error code ELIFECYCLE
21 error errno 1
22 error bank-merge-co-task-2@0.1.0 start: `react-scripts start`
22 error Exit status 1
23 error Failed at the bank-merge-co-task-2@0.1.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by rmoh13** [comment]
It is a matter of the task using an old version of npm, so I uninstalled my current npm, went to the old npm, uninstalled my current eslint, installed the new eslint, and now it works fine

**Comment by neilpatel12** [comment]
> It is a matter of the task using an old version of npm, so I uninstalled my current npm, went to the old npm, uninstalled my current eslint, installed the new eslint, and now it works fine

Can you go into more detail on your solution please, how did you uninstall npm, how did you install the older version of npm? What is eslint?
