### ISSUE TITLE
Server.py error

### ISSUE THREAD

**Issue by nitesh982** [insidesherpa/JPMC-tech-task-2-PY3#491]
When running the server3.py I am facing error.
![Screenshot 2021-02-06 133817](https://user-images.githubusercontent.com/32352362/107112836-aa779b80-6880-11eb-8fde-fbda8c818cbb.png)

**Comment by Parv-B-zz** [comment]
I'm experiencing the same error.

**Comment by aritrakar** [comment]
Try the following:
1. cd .. (goes into the JPMC-tech-task-2 or JPMC-tech-task-2-py3 folder)
2. python datafeed/server3.py

**Comment by benjaminspak** [comment]
Thanks @aritrakar! That did the trick.
