### ISSUE TITLE
npm start error

### ISSUE THREAD

**Issue by emmanuel-jr** [insidesherpa/JPMC-tech-task-2-PY3#51]
![npm start error](https://user-images.githubusercontent.com/56479785/79113772-e4e6d980-7d3e-11ea-964f-ca345b835921.png)

I have downloaded the node_modules folder and pasted it to the JPMC-tech-task-2-PY3 folder but I still get errors.
Please help.

**Comment by SiddhlodaAyyar** [comment]
Watch this video and if you still get the error comment down in the youtube section and we'll try to solve it.
https://youtu.be/wRAG9i8O_44
