### ISSUE TITLE
Error with nvm node version install

### ISSUE THREAD

**Issue by vivekptnk** [insidesherpa/JPMC-tech-task-2-PY3#513]
**I am having issues installing nvm 11.0.0 with the command nvm install 11.0.0. Attached screenshot below
I need some help resolving this issue**

<img width="828" alt="Screen Shot 2021-07-06 at 7 27 30 PM" src="https://user-images.githubusercontent.com/30744832/124678375-610f9480-de90-11eb-8f82-1f4b49e5647e.png">

**Comment by tpakkal1** [comment]
Same issue, did you find a solution?

**Comment by vivekptnk** [comment]
I didn’t, I let go of the internship because of other commitments

**Comment by surajawal7** [comment]
I also had same issue with Mac M1
If you are using Mac M1, perform the nvm install and nvm start actions using terminal with rosetta support. Perfectly works for me.
