### ISSUE TITLE
npm install/start error on windows

### ISSUE THREAD

**Issue by narayanrachit** [insidesherpa/JPMC-tech-task-2-PY3#52]
I have installed all the files and tried all the troubleshooting ways but still, its showing the following error which I have attached 
<img width="611" alt="Error" src="https://user-images.githubusercontent.com/53686465/79121258-82c7bc00-7db2-11ea-884e-17c37f82d54e.PNG">

**Comment by skritichauhan** [comment]
Change the directory to where you have cloned the following repository 
git clone https://github.com/insidesherpa/JPMC-tech-task-2.git or
git clone https://github.com/insidesherpa/JPMC-tech-task-2-PY3.git
Change to this directory and then use the command : npm install and then npm start

**Comment by narayanrachit** [comment]
Thank you @skritichauhan for your help. I proceeded according to what you said, I am getting the following errors. Can you please help me. Thanks in advance.

<img width="951" alt="error 1" src="https://user-images.githubusercontent.com/53686465/80185031-4bb29f80-8629-11ea-881b-f507b0a27a92.PNG">

**Comment by SiddhlodaAyyar** [comment]
Watch this video and if you still get the error comment down in the youtube section and we'll try to solve it.
https://youtu.be/wRAG9i8O_44

**Comment by narayanrachit** [comment]
Thank you all for helping! Mine worked with the following commands:

1.npm install --force
2.npm audit fix
3.npm start
