### ISSUE TITLE
nvm use command not working

### ISSUE THREAD

**Issue by afua-ansah** [insidesherpa/JPMC-tech-task-2-PY3#524]
Hello, I use a Windows 10 and I have successfully installed nvm. However, the 'nvm use 11.0.0' command doesn't work, it returns an exit status message;

PS C:\Users\Afua Ansah> nvm use 11.0.0
exit status 1: 'C:\Users\Afua' is not recognized as an internal or external command,
operable program or batch file.

**Comment by touchtoshibu** [comment]
i am facing same issue in windows 8

**Comment by afua-ansah** [comment]
I am suspecting it is a bug in the nvm code that isn't able to parse user names with spaces in them

**Comment by afua-ansah** [comment]
so I just found a link to some possible fixes to the situation, this happens when there are spaces in the pathnames
https://github.com/coreybutler/nvm-windows/wiki/Common-Issues#spaces-in-pathnamesinstallation-root
