### ISSUE TITLE
Getting ERR! when running npm install 

### ISSUE THREAD

**Issue by lkorchnoy** [insidesherpa/JPMC-tech-task-2-PY3#542]
Hi everyone! I'm trying to resolve the following issue. I run npm install I get gyp ERR! node-gyp -v v3.8.0 

I have tried just about everything. There may be a problem with project dependency tree. 

I created .env file and added SKIP_PREFLIGHT_CHECK=true in the project and it did not resolve the issue.

If you had a similar issue and was able to resolve it please share.

**Comment by Meshaal-Mouawad** [comment]
I got the same and have to go directly to the websites and download it. I think the instructions for the project are not completed.
make sure you are using the cmd as administer > you are in the folder of your project

**Comment by lkorchnoy** [comment]
I cloned the repository for the 2nd and 3rd tasks in my older computer. Specified 'nvm use v11.0.0' (since I already have it installed) in the terminal and run 'npm install' and 'npm start' without any issues. It was somewhat challenging to set up an environment in MacBook M1, for this task, and downloading node_modules and adding it to the project solves this issue. Thank you!
