### ISSUE TITLE
npm install (Windows)

### ISSUE THREAD

**Issue by Kevirodr7558** [insidesherpa/JPMC-tech-task-2-PY3#547]
C:\Users\Kevin\JPMC-tech-task-2-PY3>npm install
npm WARN saveError ENOENT: no such file or directory, open 'C:\Users\Kevin\JPMC-tech-task-2-PY3\package.json'
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\Kevin\JPMC-tech-task-2-PY3\package.json'
npm WARN JPMC-tech-task-2-PY3 No description
npm WARN JPMC-tech-task-2-PY3 No repository field.
npm WARN JPMC-tech-task-2-PY3 No README data
npm WARN JPMC-tech-task-2-PY3 No license field.

audited 2 packages in 0.591s
found 0 vulnerabilities

C:\Users\Kevin\JPMC-tech-task-2-PY3>npm start
npm ERR! path C:\Users\Kevin\JPMC-tech-task-2-PY3\package.json
npm ERR! code ENOENT
npm ERR! errno -4058
npm ERR! syscall open
npm ERR! enoent ENOENT: no such file or directory, open 'C:\Users\Kevin\JPMC-tech-task-2-PY3\package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Kevin\AppData\Roaming\npm-cache\_logs\2021-11-15T05_36_43_215Z-debug.log

**_### I need help getting past this step. I've already downloaded Visual C++ Build Tools, but I always get this problem once I try running and installing. I'm fairly new at this so whatever solution or explanation will work. Thank you!_**

**Comment by naveensathya7** [comment]
how did you resolved this issue ?
