### ISSUE TITLE
npm install and start errors on windows 10 python3

### ISSUE THREAD

**Issue by bengalad** [insidesherpa/JPMC-tech-task-2-PY3#56]
I have looked at the troubleshooting section and downloaded the google drive files for node_modules yet it is still not working. Any help I would be very grateful, I've been struggling with the set up.

![Screenshot (44)](https://user-images.githubusercontent.com/63682462/79282016-fdc0cd80-7eab-11ea-8eae-6328231c719d.png)

**Comment by insidesherpa** [comment]
Hi Bengalad,

It looks like NPM is not installed - make sure you check out the npm website for installation.

Kind regards,

Pasha

*Pasha Rayan*
Cofounder

*M:* 0482 017 281

*E:* pasha@insidesherpa.com
*L:* linkedin.com/in/pasharayan/ ( http://linkedin.com/in/pasharayan/ )

*US:* Level 4, 575 Market Street, San Francisco, California

*AU:* Room 22, Level 8, 66 Goulburn Street, Sydney, Australia **

-----

🎉 InsideSherpa has just raised $2.5 mil from leading Venture Capital around the world!

📰 InsideSherpa has also been featured on:

**Comment by bengalad** [comment]
Thank you for the reply, now I am facing a new issue.

When I try npm install the message in the pictures come up. Also if I just execute npm start anyway the web browser opens up and says it has failed to compile, however I have installed the C++ developer tool(2019) already. 


![Screenshot (50)](https://user-images.githubusercontent.com/63682462/79355914-3311fd80-7f36-11ea-9823-b05125c4a76e.png)
![Screenshot (51)](https://user-images.githubusercontent.com/63682462/79355916-33aa9400-7f36-11ea-8385-95930c3ccc55.png)
![Screenshot (52)](https://user-images.githubusercontent.com/63682462/79355918-34432a80-7f36-11ea-964c-b3ffd5bbda28.png)
![Screenshot (53)](https://user-images.githubusercontent.com/63682462/79355922-35745780-7f36-11ea-891a-8c5aa7b11f50.png)
