### ISSUE TITLE
npm issues- says puppeteer@1.20.0: Version no longer supported.

### ISSUE THREAD

**Issue by backstreetberry** [insidesherpa/JPMC-tech-task-2-PY3#568]
Im using python through anaconda and have given proper path as env variable. Still Im facing following errors. Please help me.
![Screenshot 2022-02-26 102210](https://user-images.githubusercontent.com/93029804/155829685-96216932-73f2-4448-a2d5-9d5c32a5453f.png)
![Screenshot 2022-02-26 102253](https://user-images.githubusercontent.com/93029804/155829698-a7c467cc-7134-4764-89f3-218e3d38c309.png)

**Comment by matthewibrahim2025** [comment]
What did you do? Im facing the same issue?
