### ISSUE TITLE
Unable to figure out Perspective configurations

### ISSUE THREAD

**Issue by bengalad** [insidesherpa/JPMC-tech-task-2-PY3#57]
I can't seem to get the Perspective configurations to work. I have followed the code on the pdf document and gone to various other sites to check syntax, however none seem to help. Could you please point me in the right direction.

![Screenshot (54)](https://user-images.githubusercontent.com/63682462/79401968-6e3a1e00-7f82-11ea-8f85-5524feae155b.png)

**Comment by 9916103020** [comment]
Hope this will resolve your error:) Happy to help:)
![resolve](https://user-images.githubusercontent.com/22716123/80313986-1f0aad80-880c-11ea-8cf3-41b947959eeb.PNG)

**Comment by bengalad** [comment]
Thanks, I managed to figure out the problem.
