### ISSUE TITLE
Hi i am unable to change the cd since i am new to this could you please help me solving this issue and also im having trouble installing npm

### ISSUE THREAD

**Issue by soyaba05** [insidesherpa/JPMC-tech-task-2-PY3#58]
![Problem](https://user-images.githubusercontent.com/56362682/79567794-a2265800-80d6-11ea-8c9b-d852c4580be0.jpg)
![Problem](https://user-images.githubusercontent.com/56362682/79567848-b702eb80-80d6-11ea-8b5a-4072a3dc967f.jpg)

**Comment by soyaba05** [comment]
hi i think i could change the directory but now i have a different problem attached below
<img width="680" alt="Screenshot 2020-04-19 at 5 35 07 PM" src="https://user-images.githubusercontent.com/56362682/79686737-59040e80-8264-11ea-8329-579c147cbb5a.png">

**Comment by 9916103020** [comment]
@soyaba05 this error is due to incorrect installation of pm. could you please go through troubleshoot page. Hope this will resolve your error:)

**Comment by soyaba05** [comment]
Thankyou so much i will now close the issue.
