### ISSUE TITLE
npm error code ELIFCYCLE

### ISSUE THREAD

**Issue by abmn12** [insidesherpa/JPMC-tech-task-2-PY3#59]
![Screenshot (2)](https://user-images.githubusercontent.com/57004001/79633883-e708c800-8184-11ea-87a1-e484333f0489.png)
I dont see any issues which has an error similar to mine 
I have executed this with node-v:11.0.0
npm -v: 6.4.1
python 3.x

**Comment by saifeemustafaq** [comment]
Hey, even I am facing the same problem. Can you please tell me how you resolved it? Thankyou.
