### ISSUE TITLE
Error Installing NPM

### ISSUE THREAD

**Issue by Manasasarva** [insidesherpa/JPMC-tech-task-2-PY3#592]
![Screenshot (13)](https://user-images.githubusercontent.com/110013433/181033316-ddcfb227-da34-442e-84d3-b79a1da93a4e.png)

**Comment by naveensathya7** [comment]
how did you resolve npm install and npm start errors,i'm stuck at that errors
![error](https://user-images.githubusercontent.com/110328622/182018058-62577051-e803-454d-8a8d-38bb4c2e0ed3.png)
