### ISSUE TITLE
Can't access "Perspective configurations particularly on the table.view configurations" link

### ISSUE THREAD

**Issue by HenryUdeogu** [insidesherpa/JPMC-tech-task-2-PY3#6]
![Screen Shot 2019-11-06 at 8 12 34 AM](https://user-images.githubusercontent.com/42478135/68305419-45296f00-006d-11ea-9339-8a46a7f9f06a.png)
![Screen Shot 2019-11-06 at 8 12 54 AM](https://user-images.githubusercontent.com/42478135/68305420-45296f00-006d-11ea-8f58-dc1bb2ee6cea.png)

**Comment by jbf-insidesherpa** [comment]
@HenryUdeogu sorry we'll fix that part in the doc. Here's the right link:
https://github.com/finos/perspective/tree/master/packages/perspective#tableviewconfig--view
