### ISSUE TITLE
Warning during npm install and error in npm start

### ISSUE THREAD

**Issue by natanAlper** [insidesherpa/JPMC-tech-task-2-PY3#63]
Hi,
Not sure what to do with warnings during "npm install" which I'm assuming is what is causing the errors during "npm start". There is no change in the command prompt that is running the server.
![warning1](https://user-images.githubusercontent.com/64056058/80053246-73e7b480-84ea-11ea-8dfe-f5826ccf0da3.PNG)
![server1](https://user-images.githubusercontent.com/64056058/80053309-a0033580-84ea-11ea-8d76-2aaeb4b963f0.PNG)

**Comment by nagasai17** [comment]
same error.Did you find any solution?

**Comment by kevintu2** [comment]
You need to cd into the repository first (i.e) JPMC-tech-task-2-py3

**Comment by natanAlper** [comment]
Yes! That fixed the issue (although now I'm on the Case A issue from the slides)
Thanks!
