### ISSUE TITLE
npm ERR! code ELIFECYCLE

### ISSUE THREAD

**Issue by saifeemustafaq** [insidesherpa/JPMC-tech-task-2-PY3#65]
PS C:\Users\mustafa\JPMC-tech-task-2-PY3> npm install
> bufferutil@3.0.5 install C:\Users\mustafa\JPMC-tech-task-2-PY3\node_modules\bufferutil
> prebuild-install || node-gyp rebuild

prebuild-install WARN install No prebuilt binaries found (target=11.0.0 runtime=node arch=x64 platform=win32)

C:\Users\mustafa\JPMC-tech-task-2-PY3\node_modules\bufferutil>if not defined npm_config_node_gyp (node "C:\Users\mustafa\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\mustafa\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
gyp ERR! configure error
gyp ERR! stack Error: Command failed: C:\Program Files\Python38\python.EXE -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                       ^
gyp ERR! stack SyntaxError: invalid syntax
gyp ERR! stack
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:289:12)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at maybeClose (internal/child_process.js:962:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
gyp ERR! System Windows_NT 10.0.17763
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\mustafa\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\mustafa\JPMC-tech-task-2-PY3\node_modules\bufferutil
gyp ERR! node -v v11.0.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm WARN bootstrap@4.2.1 requires a peer of jquery@1.9.1 - 3 but none is installed. You must install peer dependencies yourself.
npm WARN bootstrap@4.2.1 requires a peer of popper.js@^1.14.6 but none is installed. You must install peer dependencies yourself.
npm WARN extract-text-webpack-plugin@3.0.2 requires a peer of webpack@^3.1.0 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! bufferutil@3.0.5 install: `prebuild-install || node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bufferutil@3.0.5 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\mustafa\AppData\Roaming\npm-cache\_logs\2020-04-23T17_28_10_725Z-debug.log

C:\Users\mustafa\JPMC-tech-task-2-PY3>

![err eliecycle 2](https://user-images.githubusercontent.com/15520369/80130424-1013c900-8588-11ea-9f4c-f1898a4a971a.PNG)

**Comment by saifeemustafaq** [comment]
C:\Users\mustafa\JPMC-tech-task-2-PY3>npm -v
6.14.4

C:\Users\mustafa\JPMC-tech-task-2-PY3>node -v
v12.16.2

C:\Users\mustafa\JPMC-tech-task-2-PY3>nvm -v

Running version 1.1.7.

**Comment by saifeemustafaq** [comment]
[2020-04-23T13_14_15_760Z-debug.log](https://github.com/insidesherpa/JPMC-tech-task-2-PY3/files/4523388/2020-04-23T13_14_15_760Z-debug.log)


This is the generated log file

**Comment by saifeemustafaq** [comment]
This is the solution if someone else is facing this:
Delete the node_modules folder from your JPMC-tech-task-2-PY3 folder.
Download the node_modules folder from the link given below and place it in your JPMC-tech-task-2-PY3 folder. It will probably solve the problem.

https://drive.google.com/file/d/1ML6nECK18J0jM3hhfJdSCRtCNLssruYQ/view

**Comment by 1UC1F3R616** [comment]
@saifeemustafaq can u explain what's causing this problem. And how is this downloaded file solving it
and file name suggests it's for windows OS. Mine is Linux

**Comment by 1UC1F3R616** [comment]
Refer [here](https://stackoverflow.com/questions/42308879/npm-err-code-elifecycle) to solve this issue
