### ISSUE TITLE
"python: can't open file 'datafeed/server.py': [Errno 2] No such file or directory"

### ISSUE THREAD

**Issue by cathy-yue** [insidesherpa/JPMC-tech-task-2-PY3#66]
Hello, I am on a Windows operation system using command prompt terminal. I was able to install python 3 and pip fine. But when I was running the 'python datafeed/server.py' command I get an error that says 

"python: can't open file 'datafeed/server.py': [Errno 2] No such file or directory"

I tried running this command in both command prompt and administrator command prompt and got the same issue. I can't seem to find this issue on the troubleshooting slides and I am stuck.

**Comment by saifeemustafaq** [comment]
I hope your working directory is in JPMC-tech-task-2-PY3
while typing the command, type this:
python datafeed/server3.py

simply copy paste the above command

**Comment by cathy-yue** [comment]
> I hope your working directory is in JPMC-tech-task-2-PY3
> while typing the command, type this:
> python datafeed/server3.py
> 
> simply copy paste the above command

Hello! Yes I was working in that directory and your command worked. It's interesting that that command wasn't one provided in the instructions. However, that command worked and I am able to move on now. Thank you!

**Comment by saifeemustafaq** [comment]
Happy to help :)
