### ISSUE TITLE
Cannot find module '@jpmorganchase/perspective'.

### ISSUE THREAD

**Issue by rohitm131** [insidesherpa/JPMC-tech-task-2-PY3#70]
after running the application the following is happening.
![Screenshot from 2020-04-25 02-28-06](https://user-images.githubusercontent.com/43905130/80256509-70942a80-869c-11ea-81c3-ae8a7fe62926.png)

**Comment by hisourav4u** [comment]
Open the troubleshoot section and replace the "node_modules" in the downloaded folder with the one provided in https://drive.google.com/file/d/1ML6nECK18J0jM3hhfJdSCRtCNLssruYQ/view

After that no need to use "npm install"
just use "npm start"

**Comment by hisourav4u** [comment]
I was having various kinds of problems while using npm install, npm start. I tried a lot of things. Only this works for me.

**Comment by Dev-Temmy** [comment]
> I was having various kinds of problems while using npm install, npm start. I tried a lot of things. Only this works for me.

Thanks hisoura4u, it works for me too.

**Comment by 9916103020** [comment]
@Dev-Temmy close the issue if it works:)
