### ISSUE TITLE
npm Install Error

### ISSUE THREAD

**Issue by pranavaddepalli** [insidesherpa/JPMC-tech-task-2-PY3#74]
Running on Windows 64 bit, installed nvm and node correctly with the right versions too. I keep getting this error when I am trying to run the "npm install" command though.

I have python 3.7 installed, but I have already configured npm to use a python 2.7 installation on my computer too.

Here is the error I am repeatedly getting:
![Capture](https://user-images.githubusercontent.com/46876327/80297913-a517ed00-8755-11ea-9763-14b65dfaf0d4.PNG)

**Comment by saifeemustafaq** [comment]
Delete the node_modules folder from your JPMC-tech-task-2-PY3 folder.
Download the node_modules folder from the link given below and place it in your JPMC-tech-task-2-PY3 folder. It will probably solve the problem.

https://drive.google.com/file/d/1ML6nECK18J0jM3hhfJdSCRtCNLssruYQ/view
