### ISSUE TITLE
Problem with NPM Install (Resolved)

### ISSUE THREAD

**Issue by Sourish-Mukherjee** [insidesherpa/JPMC-tech-task-2-PY3#76]
Attaching the log file :
[2020-04-26T07_10_55_808Z-debug.log](https://github.com/insidesherpa/JPMC-tech-task-2-PY3/files/4534800/2020-04-26T07_10_55_808Z-debug.log)

Please help

**Comment by 9916103020** [comment]
@Sourish-Mukherjee  this error only occurs because you haven't installed npm correctly please read troubleshoot page also where there is a link from where you can directly install node module folder and paste it to JPMC folder and directly run npm start from your terminal:)
Hope this helps you:)

**Comment by Sourish-Mukherjee** [comment]
Yeah I fixed it, seems like I had to do npm set python python3.8 and then update my npm
