### ISSUE TITLE
Error during npm start.

### ISSUE THREAD

**Issue by KRN05** [insidesherpa/JPMC-tech-task-2-PY3#78]
This is the error that I am facing during npm install. 

![Screenshot (395)](https://user-images.githubusercontent.com/35370516/80306439-f8834d00-87e0-11ea-9c87-7e24152acff9.png)

And when I  run the command npm start, I encountered below error.
Please help me to resolve these issues.
![Screenshot (396)](https://user-images.githubusercontent.com/35370516/80306484-41d39c80-87e1-11ea-8376-f553760cc626.png)

**Comment by saifeemustafaq** [comment]
Delete the node_modules folder from your JPMC-tech-task-2-PY3 folder.
Download the node_modules folder from the link given below and place it in your JPMC-tech-task-2-PY3 folder. It will probably solve the problem.

https://drive.google.com/file/d/1ML6nECK18J0jM3hhfJdSCRtCNLssruYQ/view

**Comment by 9916103020** [comment]
@KRN05 I also encountered the same issue and please follow what @saifeemustafaq has said.
I also want to say you to please check your Microsoft visual build tools version and also that npm is configured with python 2 since node-gyp only works in python 2:)
Hope I was helpful:)

**Comment by KRN05** [comment]
It worked, thanks @saifeemustafaq @9916103020
