### ISSUE TITLE
Issue while running server3.py file (python3.8) 

### ISSUE THREAD

**Issue by sehgalromal** [insidesherpa/JPMC-tech-task-2-PY3#83]
![issue](https://user-images.githubusercontent.com/17382065/80391695-777d9180-8884-11ea-973b-f64335f458b3.PNG)

My python environment is correctly setup and working fine. But, when i try to run server3.py it throws "Stop Iteration" Error.

**Comment by laveshmittal** [comment]
Facing same issue

**Comment by 9916103020** [comment]
@sehgalromal @laveshmittal have you checked which version python you are using if its python 3 only then above code is right otherwise checking the version and running terminal as admin and run below command outside JPMC folder
`python3 datafeed/server3.py`
Note: run cmd as admin must:)

**Comment by sehgalromal** [comment]
@laveshmittal  Thanks, it worked !.

**Comment by binnydara** [comment]
@9916103020  thanks man it worked !!
