### ISSUE TITLE
Failed at the bufferutil@3.0.5 install script.

### ISSUE THREAD

**Issue by 1UC1F3R616** [insidesherpa/JPMC-tech-task-2-PY3#88]
When running `npm install` then getting below error

![Screenshot from 2020-04-28 04-11-06](https://user-images.githubusercontent.com/41824020/80427956-6d9c7280-8906-11ea-8d2a-5db61b0b7fe7.png)

Tried some solutions but didn't worked
[npm-err-code-elifecycle](https://stackoverflow.com/questions/42308879/npm-err-code-elifecycle)
[this](https://github.com/nodejs/node-gyp/issues/1195)

**Comment by 9916103020** [comment]
@1UC1F3R616 this is only because npm is installed properly please go through troubleshooting page in slide:) Hope there you can resolve it:)

**Comment by 1UC1F3R616** [comment]
@9916103020 npm is installed correctly and troubleshoot page don’t have this issue.
I think the problem is with the installation of multiple npm versions maybe. IDK.

**Comment by 9916103020** [comment]
run `nvm use v11.0.0`

**Comment by 9916103020** [comment]
@1UC1F3R616 if still, the error doesn't go away please install node_modules directly from troubleshooting through google drive and then just go to the terminal as admin and start your npm from JPMC folder and run directly `npm start`

**Comment by 1UC1F3R616** [comment]
@9916103020 ok thankyou, I will try this out

**Comment by Dhruv-Garg79** [comment]
I was having the same issue when I tried with node 12.13.0. 
use node version 10 or 11, it worked for me with 10.17.0

**Comment by 1UC1F3R616** [comment]
Error Remain unknown to me as I am not a node pro.
I tried downloading and replacing not module as per the advice by @9916103020 and it worked. -Thanks, bro
@Dhruv-Garg79 I tried with node 11, didn't work. Haven't tested with other versions.

Download [node_module](https://drive.google.com/open?id=1amF7C-4mRZCi3Ab5xuH0XCRQubp4aa_t) provided in ppts also.
