### ISSUE TITLE
Failing npm install issue !!

### ISSUE THREAD

**Issue by sarimurrab** [insidesherpa/JPMC-tech-task-2-PY3#89]
![Screenshot from 2020-04-28 14-31-02](https://user-images.githubusercontent.com/35756749/80468933-7ff5cb00-895d-11ea-9b33-79beaf208ba2.png)
![Screenshot from 2020-04-28 14-31-17](https://user-images.githubusercontent.com/35756749/80468965-87b56f80-895d-11ea-9c75-118902d5641f.png)

**Comment by naman99lalit** [comment]
Yeah! I am also getting the same errors in Linux. If you find any solution, then please post it here. 
Thanks

**Comment by sarimurrab** [comment]
Okay.
I found the solution.
Actually there is a requirement of python2.7 for node-gyp.
So
1. First, delete the npm_module folder in the repo.
2. Download python 2.7.x externally.
3. Then fire up the command `npm config set python /usr/bin/python` for linux.
4. then `npm install`
5. end `npm start`

**Comment by naman99lalit** [comment]
Thanks a lot for the help :)
