### ISSUE TITLE
failed to compile:error in code

### ISSUE THREAD

**Issue by somya1706551** [insidesherpa/JPMC-tech-task-2-PY3#92]
![Screenshot (135)](https://user-images.githubusercontent.com/61082132/80503054-fc54d200-898e-11ea-951b-bfeb8b057319.png)

**Comment by 9916103020** [comment]
@somya1706551 bufferutil error is only because npm is not installed correctly please go through troubleshooting page in slides:)

**Comment by Inderjeet0003** [comment]
> @somya1706551 bufferutil error is only because npm is not installed correctly please go through troubleshooting page in slides:)

maybe network problem or u should allow permissions to node.js from ur window defender or anything else probably that is causing this error coz i faced the same earlier.

**Comment by somya1706551** [comment]
> @somya1706551 bufferutil error is only because npm is not installed correctly please go through troubleshooting page in slides:)

exactly I am getting this errors repeatedly while installing npm

**Comment by somya1706551** [comment]
@9916103020 exactly I am getting this errors repeatedly while installing npm.

**Comment by somya1706551** [comment]
![Screenshot (136)](https://user-images.githubusercontent.com/61082132/80631103-e15b8e00-8a72-11ea-858d-db4c86a35657.png)

**Comment by 9916103020** [comment]
@somya1706551 go through troubleshoot page there is a link and install node_module folder directly from there and then delete old and paste this one and then directly go to terminal and run npm start from JPMC folder directory.Hope this will help you:)

**Comment by somya1706551** [comment]
@9916103020 thank you but now another error showed up
![Screenshot (137)](https://user-images.githubusercontent.com/61082132/80692669-8ae06500-8aef-11ea-885f-ded88688544b.png)

**Comment by somya1706551** [comment]
![Screenshot (138)](https://user-images.githubusercontent.com/61082132/80720735-f55aca80-8b1a-11ea-9d81-52eb97443c73.png)
