### ISSUE TITLE
Argument of type '{ stock: string; top_ask_price: string; top_bid_price: string; timestamp: string; }' is not assignable to parameter of type 'string'. facing this error while executing the below code 

### ISSUE THREAD

**Issue by AnimeshMaheshwari22** [insidesherpa/JPMC-tech-task-2-PY3#97]
![Screenshot (38)](https://user-images.githubusercontent.com/45392539/80619313-304cf780-8a62-11ea-9e38-cb04bc00ff53.png)

**Comment by 9916103020** [comment]
Hope this will help you:)
![resolve](https://user-images.githubusercontent.com/22716123/80632978-a9097f00-8a75-11ea-9e87-6b2d832971e4.PNG)

**Comment by AnimeshMaheshwari22** [comment]
Yes that worked. Thanks a lot!
